// Code generated by Fern. DO NOT EDIT.

package callrecording

import (
	context "context"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	option "github.com/wavix/wavix-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a paginated list of call recordings for the authenticated account, filtered by date range, number, call, or SIP trunk.
func (c *Client) List(
	ctx context.Context,
	request *wavixgosdk.ListCallRecordingRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.CallRecordingListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Redirects to the recording file for the call identified by `call_id`. The download URL is returned in the `Location` header.
func (c *Client) GetByCall(
	ctx context.Context,
	request *wavixgosdk.GetByCallCallRecordingRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.GetByCall(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Returns the call recording identified by `id`, including its metadata and download URL.
func (c *Client) Get(
	ctx context.Context,
	request *wavixgosdk.GetCallRecordingRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.Recording, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes the call recording identified by `id`. Deletion is permanent and removes the recording file.
func (c *Client) Delete(
	ctx context.Context,
	request *wavixgosdk.DeleteCallRecordingRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.SuccessResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
