// Code generated by Fern. DO NOT EDIT.

package config

import (
	context "context"
	http "net/http"

	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	option "github.com/wavix/wavix-go-sdk/option"
	profile "github.com/wavix/wavix-go-sdk/profile"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*profile.GetConfigResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.wavix.com",
	)
	endpointURL := baseURL + "/v1/profile/config"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *profile.GetConfigResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(profile.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*profile.GetConfigResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
