// Code generated by Fern. DO NOT EDIT.

package subscriptions

import (
	context "context"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	option "github.com/wavix/wavix-go-sdk/option"
	tendlc "github.com/wavix/wavix-go-sdk/tendlc"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the 10DLC event subscriptions for the authenticated account.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*wavixgosdk.TenDlcEventSubscription, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Registers a callback URL to receive Wavix 10DLC event notifications.
func (c *Client) Create(
	ctx context.Context,
	request *wavixgosdk.TenDlcEventSubscription,
	opts ...option.RequestOption,
) (*tendlc.CreateSubscriptionsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Removes the 10DLC event subscription for the specified event category.
func (c *Client) Delete(
	ctx context.Context,
	request *tendlc.DeleteSubscriptionsRequest,
	opts ...option.RequestOption,
) (*tendlc.DeleteSubscriptionsResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
