// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	aPIKeyCreateRequestFieldLabel         = big.NewInt(1 << 0)
	aPIKeyCreateRequestFieldActive        = big.NewInt(1 << 1)
	aPIKeyCreateRequestFieldRestricted    = big.NewInt(1 << 2)
	aPIKeyCreateRequestFieldPermittedIps  = big.NewInt(1 << 3)
	aPIKeyCreateRequestFieldScopesEnabled = big.NewInt(1 << 4)
	aPIKeyCreateRequestFieldNumbers       = big.NewInt(1 << 5)
	aPIKeyCreateRequestFieldTrunks        = big.NewInt(1 << 6)
	aPIKeyCreateRequestFieldCalls         = big.NewInt(1 << 7)
	aPIKeyCreateRequestFieldMessages      = big.NewInt(1 << 8)
	aPIKeyCreateRequestFieldRecordings    = big.NewInt(1 << 9)
	aPIKeyCreateRequestFieldCampaigns     = big.NewInt(1 << 10)
	aPIKeyCreateRequestFieldTwoFa         = big.NewInt(1 << 11)
	aPIKeyCreateRequestFieldValidator     = big.NewInt(1 << 12)
	aPIKeyCreateRequestFieldWebhooks      = big.NewInt(1 << 13)
	aPIKeyCreateRequestFieldEmbeddable    = big.NewInt(1 << 14)
	aPIKeyCreateRequestFieldBilling       = big.NewInt(1 << 15)
	aPIKeyCreateRequestFieldAccount       = big.NewInt(1 << 16)
	aPIKeyCreateRequestFieldSubaccounts   = big.NewInt(1 << 17)
)

type APIKeyCreateRequest struct {
	// API key label.
	Label string `json:"label" url:"-"`
	// Indicates whether the API key should be activated upon creation.
	Active *bool `json:"active,omitempty" url:"-"`
	// Indicates whether to restrict API key access by IP address. When enabled, only requests from IP addresses listed in `permitted_ips` are allowed.
	Restricted *bool `json:"restricted,omitempty" url:"-"`
	// List of permitted IP addresses for this API key. Each must be a valid IPv4 address. Required when `restricted` is true.
	PermittedIps []string `json:"permitted_ips,omitempty" url:"-"`
	// When `true`, scope fields below are enforced. When `false` (default), the
	// key has full access. Omitted scope fields default to `{ allow: none }`,
	// so with `scopes_enabled: true` and no scopes set the key has no access.
	ScopesEnabled *bool `json:"scopes_enabled,omitempty" url:"-"`
	// View, buy, release, and configure phone numbers, browse inventory, and manage the cart.
	Numbers *APIKeyScopePermission `json:"numbers,omitempty" url:"-"`
	// View, create, update, and delete SIP trunks and their settings.
	Trunks *APIKeyScopePermission `json:"trunks,omitempty" url:"-"`
	// Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests.
	Calls *APIKeyCallsScopePermission `json:"calls,omitempty" url:"-"`
	// Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs.
	Messages *APIKeyScopePermission `json:"messages,omitempty" url:"-"`
	// List, download, and delete call recordings.
	Recordings *APIKeyScopePermission `json:"recordings,omitempty" url:"-"`
	// View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links.
	Campaigns *APIKeyScopePermission `json:"campaigns,omitempty" url:"-"`
	// View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes.
	TwoFa *APIKeyScopePermission `json:"two_fa,omitempty" url:"-"`
	// View number validation results and trigger single or bulk validation or HLR lookup requests.
	Validator *APIKeyScopePermission `json:"validator,omitempty" url:"-"`
	// List, create, and delete webhooks.
	Webhooks *APIKeyScopePermission `json:"webhooks,omitempty" url:"-"`
	// Manage widget tokens, including listing, viewing, creating, updating, and deleting them.
	Embeddable *APIKeyScopePermission `json:"embeddable,omitempty" url:"-"`
	// Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates.
	Billing *APIKeyScopePermission `json:"billing,omitempty" url:"-"`
	// View and update account profile information and timezone.
	Account *APIKeyScopePermission `json:"account,omitempty" url:"-"`
	// Manage subaccounts: list and view them, create, update, and suspend them.
	Subaccounts *APIKeyScopePermission `json:"subaccounts,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *APIKeyCreateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetLabel(label string) {
	a.Label = label
	a.require(aPIKeyCreateRequestFieldLabel)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetActive(active *bool) {
	a.Active = active
	a.require(aPIKeyCreateRequestFieldActive)
}

// SetRestricted sets the Restricted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetRestricted(restricted *bool) {
	a.Restricted = restricted
	a.require(aPIKeyCreateRequestFieldRestricted)
}

// SetPermittedIps sets the PermittedIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetPermittedIps(permittedIps []string) {
	a.PermittedIps = permittedIps
	a.require(aPIKeyCreateRequestFieldPermittedIps)
}

// SetScopesEnabled sets the ScopesEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetScopesEnabled(scopesEnabled *bool) {
	a.ScopesEnabled = scopesEnabled
	a.require(aPIKeyCreateRequestFieldScopesEnabled)
}

// SetNumbers sets the Numbers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetNumbers(numbers *APIKeyScopePermission) {
	a.Numbers = numbers
	a.require(aPIKeyCreateRequestFieldNumbers)
}

// SetTrunks sets the Trunks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetTrunks(trunks *APIKeyScopePermission) {
	a.Trunks = trunks
	a.require(aPIKeyCreateRequestFieldTrunks)
}

// SetCalls sets the Calls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetCalls(calls *APIKeyCallsScopePermission) {
	a.Calls = calls
	a.require(aPIKeyCreateRequestFieldCalls)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetMessages(messages *APIKeyScopePermission) {
	a.Messages = messages
	a.require(aPIKeyCreateRequestFieldMessages)
}

// SetRecordings sets the Recordings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetRecordings(recordings *APIKeyScopePermission) {
	a.Recordings = recordings
	a.require(aPIKeyCreateRequestFieldRecordings)
}

// SetCampaigns sets the Campaigns field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetCampaigns(campaigns *APIKeyScopePermission) {
	a.Campaigns = campaigns
	a.require(aPIKeyCreateRequestFieldCampaigns)
}

// SetTwoFa sets the TwoFa field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetTwoFa(twoFa *APIKeyScopePermission) {
	a.TwoFa = twoFa
	a.require(aPIKeyCreateRequestFieldTwoFa)
}

// SetValidator sets the Validator field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetValidator(validator *APIKeyScopePermission) {
	a.Validator = validator
	a.require(aPIKeyCreateRequestFieldValidator)
}

// SetWebhooks sets the Webhooks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetWebhooks(webhooks *APIKeyScopePermission) {
	a.Webhooks = webhooks
	a.require(aPIKeyCreateRequestFieldWebhooks)
}

// SetEmbeddable sets the Embeddable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetEmbeddable(embeddable *APIKeyScopePermission) {
	a.Embeddable = embeddable
	a.require(aPIKeyCreateRequestFieldEmbeddable)
}

// SetBilling sets the Billing field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetBilling(billing *APIKeyScopePermission) {
	a.Billing = billing
	a.require(aPIKeyCreateRequestFieldBilling)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetAccount(account *APIKeyScopePermission) {
	a.Account = account
	a.require(aPIKeyCreateRequestFieldAccount)
}

// SetSubaccounts sets the Subaccounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetSubaccounts(subaccounts *APIKeyScopePermission) {
	a.Subaccounts = subaccounts
	a.require(aPIKeyCreateRequestFieldSubaccounts)
}

func (a *APIKeyCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = APIKeyCreateRequest(body)
	return nil
}

func (a *APIKeyCreateRequest) MarshalJSON() ([]byte, error) {
	type embed APIKeyCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteAPIKeysRequestFieldID = big.NewInt(1 << 0)
)

type DeleteAPIKeysRequest struct {
	// The unique ID of the API key.
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteAPIKeysRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAPIKeysRequest) SetID(id int) {
	d.ID = id
	d.require(deleteAPIKeysRequestFieldID)
}

var (
	listAPIKeysRequestFieldLabel = big.NewInt(1 << 0)
)

type ListAPIKeysRequest struct {
	// Filters API keys by `label`. Matches partial values.
	Label *string `json:"-" url:"label,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListAPIKeysRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysRequest) SetLabel(label *string) {
	l.Label = label
	l.require(listAPIKeysRequestFieldLabel)
}

// API key details including IP restrictions and scope permissions.
var (
	aPIKeyFieldID            = big.NewInt(1 << 0)
	aPIKeyFieldLabel         = big.NewInt(1 << 1)
	aPIKeyFieldValue         = big.NewInt(1 << 2)
	aPIKeyFieldActive        = big.NewInt(1 << 3)
	aPIKeyFieldRestricted    = big.NewInt(1 << 4)
	aPIKeyFieldPermittedIps  = big.NewInt(1 << 5)
	aPIKeyFieldScopesEnabled = big.NewInt(1 << 6)
	aPIKeyFieldLastUsedAt    = big.NewInt(1 << 7)
	aPIKeyFieldNumbers       = big.NewInt(1 << 8)
	aPIKeyFieldTrunks        = big.NewInt(1 << 9)
	aPIKeyFieldCalls         = big.NewInt(1 << 10)
	aPIKeyFieldMessages      = big.NewInt(1 << 11)
	aPIKeyFieldRecordings    = big.NewInt(1 << 12)
	aPIKeyFieldCampaigns     = big.NewInt(1 << 13)
	aPIKeyFieldTwoFa         = big.NewInt(1 << 14)
	aPIKeyFieldValidator     = big.NewInt(1 << 15)
	aPIKeyFieldWebhooks      = big.NewInt(1 << 16)
	aPIKeyFieldEmbeddable    = big.NewInt(1 << 17)
	aPIKeyFieldBilling       = big.NewInt(1 << 18)
	aPIKeyFieldAccount       = big.NewInt(1 << 19)
	aPIKeyFieldSubaccounts   = big.NewInt(1 << 20)
	aPIKeyFieldCreatedAt     = big.NewInt(1 << 21)
)

type APIKey struct {
	// API key ID.
	ID int `json:"id" url:"id"`
	// API key label.
	Label string `json:"label" url:"label"`
	// API key value.
	Value string `json:"value" url:"value"`
	// Indicates whether the API key is active.
	Active bool `json:"active" url:"active"`
	// Indicates whether IP restrictions are enabled. When enabled,
	//
	//	the API key works only from IP addresses in `permitted_ips`.
	Restricted bool `json:"restricted" url:"restricted"`
	// List of permitted IP addresses. If `restricted` is false,
	//
	//	an empty list means no IP restrictions. If `restricted` is true,
	//	 an empty list prevents all requests.
	PermittedIps []string `json:"permitted_ips" url:"permitted_ips"`
	// When `true`, the key is restricted to the permissions defined in the
	// scope fields below. When `false`, the key has full access.
	ScopesEnabled bool `json:"scopes_enabled" url:"scopes_enabled"`
	// Timestamp of the most recent authenticated request made with this key.
	LastUsedAt *time.Time `json:"last_used_at,omitempty" url:"last_used_at,omitempty"`
	// View, buy, release, and configure phone numbers, browse inventory, and manage the cart.
	Numbers *APIKeyScopePermission `json:"numbers,omitempty" url:"numbers,omitempty"`
	// View, create, update, and delete SIP trunks and their settings.
	Trunks *APIKeyScopePermission `json:"trunks,omitempty" url:"trunks,omitempty"`
	// Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests.
	Calls *APIKeyCallsScopePermission `json:"calls,omitempty" url:"calls,omitempty"`
	// Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs.
	Messages *APIKeyScopePermission `json:"messages,omitempty" url:"messages,omitempty"`
	// List, download, and delete call recordings.
	Recordings *APIKeyScopePermission `json:"recordings,omitempty" url:"recordings,omitempty"`
	// View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links.
	Campaigns *APIKeyScopePermission `json:"campaigns,omitempty" url:"campaigns,omitempty"`
	// View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes.
	TwoFa *APIKeyScopePermission `json:"two_fa,omitempty" url:"two_fa,omitempty"`
	// View number validation results and trigger single or bulk validation or HLR lookup requests.
	Validator *APIKeyScopePermission `json:"validator,omitempty" url:"validator,omitempty"`
	// List, create, and delete webhooks.
	Webhooks *APIKeyScopePermission `json:"webhooks,omitempty" url:"webhooks,omitempty"`
	// Manage widget tokens, including listing, viewing, creating, updating, and deleting them.
	Embeddable *APIKeyScopePermission `json:"embeddable,omitempty" url:"embeddable,omitempty"`
	// Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates.
	Billing *APIKeyScopePermission `json:"billing,omitempty" url:"billing,omitempty"`
	// View and update account profile information and timezone.
	Account *APIKeyScopePermission `json:"account,omitempty" url:"account,omitempty"`
	// Manage subaccounts: list and view them, create, update, and suspend them.
	Subaccounts *APIKeyScopePermission `json:"subaccounts,omitempty" url:"subaccounts,omitempty"`
	// Creation date and time in ISO 8601 format.
	CreatedAt time.Time `json:"created_at" url:"created_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIKey) GetID() int {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *APIKey) GetLabel() string {
	if a == nil {
		return ""
	}
	return a.Label
}

func (a *APIKey) GetValue() string {
	if a == nil {
		return ""
	}
	return a.Value
}

func (a *APIKey) GetActive() bool {
	if a == nil {
		return false
	}
	return a.Active
}

func (a *APIKey) GetRestricted() bool {
	if a == nil {
		return false
	}
	return a.Restricted
}

func (a *APIKey) GetPermittedIps() []string {
	if a == nil {
		return nil
	}
	return a.PermittedIps
}

func (a *APIKey) GetScopesEnabled() bool {
	if a == nil {
		return false
	}
	return a.ScopesEnabled
}

func (a *APIKey) GetLastUsedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsedAt
}

func (a *APIKey) GetNumbers() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Numbers
}

func (a *APIKey) GetTrunks() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Trunks
}

func (a *APIKey) GetCalls() *APIKeyCallsScopePermission {
	if a == nil {
		return nil
	}
	return a.Calls
}

func (a *APIKey) GetMessages() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Messages
}

func (a *APIKey) GetRecordings() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Recordings
}

func (a *APIKey) GetCampaigns() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Campaigns
}

func (a *APIKey) GetTwoFa() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.TwoFa
}

func (a *APIKey) GetValidator() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Validator
}

func (a *APIKey) GetWebhooks() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Webhooks
}

func (a *APIKey) GetEmbeddable() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Embeddable
}

func (a *APIKey) GetBilling() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Billing
}

func (a *APIKey) GetAccount() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Account
}

func (a *APIKey) GetSubaccounts() *APIKeyScopePermission {
	if a == nil {
		return nil
	}
	return a.Subaccounts
}

func (a *APIKey) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *APIKey) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIKey) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetID(id int) {
	a.ID = id
	a.require(aPIKeyFieldID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetLabel(label string) {
	a.Label = label
	a.require(aPIKeyFieldLabel)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetValue(value string) {
	a.Value = value
	a.require(aPIKeyFieldValue)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetActive(active bool) {
	a.Active = active
	a.require(aPIKeyFieldActive)
}

// SetRestricted sets the Restricted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetRestricted(restricted bool) {
	a.Restricted = restricted
	a.require(aPIKeyFieldRestricted)
}

// SetPermittedIps sets the PermittedIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetPermittedIps(permittedIps []string) {
	a.PermittedIps = permittedIps
	a.require(aPIKeyFieldPermittedIps)
}

// SetScopesEnabled sets the ScopesEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetScopesEnabled(scopesEnabled bool) {
	a.ScopesEnabled = scopesEnabled
	a.require(aPIKeyFieldScopesEnabled)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetLastUsedAt(lastUsedAt *time.Time) {
	a.LastUsedAt = lastUsedAt
	a.require(aPIKeyFieldLastUsedAt)
}

// SetNumbers sets the Numbers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetNumbers(numbers *APIKeyScopePermission) {
	a.Numbers = numbers
	a.require(aPIKeyFieldNumbers)
}

// SetTrunks sets the Trunks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetTrunks(trunks *APIKeyScopePermission) {
	a.Trunks = trunks
	a.require(aPIKeyFieldTrunks)
}

// SetCalls sets the Calls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetCalls(calls *APIKeyCallsScopePermission) {
	a.Calls = calls
	a.require(aPIKeyFieldCalls)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetMessages(messages *APIKeyScopePermission) {
	a.Messages = messages
	a.require(aPIKeyFieldMessages)
}

// SetRecordings sets the Recordings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetRecordings(recordings *APIKeyScopePermission) {
	a.Recordings = recordings
	a.require(aPIKeyFieldRecordings)
}

// SetCampaigns sets the Campaigns field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetCampaigns(campaigns *APIKeyScopePermission) {
	a.Campaigns = campaigns
	a.require(aPIKeyFieldCampaigns)
}

// SetTwoFa sets the TwoFa field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetTwoFa(twoFa *APIKeyScopePermission) {
	a.TwoFa = twoFa
	a.require(aPIKeyFieldTwoFa)
}

// SetValidator sets the Validator field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetValidator(validator *APIKeyScopePermission) {
	a.Validator = validator
	a.require(aPIKeyFieldValidator)
}

// SetWebhooks sets the Webhooks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetWebhooks(webhooks *APIKeyScopePermission) {
	a.Webhooks = webhooks
	a.require(aPIKeyFieldWebhooks)
}

// SetEmbeddable sets the Embeddable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetEmbeddable(embeddable *APIKeyScopePermission) {
	a.Embeddable = embeddable
	a.require(aPIKeyFieldEmbeddable)
}

// SetBilling sets the Billing field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetBilling(billing *APIKeyScopePermission) {
	a.Billing = billing
	a.require(aPIKeyFieldBilling)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetAccount(account *APIKeyScopePermission) {
	a.Account = account
	a.require(aPIKeyFieldAccount)
}

// SetSubaccounts sets the Subaccounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetSubaccounts(subaccounts *APIKeyScopePermission) {
	a.Subaccounts = subaccounts
	a.require(aPIKeyFieldSubaccounts)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetCreatedAt(createdAt time.Time) {
	a.CreatedAt = createdAt
	a.require(aPIKeyFieldCreatedAt)
}

func (a *APIKey) UnmarshalJSON(data []byte) error {
	type embed APIKey
	var unmarshaler = struct {
		embed
		LastUsedAt *internal.DateTime `json:"last_used_at,omitempty"`
		CreatedAt  *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = APIKey(unmarshaler.embed)
	a.LastUsedAt = unmarshaler.LastUsedAt.TimePtr()
	a.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIKey) MarshalJSON() ([]byte, error) {
	type embed APIKey
	var marshaler = struct {
		embed
		LastUsedAt *internal.DateTime `json:"last_used_at,omitempty"`
		CreatedAt  *internal.DateTime `json:"created_at"`
	}{
		embed:      embed(*a),
		LastUsedAt: internal.NewOptionalDateTime(a.LastUsedAt),
		CreatedAt:  internal.NewDateTime(a.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIKey) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Permission level for the `calls` scope group.
var (
	aPIKeyCallsScopePermissionFieldAllow = big.NewInt(1 << 0)
)

type APIKeyCallsScopePermission struct {
	// Permission level:
	// - `none`: no access
	// - `read`: GET requests, `POST /v1/cdrs`
	// - `write`: all methods (includes read)
	Allow *APIKeyCallsScopePermissionAllow `json:"allow,omitempty" url:"allow,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIKeyCallsScopePermission) GetAllow() *APIKeyCallsScopePermissionAllow {
	if a == nil {
		return nil
	}
	return a.Allow
}

func (a *APIKeyCallsScopePermission) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIKeyCallsScopePermission) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAllow sets the Allow field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCallsScopePermission) SetAllow(allow *APIKeyCallsScopePermissionAllow) {
	a.Allow = allow
	a.require(aPIKeyCallsScopePermissionFieldAllow)
}

func (a *APIKeyCallsScopePermission) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyCallsScopePermission
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIKeyCallsScopePermission(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIKeyCallsScopePermission) MarshalJSON() ([]byte, error) {
	type embed APIKeyCallsScopePermission
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIKeyCallsScopePermission) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Permission level:
// - `none`: no access
// - `read`: GET requests, `POST /v1/cdrs`
// - `write`: all methods (includes read)
type APIKeyCallsScopePermissionAllow string

const (
	APIKeyCallsScopePermissionAllowNone  APIKeyCallsScopePermissionAllow = "none"
	APIKeyCallsScopePermissionAllowRead  APIKeyCallsScopePermissionAllow = "read"
	APIKeyCallsScopePermissionAllowWrite APIKeyCallsScopePermissionAllow = "write"
)

func NewAPIKeyCallsScopePermissionAllowFromString(s string) (APIKeyCallsScopePermissionAllow, error) {
	switch s {
	case "none":
		return APIKeyCallsScopePermissionAllowNone, nil
	case "read":
		return APIKeyCallsScopePermissionAllowRead, nil
	case "write":
		return APIKeyCallsScopePermissionAllowWrite, nil
	}
	var t APIKeyCallsScopePermissionAllow
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a APIKeyCallsScopePermissionAllow) Ptr() *APIKeyCallsScopePermissionAllow {
	return &a
}

// Permission level for an API key scope group.
var (
	aPIKeyScopePermissionFieldAllow = big.NewInt(1 << 0)
)

type APIKeyScopePermission struct {
	// Permission level:
	// - `none`: no access
	// - `read`: GET only
	// - `write`: all methods (includes read)
	Allow *APIKeyScopePermissionAllow `json:"allow,omitempty" url:"allow,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIKeyScopePermission) GetAllow() *APIKeyScopePermissionAllow {
	if a == nil {
		return nil
	}
	return a.Allow
}

func (a *APIKeyScopePermission) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIKeyScopePermission) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAllow sets the Allow field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyScopePermission) SetAllow(allow *APIKeyScopePermissionAllow) {
	a.Allow = allow
	a.require(aPIKeyScopePermissionFieldAllow)
}

func (a *APIKeyScopePermission) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyScopePermission
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIKeyScopePermission(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIKeyScopePermission) MarshalJSON() ([]byte, error) {
	type embed APIKeyScopePermission
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIKeyScopePermission) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Permission level:
// - `none`: no access
// - `read`: GET only
// - `write`: all methods (includes read)
type APIKeyScopePermissionAllow string

const (
	APIKeyScopePermissionAllowNone  APIKeyScopePermissionAllow = "none"
	APIKeyScopePermissionAllowRead  APIKeyScopePermissionAllow = "read"
	APIKeyScopePermissionAllowWrite APIKeyScopePermissionAllow = "write"
)

func NewAPIKeyScopePermissionAllowFromString(s string) (APIKeyScopePermissionAllow, error) {
	switch s {
	case "none":
		return APIKeyScopePermissionAllowNone, nil
	case "read":
		return APIKeyScopePermissionAllowRead, nil
	case "write":
		return APIKeyScopePermissionAllowWrite, nil
	}
	var t APIKeyScopePermissionAllow
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a APIKeyScopePermissionAllow) Ptr() *APIKeyScopePermissionAllow {
	return &a
}

var (
	aPIKeyUpdateRequestFieldID            = big.NewInt(1 << 0)
	aPIKeyUpdateRequestFieldActive        = big.NewInt(1 << 1)
	aPIKeyUpdateRequestFieldRestricted    = big.NewInt(1 << 2)
	aPIKeyUpdateRequestFieldScopesEnabled = big.NewInt(1 << 3)
	aPIKeyUpdateRequestFieldPermittedIps  = big.NewInt(1 << 4)
	aPIKeyUpdateRequestFieldLabel         = big.NewInt(1 << 5)
	aPIKeyUpdateRequestFieldNumbers       = big.NewInt(1 << 6)
	aPIKeyUpdateRequestFieldTrunks        = big.NewInt(1 << 7)
	aPIKeyUpdateRequestFieldCalls         = big.NewInt(1 << 8)
	aPIKeyUpdateRequestFieldMessages      = big.NewInt(1 << 9)
	aPIKeyUpdateRequestFieldRecordings    = big.NewInt(1 << 10)
	aPIKeyUpdateRequestFieldCampaigns     = big.NewInt(1 << 11)
	aPIKeyUpdateRequestFieldTwoFa         = big.NewInt(1 << 12)
	aPIKeyUpdateRequestFieldValidator     = big.NewInt(1 << 13)
	aPIKeyUpdateRequestFieldWebhooks      = big.NewInt(1 << 14)
	aPIKeyUpdateRequestFieldEmbeddable    = big.NewInt(1 << 15)
	aPIKeyUpdateRequestFieldBilling       = big.NewInt(1 << 16)
	aPIKeyUpdateRequestFieldAccount       = big.NewInt(1 << 17)
	aPIKeyUpdateRequestFieldSubaccounts   = big.NewInt(1 << 18)
)

type APIKeyUpdateRequest struct {
	// The unique ID of the API key.
	ID int `json:"-" url:"-"`
	// Indicates whether the API key is active.
	Active *bool `json:"active,omitempty" url:"-"`
	// Indicates whether the API key is restricted to the listed permitted IPs.
	Restricted *bool `json:"restricted,omitempty" url:"-"`
	// Indicates whether per-resource scope permissions are enforced for the API key.
	ScopesEnabled *bool `json:"scopes_enabled,omitempty" url:"-"`
	// IP addresses allowed to use the API key when restriction is enabled.
	PermittedIps []string `json:"permitted_ips,omitempty" url:"-"`
	// Human-readable label for the API key.
	Label *string `json:"label,omitempty" url:"-"`
	// View, buy, release, and configure phone numbers, browse inventory, and manage the cart.
	Numbers *APIKeyScopePermission `json:"numbers,omitempty" url:"-"`
	// View, create, update, and delete SIP trunks and their settings.
	Trunks *APIKeyScopePermission `json:"trunks,omitempty" url:"-"`
	// Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests.
	Calls *APIKeyCallsScopePermission `json:"calls,omitempty" url:"-"`
	// Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs.
	Messages *APIKeyScopePermission `json:"messages,omitempty" url:"-"`
	// List, download, and delete call recordings.
	Recordings *APIKeyScopePermission `json:"recordings,omitempty" url:"-"`
	// View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links.
	Campaigns *APIKeyScopePermission `json:"campaigns,omitempty" url:"-"`
	// View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes.
	TwoFa *APIKeyScopePermission `json:"two_fa,omitempty" url:"-"`
	// View number validation results and trigger single or bulk validation or HLR lookup requests.
	Validator *APIKeyScopePermission `json:"validator,omitempty" url:"-"`
	// List, create, and delete webhooks.
	Webhooks *APIKeyScopePermission `json:"webhooks,omitempty" url:"-"`
	// Manage widget tokens, including listing, viewing, creating, updating, and deleting them.
	Embeddable *APIKeyScopePermission `json:"embeddable,omitempty" url:"-"`
	// Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates.
	Billing *APIKeyScopePermission `json:"billing,omitempty" url:"-"`
	// View and update account profile information and timezone.
	Account *APIKeyScopePermission `json:"account,omitempty" url:"-"`
	// Manage subaccounts: list and view them, create, update, and suspend them.
	Subaccounts *APIKeyScopePermission `json:"subaccounts,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *APIKeyUpdateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetID(id int) {
	a.ID = id
	a.require(aPIKeyUpdateRequestFieldID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetActive(active *bool) {
	a.Active = active
	a.require(aPIKeyUpdateRequestFieldActive)
}

// SetRestricted sets the Restricted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetRestricted(restricted *bool) {
	a.Restricted = restricted
	a.require(aPIKeyUpdateRequestFieldRestricted)
}

// SetScopesEnabled sets the ScopesEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetScopesEnabled(scopesEnabled *bool) {
	a.ScopesEnabled = scopesEnabled
	a.require(aPIKeyUpdateRequestFieldScopesEnabled)
}

// SetPermittedIps sets the PermittedIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetPermittedIps(permittedIps []string) {
	a.PermittedIps = permittedIps
	a.require(aPIKeyUpdateRequestFieldPermittedIps)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetLabel(label *string) {
	a.Label = label
	a.require(aPIKeyUpdateRequestFieldLabel)
}

// SetNumbers sets the Numbers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetNumbers(numbers *APIKeyScopePermission) {
	a.Numbers = numbers
	a.require(aPIKeyUpdateRequestFieldNumbers)
}

// SetTrunks sets the Trunks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetTrunks(trunks *APIKeyScopePermission) {
	a.Trunks = trunks
	a.require(aPIKeyUpdateRequestFieldTrunks)
}

// SetCalls sets the Calls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetCalls(calls *APIKeyCallsScopePermission) {
	a.Calls = calls
	a.require(aPIKeyUpdateRequestFieldCalls)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetMessages(messages *APIKeyScopePermission) {
	a.Messages = messages
	a.require(aPIKeyUpdateRequestFieldMessages)
}

// SetRecordings sets the Recordings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetRecordings(recordings *APIKeyScopePermission) {
	a.Recordings = recordings
	a.require(aPIKeyUpdateRequestFieldRecordings)
}

// SetCampaigns sets the Campaigns field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetCampaigns(campaigns *APIKeyScopePermission) {
	a.Campaigns = campaigns
	a.require(aPIKeyUpdateRequestFieldCampaigns)
}

// SetTwoFa sets the TwoFa field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetTwoFa(twoFa *APIKeyScopePermission) {
	a.TwoFa = twoFa
	a.require(aPIKeyUpdateRequestFieldTwoFa)
}

// SetValidator sets the Validator field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetValidator(validator *APIKeyScopePermission) {
	a.Validator = validator
	a.require(aPIKeyUpdateRequestFieldValidator)
}

// SetWebhooks sets the Webhooks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetWebhooks(webhooks *APIKeyScopePermission) {
	a.Webhooks = webhooks
	a.require(aPIKeyUpdateRequestFieldWebhooks)
}

// SetEmbeddable sets the Embeddable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetEmbeddable(embeddable *APIKeyScopePermission) {
	a.Embeddable = embeddable
	a.require(aPIKeyUpdateRequestFieldEmbeddable)
}

// SetBilling sets the Billing field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetBilling(billing *APIKeyScopePermission) {
	a.Billing = billing
	a.require(aPIKeyUpdateRequestFieldBilling)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetAccount(account *APIKeyScopePermission) {
	a.Account = account
	a.require(aPIKeyUpdateRequestFieldAccount)
}

// SetSubaccounts sets the Subaccounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyUpdateRequest) SetSubaccounts(subaccounts *APIKeyScopePermission) {
	a.Subaccounts = subaccounts
	a.require(aPIKeyUpdateRequestFieldSubaccounts)
}

func (a *APIKeyUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = APIKeyUpdateRequest(body)
	return nil
}

func (a *APIKeyUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed APIKeyUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}
