// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	getCdrsRequestFieldCallID            = big.NewInt(1 << 0)
	getCdrsRequestFieldShowTranscription = big.NewInt(1 << 1)
)

type GetCdrsRequest struct {
	// The unique ID of the call.
	CallID string `json:"-" url:"-"`
	// When `true`, includes the call transcription in the response.
	ShowTranscription *bool `json:"-" url:"show_transcription,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCdrsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCdrsRequest) SetCallID(callID string) {
	g.CallID = callID
	g.require(getCdrsRequestFieldCallID)
}

// SetShowTranscription sets the ShowTranscription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCdrsRequest) SetShowTranscription(showTranscription *bool) {
	g.ShowTranscription = showTranscription
	g.require(getCdrsRequestFieldShowTranscription)
}

var (
	listCdrsRequestFieldFrom        = big.NewInt(1 << 0)
	listCdrsRequestFieldTo          = big.NewInt(1 << 1)
	listCdrsRequestFieldType        = big.NewInt(1 << 2)
	listCdrsRequestFieldDisposition = big.NewInt(1 << 3)
	listCdrsRequestFieldFromSearch  = big.NewInt(1 << 4)
	listCdrsRequestFieldToSearch    = big.NewInt(1 << 5)
	listCdrsRequestFieldSipTrunk    = big.NewInt(1 << 6)
	listCdrsRequestFieldUUID        = big.NewInt(1 << 7)
	listCdrsRequestFieldPage        = big.NewInt(1 << 8)
	listCdrsRequestFieldPerPage     = big.NewInt(1 << 9)
)

type ListCdrsRequest struct {
	// Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	From time.Time `json:"-" url:"from" format:"date"`
	// End of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	To time.Time `json:"-" url:"to" format:"date"`
	// Filters CDRs by call direction. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account).
	Type string `json:"-" url:"type"`
	// Filters CDRs by call disposition. One of `answered` (the called party answered), `busy` (the called party was busy), `rejected` (the call was declined), `failed` (the call could not be routed), or `all` (no disposition filter).
	Disposition *CallDisposition `json:"-" url:"disposition,omitempty"`
	// Filters CDRs by originating phone number. Accepts a full or partial number.
	FromSearch *string `json:"-" url:"from_search,omitempty"`
	// Filters CDRs by destination phone number. Accepts a full or partial number.
	ToSearch *string `json:"-" url:"to_search,omitempty"`
	// Filters outbound CDRs by SIP trunk login. Ignored for inbound calls.
	SipTrunk *string `json:"-" url:"sip_trunk,omitempty"`
	// Filters CDRs by the unique call ID.
	UUID *string `json:"-" url:"uuid,omitempty"`
	// Page number to retrieve. Default `1`.
	Page *int `json:"-" url:"page,omitempty"`
	// Number of records to return per page. Default `25`.
	PerPage *int `json:"-" url:"per_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCdrsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetFrom(from time.Time) {
	l.From = from
	l.require(listCdrsRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetTo(to time.Time) {
	l.To = to
	l.require(listCdrsRequestFieldTo)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetType(type_ string) {
	l.Type = type_
	l.require(listCdrsRequestFieldType)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetDisposition(disposition *CallDisposition) {
	l.Disposition = disposition
	l.require(listCdrsRequestFieldDisposition)
}

// SetFromSearch sets the FromSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetFromSearch(fromSearch *string) {
	l.FromSearch = fromSearch
	l.require(listCdrsRequestFieldFromSearch)
}

// SetToSearch sets the ToSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetToSearch(toSearch *string) {
	l.ToSearch = toSearch
	l.require(listCdrsRequestFieldToSearch)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetSipTrunk(sipTrunk *string) {
	l.SipTrunk = sipTrunk
	l.require(listCdrsRequestFieldSipTrunk)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetUUID(uuid *string) {
	l.UUID = uuid
	l.require(listCdrsRequestFieldUUID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listCdrsRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCdrsRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listCdrsRequestFieldPerPage)
}

var (
	listAllCdrsRequestFieldFrom        = big.NewInt(1 << 0)
	listAllCdrsRequestFieldTo          = big.NewInt(1 << 1)
	listAllCdrsRequestFieldType        = big.NewInt(1 << 2)
	listAllCdrsRequestFieldDisposition = big.NewInt(1 << 3)
	listAllCdrsRequestFieldFromSearch  = big.NewInt(1 << 4)
	listAllCdrsRequestFieldToSearch    = big.NewInt(1 << 5)
	listAllCdrsRequestFieldSipTrunk    = big.NewInt(1 << 6)
	listAllCdrsRequestFieldUUID        = big.NewInt(1 << 7)
	listAllCdrsRequestFieldPage        = big.NewInt(1 << 8)
	listAllCdrsRequestFieldPerPage     = big.NewInt(1 << 9)
)

type ListAllCdrsRequest struct {
	// Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	From time.Time `json:"-" url:"from" format:"date"`
	// End of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	To time.Time `json:"-" url:"to" format:"date"`
	// Filters CDRs by call direction. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account).
	Type string `json:"-" url:"type"`
	// Filters CDRs by call disposition. One of `answered` (the called party answered), `busy` (the called party was busy), `rejected` (the call was declined), `failed` (the call could not be routed), or `all` (no disposition filter).
	Disposition *CallDisposition `json:"-" url:"disposition,omitempty"`
	// Filters CDRs by originating phone number. Accepts a full or partial number.
	FromSearch *string `json:"-" url:"from_search,omitempty"`
	// Filters CDRs by destination phone number. Accepts a full or partial number.
	ToSearch *string `json:"-" url:"to_search,omitempty"`
	// Filters outbound CDRs by SIP trunk login. Ignored for inbound calls.
	SipTrunk *string `json:"-" url:"sip_trunk,omitempty"`
	// Filters CDRs by the unique call ID.
	UUID *string `json:"-" url:"uuid,omitempty"`
	// Page number to retrieve. Default `1`.
	Page *int `json:"-" url:"page,omitempty"`
	// Number of records to return per page. Default `25`.
	PerPage *int `json:"-" url:"per_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListAllCdrsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetFrom(from time.Time) {
	l.From = from
	l.require(listAllCdrsRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetTo(to time.Time) {
	l.To = to
	l.require(listAllCdrsRequestFieldTo)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetType(type_ string) {
	l.Type = type_
	l.require(listAllCdrsRequestFieldType)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetDisposition(disposition *CallDisposition) {
	l.Disposition = disposition
	l.require(listAllCdrsRequestFieldDisposition)
}

// SetFromSearch sets the FromSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetFromSearch(fromSearch *string) {
	l.FromSearch = fromSearch
	l.require(listAllCdrsRequestFieldFromSearch)
}

// SetToSearch sets the ToSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetToSearch(toSearch *string) {
	l.ToSearch = toSearch
	l.require(listAllCdrsRequestFieldToSearch)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetSipTrunk(sipTrunk *string) {
	l.SipTrunk = sipTrunk
	l.require(listAllCdrsRequestFieldSipTrunk)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetUUID(uuid *string) {
	l.UUID = uuid
	l.require(listAllCdrsRequestFieldUUID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listAllCdrsRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAllCdrsRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listAllCdrsRequestFieldPerPage)
}

var (
	cdrRetranscriptionRequestFieldCallID     = big.NewInt(1 << 0)
	cdrRetranscriptionRequestFieldLanguage   = big.NewInt(1 << 1)
	cdrRetranscriptionRequestFieldWebhookURL = big.NewInt(1 << 2)
)

type CdrRetranscriptionRequest struct {
	// The unique ID of the call.
	CallID   string                 `json:"-" url:"-"`
	Language *TranscriptionLanguage `json:"language,omitempty" url:"-"`
	// Webhook URL to receive status updates.
	WebhookURL *string `json:"webhook_url,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CdrRetranscriptionRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrRetranscriptionRequest) SetCallID(callID string) {
	c.CallID = callID
	c.require(cdrRetranscriptionRequestFieldCallID)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrRetranscriptionRequest) SetLanguage(language *TranscriptionLanguage) {
	c.Language = language
	c.require(cdrRetranscriptionRequestFieldLanguage)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrRetranscriptionRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cdrRetranscriptionRequestFieldWebhookURL)
}

func (c *CdrRetranscriptionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CdrRetranscriptionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CdrRetranscriptionRequest(body)
	return nil
}

func (c *CdrRetranscriptionRequest) MarshalJSON() ([]byte, error) {
	type embed CdrRetranscriptionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	cdrSearchRequestFieldType          = big.NewInt(1 << 0)
	cdrSearchRequestFieldFrom          = big.NewInt(1 << 1)
	cdrSearchRequestFieldTo            = big.NewInt(1 << 2)
	cdrSearchRequestFieldFromSearch    = big.NewInt(1 << 3)
	cdrSearchRequestFieldToSearch      = big.NewInt(1 << 4)
	cdrSearchRequestFieldSipTrunk      = big.NewInt(1 << 5)
	cdrSearchRequestFieldMinDuration   = big.NewInt(1 << 6)
	cdrSearchRequestFieldTranscription = big.NewInt(1 << 7)
	cdrSearchRequestFieldUUID          = big.NewInt(1 << 8)
	cdrSearchRequestFieldDisposition   = big.NewInt(1 << 9)
	cdrSearchRequestFieldPage          = big.NewInt(1 << 10)
	cdrSearchRequestFieldPerPage       = big.NewInt(1 << 11)
)

type CdrSearchRequest struct {
	// Filters by call type. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account).
	Type CdrSearchRequestType `json:"type" url:"-"`
	// Start date for call search in `YYYY-MM-DD` format.
	From time.Time `json:"from" url:"-" format:"date"`
	// End date for call search in `YYYY-MM-DD` format.
	To time.Time `json:"to" url:"-" format:"date"`
	// Originating phone number to filter results. Accepts full or partial number.
	FromSearch *string `json:"from_search,omitempty" url:"-"`
	// Destination phone number to filter results. Accepts full or partial number.
	ToSearch *string `json:"to_search,omitempty" url:"-"`
	// SIP trunk login to filter outbound calls. Ignored for inbound calls.
	SipTrunk *string `json:"sip_trunk,omitempty" url:"-"`
	// Minimum call duration in seconds.
	MinDuration   *int                 `json:"min_duration,omitempty" url:"-"`
	Transcription *TranscriptionFilter `json:"transcription,omitempty" url:"-"`
	// Call ID.
	UUID *string `json:"uuid,omitempty" url:"-"`
	// Call disposition to filter results.  If omitted, returns only answered
	//
	//	calls. Allowed values: `answered`, `busy`, `rejected`,
	//	 `failed`, `all`. Use `all` to return calls
	//	  regardless of their disposition.
	Disposition *CdrSearchRequestDisposition `json:"disposition,omitempty" url:"-"`
	// Page number to retrieve.
	Page int `json:"page" url:"-"`
	// Number of records per page.
	PerPage int `json:"per_page" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CdrSearchRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetType(type_ CdrSearchRequestType) {
	c.Type = type_
	c.require(cdrSearchRequestFieldType)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetFrom(from time.Time) {
	c.From = from
	c.require(cdrSearchRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetTo(to time.Time) {
	c.To = to
	c.require(cdrSearchRequestFieldTo)
}

// SetFromSearch sets the FromSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetFromSearch(fromSearch *string) {
	c.FromSearch = fromSearch
	c.require(cdrSearchRequestFieldFromSearch)
}

// SetToSearch sets the ToSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetToSearch(toSearch *string) {
	c.ToSearch = toSearch
	c.require(cdrSearchRequestFieldToSearch)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetSipTrunk(sipTrunk *string) {
	c.SipTrunk = sipTrunk
	c.require(cdrSearchRequestFieldSipTrunk)
}

// SetMinDuration sets the MinDuration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetMinDuration(minDuration *int) {
	c.MinDuration = minDuration
	c.require(cdrSearchRequestFieldMinDuration)
}

// SetTranscription sets the Transcription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetTranscription(transcription *TranscriptionFilter) {
	c.Transcription = transcription
	c.require(cdrSearchRequestFieldTranscription)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetUUID(uuid *string) {
	c.UUID = uuid
	c.require(cdrSearchRequestFieldUUID)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetDisposition(disposition *CdrSearchRequestDisposition) {
	c.Disposition = disposition
	c.require(cdrSearchRequestFieldDisposition)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetPage(page int) {
	c.Page = page
	c.require(cdrSearchRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrSearchRequest) SetPerPage(perPage int) {
	c.PerPage = perPage
	c.require(cdrSearchRequestFieldPerPage)
}

func (c *CdrSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CdrSearchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CdrSearchRequest(body)
	return nil
}

func (c *CdrSearchRequest) MarshalJSON() ([]byte, error) {
	type embed CdrSearchRequest
	var marshaler = struct {
		embed
		From *internal.Date `json:"from"`
		To   *internal.Date `json:"to"`
	}{
		embed: embed(*c),
		From:  internal.NewDate(c.From),
		To:    internal.NewDate(c.To),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	transcriptionsCdrsRequestFieldCallID = big.NewInt(1 << 0)
)

type TranscriptionsCdrsRequest struct {
	// The unique ID of the call.
	CallID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TranscriptionsCdrsRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionsCdrsRequest) SetCallID(callID string) {
	t.CallID = callID
	t.require(transcriptionsCdrsRequestFieldCallID)
}

// Final disposition of the call. One of `answered` (the called party answered), `noanswer` (no answer within the ring timeout), `busy` (the called party was busy), `failed` (the call could not be routed), or `all` (matches any disposition when used as a filter).
type CallDisposition string

const (
	CallDispositionAnswered CallDisposition = "answered"
	CallDispositionNoanswer CallDisposition = "noanswer"
	CallDispositionBusy     CallDisposition = "busy"
	CallDispositionFailed   CallDisposition = "failed"
	CallDispositionAll      CallDisposition = "all"
)

func NewCallDispositionFromString(s string) (CallDisposition, error) {
	switch s {
	case "answered":
		return CallDispositionAnswered, nil
	case "noanswer":
		return CallDispositionNoanswer, nil
	case "busy":
		return CallDispositionBusy, nil
	case "failed":
		return CallDispositionFailed, nil
	case "all":
		return CallDispositionAll, nil
	}
	var t CallDisposition
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CallDisposition) Ptr() *CallDisposition {
	return &c
}

// Call detail record (CDR) for an individual call.
var (
	cdrFieldDate         = big.NewInt(1 << 0)
	cdrFieldFrom         = big.NewInt(1 << 1)
	cdrFieldTo           = big.NewInt(1 << 2)
	cdrFieldDisposition  = big.NewInt(1 << 3)
	cdrFieldDuration     = big.NewInt(1 << 4)
	cdrFieldDestination  = big.NewInt(1 << 5)
	cdrFieldPerMinute    = big.NewInt(1 << 6)
	cdrFieldCharge       = big.NewInt(1 << 7)
	cdrFieldSipTrunk     = big.NewInt(1 << 8)
	cdrFieldForwardFee   = big.NewInt(1 << 9)
	cdrFieldUUID         = big.NewInt(1 << 10)
	cdrFieldCallID       = big.NewInt(1 << 11)
	cdrFieldParentUUID   = big.NewInt(1 << 12)
	cdrFieldParentCallID = big.NewInt(1 << 13)
	cdrFieldAnsweredBy   = big.NewInt(1 << 14)
)

type Cdr struct {
	// Date and time of the call in ISO 8601 format.
	Date time.Time `json:"date" url:"date"`
	// Originating phone number (ANI).
	From string `json:"from" url:"from"`
	// Destination phone number (DNIS).
	To          string          `json:"to" url:"to"`
	Disposition CallDisposition `json:"disposition" url:"disposition"`
	// Call duration in seconds.
	Duration int `json:"duration" url:"duration"`
	// Destination of the call. For outbound calls,
	//
	//	contains the country name and, optionally, a mobile carrier
	//	 or city name. For inbound calls, includes the SIP trunk name,
	//	  SIP URI, or PSTN number the call is forwarded to.
	Destination string `json:"destination" url:"destination"`
	// Price per minute in USD.
	PerMinute string `json:"per_minute" url:"per_minute"`
	// Total charge for the call in USD.
	Charge string `json:"charge" url:"charge"`
	// System-generated SIP trunk login. For outbound calls only.
	SipTrunk *string `json:"sip_trunk,omitempty" url:"sip_trunk,omitempty"`
	// PSTN forwarding price in USD. For inbound calls only when forwarded to PSTN.
	ForwardFee *string `json:"forward_fee,omitempty" url:"forward_fee,omitempty"`
	// Call ID. Deprecated — use `call_id` instead.
	UUID string `json:"uuid" url:"uuid"`
	// Call ID. Alias of `uuid`.
	CallID string `json:"call_id" url:"call_id"`
	// Parent call ID. Deprecated — use `parent_call_id` instead.
	ParentUUID *string `json:"parent_uuid,omitempty" url:"parent_uuid,omitempty"`
	// Parent call ID. Alias of `parent_uuid`.
	ParentCallID *string `json:"parent_call_id,omitempty" url:"parent_call_id,omitempty"`
	// Who answered the call. Possible values are `human`, `machine`.
	AnsweredBy *string `json:"answered_by,omitempty" url:"answered_by,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Cdr) GetDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Date
}

func (c *Cdr) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *Cdr) GetTo() string {
	if c == nil {
		return ""
	}
	return c.To
}

func (c *Cdr) GetDisposition() CallDisposition {
	if c == nil {
		return ""
	}
	return c.Disposition
}

func (c *Cdr) GetDuration() int {
	if c == nil {
		return 0
	}
	return c.Duration
}

func (c *Cdr) GetDestination() string {
	if c == nil {
		return ""
	}
	return c.Destination
}

func (c *Cdr) GetPerMinute() string {
	if c == nil {
		return ""
	}
	return c.PerMinute
}

func (c *Cdr) GetCharge() string {
	if c == nil {
		return ""
	}
	return c.Charge
}

func (c *Cdr) GetSipTrunk() *string {
	if c == nil {
		return nil
	}
	return c.SipTrunk
}

func (c *Cdr) GetForwardFee() *string {
	if c == nil {
		return nil
	}
	return c.ForwardFee
}

func (c *Cdr) GetUUID() string {
	if c == nil {
		return ""
	}
	return c.UUID
}

func (c *Cdr) GetCallID() string {
	if c == nil {
		return ""
	}
	return c.CallID
}

func (c *Cdr) GetParentUUID() *string {
	if c == nil {
		return nil
	}
	return c.ParentUUID
}

func (c *Cdr) GetParentCallID() *string {
	if c == nil {
		return nil
	}
	return c.ParentCallID
}

func (c *Cdr) GetAnsweredBy() *string {
	if c == nil {
		return nil
	}
	return c.AnsweredBy
}

func (c *Cdr) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Cdr) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetDate(date time.Time) {
	c.Date = date
	c.require(cdrFieldDate)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetFrom(from string) {
	c.From = from
	c.require(cdrFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetTo(to string) {
	c.To = to
	c.require(cdrFieldTo)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetDisposition(disposition CallDisposition) {
	c.Disposition = disposition
	c.require(cdrFieldDisposition)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetDuration(duration int) {
	c.Duration = duration
	c.require(cdrFieldDuration)
}

// SetDestination sets the Destination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetDestination(destination string) {
	c.Destination = destination
	c.require(cdrFieldDestination)
}

// SetPerMinute sets the PerMinute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetPerMinute(perMinute string) {
	c.PerMinute = perMinute
	c.require(cdrFieldPerMinute)
}

// SetCharge sets the Charge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetCharge(charge string) {
	c.Charge = charge
	c.require(cdrFieldCharge)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetSipTrunk(sipTrunk *string) {
	c.SipTrunk = sipTrunk
	c.require(cdrFieldSipTrunk)
}

// SetForwardFee sets the ForwardFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetForwardFee(forwardFee *string) {
	c.ForwardFee = forwardFee
	c.require(cdrFieldForwardFee)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetUUID(uuid string) {
	c.UUID = uuid
	c.require(cdrFieldUUID)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetCallID(callID string) {
	c.CallID = callID
	c.require(cdrFieldCallID)
}

// SetParentUUID sets the ParentUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetParentUUID(parentUUID *string) {
	c.ParentUUID = parentUUID
	c.require(cdrFieldParentUUID)
}

// SetParentCallID sets the ParentCallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetParentCallID(parentCallID *string) {
	c.ParentCallID = parentCallID
	c.require(cdrFieldParentCallID)
}

// SetAnsweredBy sets the AnsweredBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cdr) SetAnsweredBy(answeredBy *string) {
	c.AnsweredBy = answeredBy
	c.require(cdrFieldAnsweredBy)
}

func (c *Cdr) UnmarshalJSON(data []byte) error {
	type embed Cdr
	var unmarshaler = struct {
		embed
		Date *internal.DateTime `json:"date"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = Cdr(unmarshaler.embed)
	c.Date = unmarshaler.Date.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Cdr) MarshalJSON() ([]byte, error) {
	type embed Cdr
	var marshaler = struct {
		embed
		Date *internal.DateTime `json:"date"`
	}{
		embed: embed(*c),
		Date:  internal.NewDateTime(c.Date),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Cdr) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cdrListResponseFieldItems      = big.NewInt(1 << 0)
	cdrListResponseFieldPagination = big.NewInt(1 << 1)
)

type CdrListResponse struct {
	// List of CDRs
	Items      []*Cdr      `json:"items" url:"items"`
	Pagination *Pagination `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CdrListResponse) GetItems() []*Cdr {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CdrListResponse) GetPagination() *Pagination {
	if c == nil {
		return nil
	}
	return c.Pagination
}

func (c *CdrListResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CdrListResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrListResponse) SetItems(items []*Cdr) {
	c.Items = items
	c.require(cdrListResponseFieldItems)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrListResponse) SetPagination(pagination *Pagination) {
	c.Pagination = pagination
	c.require(cdrListResponseFieldPagination)
}

func (c *CdrListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CdrListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CdrListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CdrListResponse) MarshalJSON() ([]byte, error) {
	type embed CdrListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CdrListResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cdrResponseFieldDate          = big.NewInt(1 << 0)
	cdrResponseFieldFrom          = big.NewInt(1 << 1)
	cdrResponseFieldTo            = big.NewInt(1 << 2)
	cdrResponseFieldDisposition   = big.NewInt(1 << 3)
	cdrResponseFieldDuration      = big.NewInt(1 << 4)
	cdrResponseFieldDestination   = big.NewInt(1 << 5)
	cdrResponseFieldPerMinute     = big.NewInt(1 << 6)
	cdrResponseFieldRecordingURL  = big.NewInt(1 << 7)
	cdrResponseFieldCharge        = big.NewInt(1 << 8)
	cdrResponseFieldSipTrunk      = big.NewInt(1 << 9)
	cdrResponseFieldForwardFee    = big.NewInt(1 << 10)
	cdrResponseFieldUUID          = big.NewInt(1 << 11)
	cdrResponseFieldCallID        = big.NewInt(1 << 12)
	cdrResponseFieldParentUUID    = big.NewInt(1 << 13)
	cdrResponseFieldParentCallID  = big.NewInt(1 << 14)
	cdrResponseFieldAnsweredBy    = big.NewInt(1 << 15)
	cdrResponseFieldTranscription = big.NewInt(1 << 16)
)

type CdrResponse struct {
	// Call date and time in ISO 8601 format.
	Date *time.Time `json:"date,omitempty" url:"date,omitempty"`
	// Caller ID (ANI).
	From string `json:"from" url:"from"`
	// Dialed number (DNIS).
	To          string          `json:"to" url:"to"`
	Disposition CallDisposition `json:"disposition" url:"disposition"`
	// Call duration in seconds.
	Duration int `json:"duration" url:"duration"`
	// Destination of the call. For outbound calls,
	//
	//	contains the country name and, optionally, a mobile carrier
	//	 or city name. For inbound calls, includes the SIP trunk name,
	//	  SIP URI, or PSTN number the call is forwarded to.
	Destination *string `json:"destination,omitempty" url:"destination,omitempty"`
	// Price per minute in USD.
	PerMinute *string `json:"per_minute,omitempty" url:"per_minute,omitempty"`
	// URL of the recorded call file. Call recording can be enabled
	//
	//	on a SIP trunk for outbound calls and on
	//	 a phone number for inbound calls.
	RecordingURL *string `json:"recording_url,omitempty" url:"recording_url,omitempty"`
	// Total charge for the call in USD.
	Charge *string `json:"charge,omitempty" url:"charge,omitempty"`
	// System-generated SIP trunk login. For outbound calls only.
	SipTrunk *string `json:"sip_trunk,omitempty" url:"sip_trunk,omitempty"`
	// PSTN forwarding price in USD. For inbound calls only
	//
	//	when forwarded to PSTN.
	ForwardFee *string `json:"forward_fee,omitempty" url:"forward_fee,omitempty"`
	// Call ID. Deprecated — use `call_id` instead.
	UUID string `json:"uuid" url:"uuid"`
	// Call ID. Alias of `uuid`.
	CallID string `json:"call_id" url:"call_id"`
	// Parent call ID. Deprecated — use `parent_call_id` instead.
	ParentUUID *string `json:"parent_uuid,omitempty" url:"parent_uuid,omitempty"`
	// Parent call ID. Alias of `parent_uuid`.
	ParentCallID *string `json:"parent_call_id,omitempty" url:"parent_call_id,omitempty"`
	// Who answered the call. Possible values are `human`, `machine`.
	AnsweredBy    *string                 `json:"answered_by,omitempty" url:"answered_by,omitempty"`
	Transcription *TranscriptionReference `json:"transcription,omitempty" url:"transcription,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CdrResponse) GetDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.Date
}

func (c *CdrResponse) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *CdrResponse) GetTo() string {
	if c == nil {
		return ""
	}
	return c.To
}

func (c *CdrResponse) GetDisposition() CallDisposition {
	if c == nil {
		return ""
	}
	return c.Disposition
}

func (c *CdrResponse) GetDuration() int {
	if c == nil {
		return 0
	}
	return c.Duration
}

func (c *CdrResponse) GetDestination() *string {
	if c == nil {
		return nil
	}
	return c.Destination
}

func (c *CdrResponse) GetPerMinute() *string {
	if c == nil {
		return nil
	}
	return c.PerMinute
}

func (c *CdrResponse) GetRecordingURL() *string {
	if c == nil {
		return nil
	}
	return c.RecordingURL
}

func (c *CdrResponse) GetCharge() *string {
	if c == nil {
		return nil
	}
	return c.Charge
}

func (c *CdrResponse) GetSipTrunk() *string {
	if c == nil {
		return nil
	}
	return c.SipTrunk
}

func (c *CdrResponse) GetForwardFee() *string {
	if c == nil {
		return nil
	}
	return c.ForwardFee
}

func (c *CdrResponse) GetUUID() string {
	if c == nil {
		return ""
	}
	return c.UUID
}

func (c *CdrResponse) GetCallID() string {
	if c == nil {
		return ""
	}
	return c.CallID
}

func (c *CdrResponse) GetParentUUID() *string {
	if c == nil {
		return nil
	}
	return c.ParentUUID
}

func (c *CdrResponse) GetParentCallID() *string {
	if c == nil {
		return nil
	}
	return c.ParentCallID
}

func (c *CdrResponse) GetAnsweredBy() *string {
	if c == nil {
		return nil
	}
	return c.AnsweredBy
}

func (c *CdrResponse) GetTranscription() *TranscriptionReference {
	if c == nil {
		return nil
	}
	return c.Transcription
}

func (c *CdrResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CdrResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetDate(date *time.Time) {
	c.Date = date
	c.require(cdrResponseFieldDate)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetFrom(from string) {
	c.From = from
	c.require(cdrResponseFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetTo(to string) {
	c.To = to
	c.require(cdrResponseFieldTo)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetDisposition(disposition CallDisposition) {
	c.Disposition = disposition
	c.require(cdrResponseFieldDisposition)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetDuration(duration int) {
	c.Duration = duration
	c.require(cdrResponseFieldDuration)
}

// SetDestination sets the Destination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetDestination(destination *string) {
	c.Destination = destination
	c.require(cdrResponseFieldDestination)
}

// SetPerMinute sets the PerMinute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetPerMinute(perMinute *string) {
	c.PerMinute = perMinute
	c.require(cdrResponseFieldPerMinute)
}

// SetRecordingURL sets the RecordingURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetRecordingURL(recordingURL *string) {
	c.RecordingURL = recordingURL
	c.require(cdrResponseFieldRecordingURL)
}

// SetCharge sets the Charge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetCharge(charge *string) {
	c.Charge = charge
	c.require(cdrResponseFieldCharge)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetSipTrunk(sipTrunk *string) {
	c.SipTrunk = sipTrunk
	c.require(cdrResponseFieldSipTrunk)
}

// SetForwardFee sets the ForwardFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetForwardFee(forwardFee *string) {
	c.ForwardFee = forwardFee
	c.require(cdrResponseFieldForwardFee)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetUUID(uuid string) {
	c.UUID = uuid
	c.require(cdrResponseFieldUUID)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetCallID(callID string) {
	c.CallID = callID
	c.require(cdrResponseFieldCallID)
}

// SetParentUUID sets the ParentUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetParentUUID(parentUUID *string) {
	c.ParentUUID = parentUUID
	c.require(cdrResponseFieldParentUUID)
}

// SetParentCallID sets the ParentCallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetParentCallID(parentCallID *string) {
	c.ParentCallID = parentCallID
	c.require(cdrResponseFieldParentCallID)
}

// SetAnsweredBy sets the AnsweredBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetAnsweredBy(answeredBy *string) {
	c.AnsweredBy = answeredBy
	c.require(cdrResponseFieldAnsweredBy)
}

// SetTranscription sets the Transcription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrResponse) SetTranscription(transcription *TranscriptionReference) {
	c.Transcription = transcription
	c.require(cdrResponseFieldTranscription)
}

func (c *CdrResponse) UnmarshalJSON(data []byte) error {
	type embed CdrResponse
	var unmarshaler = struct {
		embed
		Date *internal.DateTime `json:"date,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CdrResponse(unmarshaler.embed)
	c.Date = unmarshaler.Date.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CdrResponse) MarshalJSON() ([]byte, error) {
	type embed CdrResponse
	var marshaler = struct {
		embed
		Date *internal.DateTime `json:"date,omitempty"`
	}{
		embed: embed(*c),
		Date:  internal.NewOptionalDateTime(c.Date),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CdrResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cdrTranscriptionSearchResponseFieldItems      = big.NewInt(1 << 0)
	cdrTranscriptionSearchResponseFieldPagination = big.NewInt(1 << 1)
)

type CdrTranscriptionSearchResponse struct {
	// List of CDRs with transcription links.
	Items      []*CdrWithTranscription `json:"items" url:"items"`
	Pagination *Pagination             `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CdrTranscriptionSearchResponse) GetItems() []*CdrWithTranscription {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CdrTranscriptionSearchResponse) GetPagination() *Pagination {
	if c == nil {
		return nil
	}
	return c.Pagination
}

func (c *CdrTranscriptionSearchResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CdrTranscriptionSearchResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrTranscriptionSearchResponse) SetItems(items []*CdrWithTranscription) {
	c.Items = items
	c.require(cdrTranscriptionSearchResponseFieldItems)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrTranscriptionSearchResponse) SetPagination(pagination *Pagination) {
	c.Pagination = pagination
	c.require(cdrTranscriptionSearchResponseFieldPagination)
}

func (c *CdrTranscriptionSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CdrTranscriptionSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CdrTranscriptionSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CdrTranscriptionSearchResponse) MarshalJSON() ([]byte, error) {
	type embed CdrTranscriptionSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CdrTranscriptionSearchResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A CDR of a single call with call transcription
var (
	cdrWithTranscriptionFieldAnsweredBy    = big.NewInt(1 << 0)
	cdrWithTranscriptionFieldDate          = big.NewInt(1 << 1)
	cdrWithTranscriptionFieldFrom          = big.NewInt(1 << 2)
	cdrWithTranscriptionFieldTo            = big.NewInt(1 << 3)
	cdrWithTranscriptionFieldDisposition   = big.NewInt(1 << 4)
	cdrWithTranscriptionFieldDuration      = big.NewInt(1 << 5)
	cdrWithTranscriptionFieldDestination   = big.NewInt(1 << 6)
	cdrWithTranscriptionFieldPerMinute     = big.NewInt(1 << 7)
	cdrWithTranscriptionFieldCharge        = big.NewInt(1 << 8)
	cdrWithTranscriptionFieldSipTrunk      = big.NewInt(1 << 9)
	cdrWithTranscriptionFieldForwardFee    = big.NewInt(1 << 10)
	cdrWithTranscriptionFieldUUID          = big.NewInt(1 << 11)
	cdrWithTranscriptionFieldCallID        = big.NewInt(1 << 12)
	cdrWithTranscriptionFieldParentUUID    = big.NewInt(1 << 13)
	cdrWithTranscriptionFieldParentCallID  = big.NewInt(1 << 14)
	cdrWithTranscriptionFieldTranscription = big.NewInt(1 << 15)
)

type CdrWithTranscription struct {
	// Who answered the call. Allowed values are `human`, `machine`.
	AnsweredBy *string `json:"answered_by,omitempty" url:"answered_by,omitempty"`
	// Date and time of the call
	Date time.Time `json:"date" url:"date"`
	// ANI/From attribute of the call
	From string `json:"from" url:"from"`
	// DNIS/To attribute of the call
	To          string          `json:"to" url:"to"`
	Disposition CallDisposition `json:"disposition" url:"disposition"`
	// Duration of the call, in seconds
	Duration int `json:"duration" url:"duration"`
	// Destination of the call. For outbound calls, it contains the country name and, optionally, a mobile carrier or city name. For inbound calls, the destination includes the user-defined SIP trunk name, SIP URI, or PSTN number that the call is forwarded to.
	Destination string `json:"destination" url:"destination"`
	// Price per minute, in USD
	PerMinute string `json:"per_minute" url:"per_minute"`
	// Total charge for the call, in USD
	Charge string `json:"charge" url:"charge"`
	// System-generated login of a SIP trunk. For `placed` calls only.
	SipTrunk *string `json:"sip_trunk,omitempty" url:"sip_trunk,omitempty"`
	// PSTN forwarding price, in USD. For `received` calls only when forwarded to PSTN.
	ForwardFee *string `json:"forward_fee,omitempty" url:"forward_fee,omitempty"`
	// Call ID. Deprecated — use `call_id` instead.
	UUID string `json:"uuid" url:"uuid"`
	// Call ID. Alias of `uuid`.
	CallID string `json:"call_id" url:"call_id"`
	// Parent call ID. Deprecated — use `parent_call_id` instead.
	ParentUUID *string `json:"parent_uuid,omitempty" url:"parent_uuid,omitempty"`
	// Parent call ID. Alias of `parent_uuid`.
	ParentCallID  *string                 `json:"parent_call_id,omitempty" url:"parent_call_id,omitempty"`
	Transcription *TranscriptionReference `json:"transcription,omitempty" url:"transcription,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CdrWithTranscription) GetAnsweredBy() *string {
	if c == nil {
		return nil
	}
	return c.AnsweredBy
}

func (c *CdrWithTranscription) GetDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Date
}

func (c *CdrWithTranscription) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *CdrWithTranscription) GetTo() string {
	if c == nil {
		return ""
	}
	return c.To
}

func (c *CdrWithTranscription) GetDisposition() CallDisposition {
	if c == nil {
		return ""
	}
	return c.Disposition
}

func (c *CdrWithTranscription) GetDuration() int {
	if c == nil {
		return 0
	}
	return c.Duration
}

func (c *CdrWithTranscription) GetDestination() string {
	if c == nil {
		return ""
	}
	return c.Destination
}

func (c *CdrWithTranscription) GetPerMinute() string {
	if c == nil {
		return ""
	}
	return c.PerMinute
}

func (c *CdrWithTranscription) GetCharge() string {
	if c == nil {
		return ""
	}
	return c.Charge
}

func (c *CdrWithTranscription) GetSipTrunk() *string {
	if c == nil {
		return nil
	}
	return c.SipTrunk
}

func (c *CdrWithTranscription) GetForwardFee() *string {
	if c == nil {
		return nil
	}
	return c.ForwardFee
}

func (c *CdrWithTranscription) GetUUID() string {
	if c == nil {
		return ""
	}
	return c.UUID
}

func (c *CdrWithTranscription) GetCallID() string {
	if c == nil {
		return ""
	}
	return c.CallID
}

func (c *CdrWithTranscription) GetParentUUID() *string {
	if c == nil {
		return nil
	}
	return c.ParentUUID
}

func (c *CdrWithTranscription) GetParentCallID() *string {
	if c == nil {
		return nil
	}
	return c.ParentCallID
}

func (c *CdrWithTranscription) GetTranscription() *TranscriptionReference {
	if c == nil {
		return nil
	}
	return c.Transcription
}

func (c *CdrWithTranscription) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CdrWithTranscription) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAnsweredBy sets the AnsweredBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetAnsweredBy(answeredBy *string) {
	c.AnsweredBy = answeredBy
	c.require(cdrWithTranscriptionFieldAnsweredBy)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetDate(date time.Time) {
	c.Date = date
	c.require(cdrWithTranscriptionFieldDate)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetFrom(from string) {
	c.From = from
	c.require(cdrWithTranscriptionFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetTo(to string) {
	c.To = to
	c.require(cdrWithTranscriptionFieldTo)
}

// SetDisposition sets the Disposition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetDisposition(disposition CallDisposition) {
	c.Disposition = disposition
	c.require(cdrWithTranscriptionFieldDisposition)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetDuration(duration int) {
	c.Duration = duration
	c.require(cdrWithTranscriptionFieldDuration)
}

// SetDestination sets the Destination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetDestination(destination string) {
	c.Destination = destination
	c.require(cdrWithTranscriptionFieldDestination)
}

// SetPerMinute sets the PerMinute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetPerMinute(perMinute string) {
	c.PerMinute = perMinute
	c.require(cdrWithTranscriptionFieldPerMinute)
}

// SetCharge sets the Charge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetCharge(charge string) {
	c.Charge = charge
	c.require(cdrWithTranscriptionFieldCharge)
}

// SetSipTrunk sets the SipTrunk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetSipTrunk(sipTrunk *string) {
	c.SipTrunk = sipTrunk
	c.require(cdrWithTranscriptionFieldSipTrunk)
}

// SetForwardFee sets the ForwardFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetForwardFee(forwardFee *string) {
	c.ForwardFee = forwardFee
	c.require(cdrWithTranscriptionFieldForwardFee)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetUUID(uuid string) {
	c.UUID = uuid
	c.require(cdrWithTranscriptionFieldUUID)
}

// SetCallID sets the CallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetCallID(callID string) {
	c.CallID = callID
	c.require(cdrWithTranscriptionFieldCallID)
}

// SetParentUUID sets the ParentUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetParentUUID(parentUUID *string) {
	c.ParentUUID = parentUUID
	c.require(cdrWithTranscriptionFieldParentUUID)
}

// SetParentCallID sets the ParentCallID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetParentCallID(parentCallID *string) {
	c.ParentCallID = parentCallID
	c.require(cdrWithTranscriptionFieldParentCallID)
}

// SetTranscription sets the Transcription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CdrWithTranscription) SetTranscription(transcription *TranscriptionReference) {
	c.Transcription = transcription
	c.require(cdrWithTranscriptionFieldTranscription)
}

func (c *CdrWithTranscription) UnmarshalJSON(data []byte) error {
	type embed CdrWithTranscription
	var unmarshaler = struct {
		embed
		Date *internal.DateTime `json:"date"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CdrWithTranscription(unmarshaler.embed)
	c.Date = unmarshaler.Date.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CdrWithTranscription) MarshalJSON() ([]byte, error) {
	type embed CdrWithTranscription
	var marshaler = struct {
		embed
		Date *internal.DateTime `json:"date"`
	}{
		embed: embed(*c),
		Date:  internal.NewDateTime(c.Date),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CdrWithTranscription) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	transcriptionFilterFieldAgent  = big.NewInt(1 << 0)
	transcriptionFilterFieldClient = big.NewInt(1 << 1)
	transcriptionFilterFieldAny    = big.NewInt(1 << 2)
)

type TranscriptionFilter struct {
	// Search in an agent's spoken words and phrases
	Agent *TranscriptionFilterAgent `json:"agent" url:"agent"`
	// Search in an customer's spoken words and phrases
	Client *TranscriptionFilterClient `json:"client" url:"client"`
	// Search in both speakers' spoken words and phrases
	Any *TranscriptionFilterAny `json:"any" url:"any"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TranscriptionFilter) GetAgent() *TranscriptionFilterAgent {
	if t == nil {
		return nil
	}
	return t.Agent
}

func (t *TranscriptionFilter) GetClient() *TranscriptionFilterClient {
	if t == nil {
		return nil
	}
	return t.Client
}

func (t *TranscriptionFilter) GetAny() *TranscriptionFilterAny {
	if t == nil {
		return nil
	}
	return t.Any
}

func (t *TranscriptionFilter) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TranscriptionFilter) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetAgent sets the Agent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilter) SetAgent(agent *TranscriptionFilterAgent) {
	t.Agent = agent
	t.require(transcriptionFilterFieldAgent)
}

// SetClient sets the Client field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilter) SetClient(client *TranscriptionFilterClient) {
	t.Client = client
	t.require(transcriptionFilterFieldClient)
}

// SetAny sets the Any field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilter) SetAny(any_ *TranscriptionFilterAny) {
	t.Any = any_
	t.require(transcriptionFilterFieldAny)
}

func (t *TranscriptionFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionFilter) MarshalJSON() ([]byte, error) {
	type embed TranscriptionFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TranscriptionFilter) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Search in an agent's spoken words and phrases
var (
	transcriptionFilterAgentFieldMust    = big.NewInt(1 << 0)
	transcriptionFilterAgentFieldMatch   = big.NewInt(1 << 1)
	transcriptionFilterAgentFieldExclude = big.NewInt(1 << 2)
)

type TranscriptionFilterAgent struct {
	// Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND
	Must []string `json:"must,omitempty" url:"must,omitempty"`
	// Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Match []string `json:"match,omitempty" url:"match,omitempty"`
	// Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Exclude []string `json:"exclude,omitempty" url:"exclude,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TranscriptionFilterAgent) GetMust() []string {
	if t == nil {
		return nil
	}
	return t.Must
}

func (t *TranscriptionFilterAgent) GetMatch() []string {
	if t == nil {
		return nil
	}
	return t.Match
}

func (t *TranscriptionFilterAgent) GetExclude() []string {
	if t == nil {
		return nil
	}
	return t.Exclude
}

func (t *TranscriptionFilterAgent) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TranscriptionFilterAgent) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetMust sets the Must field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAgent) SetMust(must []string) {
	t.Must = must
	t.require(transcriptionFilterAgentFieldMust)
}

// SetMatch sets the Match field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAgent) SetMatch(match []string) {
	t.Match = match
	t.require(transcriptionFilterAgentFieldMatch)
}

// SetExclude sets the Exclude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAgent) SetExclude(exclude []string) {
	t.Exclude = exclude
	t.require(transcriptionFilterAgentFieldExclude)
}

func (t *TranscriptionFilterAgent) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionFilterAgent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionFilterAgent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionFilterAgent) MarshalJSON() ([]byte, error) {
	type embed TranscriptionFilterAgent
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TranscriptionFilterAgent) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Search in both speakers' spoken words and phrases
var (
	transcriptionFilterAnyFieldMust    = big.NewInt(1 << 0)
	transcriptionFilterAnyFieldMatch   = big.NewInt(1 << 1)
	transcriptionFilterAnyFieldExclude = big.NewInt(1 << 2)
)

type TranscriptionFilterAny struct {
	// Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND
	Must []string `json:"must,omitempty" url:"must,omitempty"`
	// Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Match []string `json:"match,omitempty" url:"match,omitempty"`
	// Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Exclude []string `json:"exclude,omitempty" url:"exclude,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TranscriptionFilterAny) GetMust() []string {
	if t == nil {
		return nil
	}
	return t.Must
}

func (t *TranscriptionFilterAny) GetMatch() []string {
	if t == nil {
		return nil
	}
	return t.Match
}

func (t *TranscriptionFilterAny) GetExclude() []string {
	if t == nil {
		return nil
	}
	return t.Exclude
}

func (t *TranscriptionFilterAny) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TranscriptionFilterAny) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetMust sets the Must field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAny) SetMust(must []string) {
	t.Must = must
	t.require(transcriptionFilterAnyFieldMust)
}

// SetMatch sets the Match field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAny) SetMatch(match []string) {
	t.Match = match
	t.require(transcriptionFilterAnyFieldMatch)
}

// SetExclude sets the Exclude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterAny) SetExclude(exclude []string) {
	t.Exclude = exclude
	t.require(transcriptionFilterAnyFieldExclude)
}

func (t *TranscriptionFilterAny) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionFilterAny
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionFilterAny(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionFilterAny) MarshalJSON() ([]byte, error) {
	type embed TranscriptionFilterAny
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TranscriptionFilterAny) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Search in an customer's spoken words and phrases
var (
	transcriptionFilterClientFieldMust    = big.NewInt(1 << 0)
	transcriptionFilterClientFieldMatch   = big.NewInt(1 << 1)
	transcriptionFilterClientFieldExclude = big.NewInt(1 << 2)
)

type TranscriptionFilterClient struct {
	// Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND
	Must []string `json:"must,omitempty" url:"must,omitempty"`
	// Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Match []string `json:"match,omitempty" url:"match,omitempty"`
	// Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR
	Exclude []string `json:"exclude,omitempty" url:"exclude,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TranscriptionFilterClient) GetMust() []string {
	if t == nil {
		return nil
	}
	return t.Must
}

func (t *TranscriptionFilterClient) GetMatch() []string {
	if t == nil {
		return nil
	}
	return t.Match
}

func (t *TranscriptionFilterClient) GetExclude() []string {
	if t == nil {
		return nil
	}
	return t.Exclude
}

func (t *TranscriptionFilterClient) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TranscriptionFilterClient) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetMust sets the Must field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterClient) SetMust(must []string) {
	t.Must = must
	t.require(transcriptionFilterClientFieldMust)
}

// SetMatch sets the Match field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterClient) SetMatch(match []string) {
	t.Match = match
	t.require(transcriptionFilterClientFieldMatch)
}

// SetExclude sets the Exclude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionFilterClient) SetExclude(exclude []string) {
	t.Exclude = exclude
	t.require(transcriptionFilterClientFieldExclude)
}

func (t *TranscriptionFilterClient) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionFilterClient
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionFilterClient(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionFilterClient) MarshalJSON() ([]byte, error) {
	type embed TranscriptionFilterClient
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TranscriptionFilterClient) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	transcriptionReferenceFieldUUID = big.NewInt(1 << 0)
	transcriptionReferenceFieldURL  = big.NewInt(1 << 1)
)

type TranscriptionReference struct {
	// Unique identifier of the call transcription.
	UUID string `json:"uuid" url:"uuid"`
	// URL for retrieving the full call transcription.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TranscriptionReference) GetUUID() string {
	if t == nil {
		return ""
	}
	return t.UUID
}

func (t *TranscriptionReference) GetURL() string {
	if t == nil {
		return ""
	}
	return t.URL
}

func (t *TranscriptionReference) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TranscriptionReference) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionReference) SetUUID(uuid string) {
	t.UUID = uuid
	t.require(transcriptionReferenceFieldUUID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TranscriptionReference) SetURL(url string) {
	t.URL = url
	t.require(transcriptionReferenceFieldURL)
}

func (t *TranscriptionReference) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionReference
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionReference(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionReference) MarshalJSON() ([]byte, error) {
	type embed TranscriptionReference
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TranscriptionReference) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Call disposition to filter results.  If omitted, returns only answered
//
//	calls. Allowed values: `answered`, `busy`, `rejected`,
//	 `failed`, `all`. Use `all` to return calls
//	  regardless of their disposition.
type CdrSearchRequestDisposition string

const (
	CdrSearchRequestDispositionAnswered CdrSearchRequestDisposition = "answered"
	CdrSearchRequestDispositionNoanswer CdrSearchRequestDisposition = "noanswer"
	CdrSearchRequestDispositionBusy     CdrSearchRequestDisposition = "busy"
	CdrSearchRequestDispositionFailed   CdrSearchRequestDisposition = "failed"
	CdrSearchRequestDispositionAll      CdrSearchRequestDisposition = "all"
)

func NewCdrSearchRequestDispositionFromString(s string) (CdrSearchRequestDisposition, error) {
	switch s {
	case "answered":
		return CdrSearchRequestDispositionAnswered, nil
	case "noanswer":
		return CdrSearchRequestDispositionNoanswer, nil
	case "busy":
		return CdrSearchRequestDispositionBusy, nil
	case "failed":
		return CdrSearchRequestDispositionFailed, nil
	case "all":
		return CdrSearchRequestDispositionAll, nil
	}
	var t CdrSearchRequestDisposition
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CdrSearchRequestDisposition) Ptr() *CdrSearchRequestDisposition {
	return &c
}

// Filters by call type. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account).
type CdrSearchRequestType string

const (
	CdrSearchRequestTypePlaced   CdrSearchRequestType = "placed"
	CdrSearchRequestTypeReceived CdrSearchRequestType = "received"
)

func NewCdrSearchRequestTypeFromString(s string) (CdrSearchRequestType, error) {
	switch s {
	case "placed":
		return CdrSearchRequestTypePlaced, nil
	case "received":
		return CdrSearchRequestTypeReceived, nil
	}
	var t CdrSearchRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CdrSearchRequestType) Ptr() *CdrSearchRequestType {
	return &c
}
