// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	phoneValidationRequestFieldPhoneNumbers = big.NewInt(1 << 0)
	phoneValidationRequestFieldType         = big.NewInt(1 << 1)
	phoneValidationRequestFieldAsync        = big.NewInt(1 << 2)
	phoneValidationRequestFieldForce        = big.NewInt(1 << 3)
)

type PhoneValidationRequest struct {
	// List of phone numbers to get detailed information about.
	PhoneNumbers []string                  `json:"phone_numbers" url:"-"`
	Type         PhoneNumberValidationType `json:"type" url:"-"`
	// Indicates whether the request should be executed asynchronously. If `true`, the response will include a `request_uuid` that can be used to poll for results. If `false`, the response will include validation results directly.
	Async bool `json:"async" url:"-"`
	// Indicates whether to force a fresh validation instead of returning a previously cached result.
	Force bool `json:"force" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhoneValidationRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPhoneNumbers sets the PhoneNumbers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationRequest) SetPhoneNumbers(phoneNumbers []string) {
	p.PhoneNumbers = phoneNumbers
	p.require(phoneValidationRequestFieldPhoneNumbers)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationRequest) SetType(type_ PhoneNumberValidationType) {
	p.Type = type_
	p.require(phoneValidationRequestFieldType)
}

// SetAsync sets the Async field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationRequest) SetAsync(async bool) {
	p.Async = async
	p.require(phoneValidationRequestFieldAsync)
}

// SetForce sets the Force field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationRequest) SetForce(force bool) {
	p.Force = force
	p.require(phoneValidationRequestFieldForce)
}

func (p *PhoneValidationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneValidationRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PhoneValidationRequest(body)
	return nil
}

func (p *PhoneValidationRequest) MarshalJSON() ([]byte, error) {
	type embed PhoneValidationRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getNumberValidatorRequestFieldPhoneNumber = big.NewInt(1 << 0)
	getNumberValidatorRequestFieldType        = big.NewInt(1 << 1)
)

type GetNumberValidatorRequest struct {
	// The phone number to validate, in E.164 format with or without the leading `+`.
	PhoneNumber string `json:"-" url:"phone_number"`
	// Depth of validation to perform. Accepts a `PhoneNumberValidationType` value.
	Type PhoneNumberValidationType `json:"-" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNumberValidatorRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorRequest) SetPhoneNumber(phoneNumber string) {
	g.PhoneNumber = phoneNumber
	g.require(getNumberValidatorRequestFieldPhoneNumber)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorRequest) SetType(type_ PhoneNumberValidationType) {
	g.Type = type_
	g.require(getNumberValidatorRequestFieldType)
}

type NumberValidatorCreateBulkResponse struct {
	PhoneValidationBatchResponse *PhoneValidationBatchResponse
	// Returned when validation runs asynchronously; poll results using `request_id`.
	NumberValidatorCreateBulkResponseRequestID *NumberValidatorCreateBulkResponseRequestID

	typ string
}

func (n *NumberValidatorCreateBulkResponse) GetPhoneValidationBatchResponse() *PhoneValidationBatchResponse {
	if n == nil {
		return nil
	}
	return n.PhoneValidationBatchResponse
}

func (n *NumberValidatorCreateBulkResponse) GetNumberValidatorCreateBulkResponseRequestID() *NumberValidatorCreateBulkResponseRequestID {
	if n == nil {
		return nil
	}
	return n.NumberValidatorCreateBulkResponseRequestID
}

func (n *NumberValidatorCreateBulkResponse) UnmarshalJSON(data []byte) error {
	valuePhoneValidationBatchResponse := new(PhoneValidationBatchResponse)
	if err := json.Unmarshal(data, &valuePhoneValidationBatchResponse); err == nil {
		n.typ = "PhoneValidationBatchResponse"
		n.PhoneValidationBatchResponse = valuePhoneValidationBatchResponse
		return nil
	}
	valueNumberValidatorCreateBulkResponseRequestID := new(NumberValidatorCreateBulkResponseRequestID)
	if err := json.Unmarshal(data, &valueNumberValidatorCreateBulkResponseRequestID); err == nil {
		n.typ = "NumberValidatorCreateBulkResponseRequestID"
		n.NumberValidatorCreateBulkResponseRequestID = valueNumberValidatorCreateBulkResponseRequestID
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, n)
}

func (n NumberValidatorCreateBulkResponse) MarshalJSON() ([]byte, error) {
	if n.typ == "PhoneValidationBatchResponse" || n.PhoneValidationBatchResponse != nil {
		return json.Marshal(n.PhoneValidationBatchResponse)
	}
	if n.typ == "NumberValidatorCreateBulkResponseRequestID" || n.NumberValidatorCreateBulkResponseRequestID != nil {
		return json.Marshal(n.NumberValidatorCreateBulkResponseRequestID)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", n)
}

type NumberValidatorCreateBulkResponseVisitor interface {
	VisitPhoneValidationBatchResponse(*PhoneValidationBatchResponse) error
	VisitNumberValidatorCreateBulkResponseRequestID(*NumberValidatorCreateBulkResponseRequestID) error
}

func (n *NumberValidatorCreateBulkResponse) Accept(visitor NumberValidatorCreateBulkResponseVisitor) error {
	if n.typ == "PhoneValidationBatchResponse" || n.PhoneValidationBatchResponse != nil {
		return visitor.VisitPhoneValidationBatchResponse(n.PhoneValidationBatchResponse)
	}
	if n.typ == "NumberValidatorCreateBulkResponseRequestID" || n.NumberValidatorCreateBulkResponseRequestID != nil {
		return visitor.VisitNumberValidatorCreateBulkResponseRequestID(n.NumberValidatorCreateBulkResponseRequestID)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", n)
}

// Returned when validation runs asynchronously; poll results using `request_id`.
var (
	numberValidatorCreateBulkResponseRequestIDFieldRequestID = big.NewInt(1 << 0)
)

type NumberValidatorCreateBulkResponseRequestID struct {
	// Request ID. Use to poll validation results when `async` is `true`.
	RequestID *string `json:"request_id,omitempty" url:"request_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NumberValidatorCreateBulkResponseRequestID) GetRequestID() *string {
	if n == nil {
		return nil
	}
	return n.RequestID
}

func (n *NumberValidatorCreateBulkResponseRequestID) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NumberValidatorCreateBulkResponseRequestID) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NumberValidatorCreateBulkResponseRequestID) SetRequestID(requestID *string) {
	n.RequestID = requestID
	n.require(numberValidatorCreateBulkResponseRequestIDFieldRequestID)
}

func (n *NumberValidatorCreateBulkResponseRequestID) UnmarshalJSON(data []byte) error {
	type unmarshaler NumberValidatorCreateBulkResponseRequestID
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NumberValidatorCreateBulkResponseRequestID(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NumberValidatorCreateBulkResponseRequestID) MarshalJSON() ([]byte, error) {
	type embed NumberValidatorCreateBulkResponseRequestID
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NumberValidatorCreateBulkResponseRequestID) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Depth of validation to perform on the phone number. One of `format` (checks number syntax only), `analysis` (returns number metadata such as type and country), or `validation` (performs a live network lookup of the number's current status).
type PhoneNumberValidationType string

const (
	PhoneNumberValidationTypeFormat     PhoneNumberValidationType = "format"
	PhoneNumberValidationTypeAnalysis   PhoneNumberValidationType = "analysis"
	PhoneNumberValidationTypeValidation PhoneNumberValidationType = "validation"
)

func NewPhoneNumberValidationTypeFromString(s string) (PhoneNumberValidationType, error) {
	switch s {
	case "format":
		return PhoneNumberValidationTypeFormat, nil
	case "analysis":
		return PhoneNumberValidationTypeAnalysis, nil
	case "validation":
		return PhoneNumberValidationTypeValidation, nil
	}
	var t PhoneNumberValidationType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PhoneNumberValidationType) Ptr() *PhoneNumberValidationType {
	return &p
}

var (
	phoneValidationBatchResponseFieldStatus  = big.NewInt(1 << 0)
	phoneValidationBatchResponseFieldPending = big.NewInt(1 << 1)
	phoneValidationBatchResponseFieldCount   = big.NewInt(1 << 2)
	phoneValidationBatchResponseFieldItems   = big.NewInt(1 << 3)
)

type PhoneValidationBatchResponse struct {
	// Validation request status.
	Status string `json:"status" url:"status"`
	// Number of validations still in progress.
	Pending int `json:"pending" url:"pending"`
	// Total number of phone numbers in the request.
	Count int `json:"count" url:"count"`
	// List of validation results for each phone number.
	Items []*PhoneValidationResultResponse `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneValidationBatchResponse) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PhoneValidationBatchResponse) GetPending() int {
	if p == nil {
		return 0
	}
	return p.Pending
}

func (p *PhoneValidationBatchResponse) GetCount() int {
	if p == nil {
		return 0
	}
	return p.Count
}

func (p *PhoneValidationBatchResponse) GetItems() []*PhoneValidationResultResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PhoneValidationBatchResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneValidationBatchResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationBatchResponse) SetStatus(status string) {
	p.Status = status
	p.require(phoneValidationBatchResponseFieldStatus)
}

// SetPending sets the Pending field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationBatchResponse) SetPending(pending int) {
	p.Pending = pending
	p.require(phoneValidationBatchResponseFieldPending)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationBatchResponse) SetCount(count int) {
	p.Count = count
	p.require(phoneValidationBatchResponseFieldCount)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneValidationBatchResponse) SetItems(items []*PhoneValidationResultResponse) {
	p.Items = items
	p.require(phoneValidationBatchResponseFieldItems)
}

func (p *PhoneValidationBatchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneValidationBatchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneValidationBatchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneValidationBatchResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneValidationBatchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneValidationBatchResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	getNumberValidatorResponseFieldPhoneNumber      = big.NewInt(1 << 0)
	getNumberValidatorResponseFieldValid            = big.NewInt(1 << 1)
	getNumberValidatorResponseFieldCountryCode      = big.NewInt(1 << 2)
	getNumberValidatorResponseFieldE164Format       = big.NewInt(1 << 3)
	getNumberValidatorResponseFieldNationalFormat   = big.NewInt(1 << 4)
	getNumberValidatorResponseFieldPorted           = big.NewInt(1 << 5)
	getNumberValidatorResponseFieldMcc              = big.NewInt(1 << 6)
	getNumberValidatorResponseFieldMnc              = big.NewInt(1 << 7)
	getNumberValidatorResponseFieldNumberType       = big.NewInt(1 << 8)
	getNumberValidatorResponseFieldCarrierName      = big.NewInt(1 << 9)
	getNumberValidatorResponseFieldRiskyDestination = big.NewInt(1 << 10)
	getNumberValidatorResponseFieldUnallocatedRange = big.NewInt(1 << 11)
	getNumberValidatorResponseFieldReachable        = big.NewInt(1 << 12)
	getNumberValidatorResponseFieldRoaming          = big.NewInt(1 << 13)
	getNumberValidatorResponseFieldTimezone         = big.NewInt(1 << 14)
	getNumberValidatorResponseFieldCharge           = big.NewInt(1 << 15)
	getNumberValidatorResponseFieldErrorCode        = big.NewInt(1 << 16)
)

type GetNumberValidatorResponse struct {
	// Phone number.
	PhoneNumber string `json:"phone_number" url:"phone_number"`
	// Indicates whether the phone number is valid.
	Valid bool `json:"valid" url:"valid"`
	// ISO 3166-1 alpha-2 country code of the phone number.
	//
	//	`null` if the number is invalid.
	CountryCode *string `json:"country_code,omitempty" url:"country_code,omitempty"`
	// Phone number in international E.164 format.
	E164Format string `json:"e164_format" url:"e164_format"`
	// Phone number in the national format of the identified country.
	NationalFormat string `json:"national_format" url:"national_format"`
	// Indicates whether the phone number was ported or not. `null` if the phone number is invalid.
	Ported *bool `json:"ported,omitempty" url:"ported,omitempty"`
	// Mobile Country Code of the phone number carrier. For mobile phone numbers only. `null` if the phone number is invalid.
	Mcc *string `json:"mcc,omitempty" url:"mcc,omitempty"`
	// Mobile Network Code of the phone number carrier. For mobile phone numbers only. `null` if the phone number is invalid
	Mnc *string `json:"mnc,omitempty" url:"mnc,omitempty"`
	// Number type. Possible values are `mobile`, `landline`, or `toll-free`. `null` if the phone number is invalid.
	NumberType *string `json:"number_type,omitempty" url:"number_type,omitempty"`
	// Name of the phone number carrier. `null` if the phone number is invalid.
	CarrierName *string `json:"carrier_name,omitempty" url:"carrier_name,omitempty"`
	// Indicates whether the phone number belongs to a number range associated with traffic pumping. `null` if the number is invalid.
	RiskyDestination *bool `json:"risky_destination,omitempty" url:"risky_destination,omitempty"`
	// Indicates whether the phone number belongs to an unallocated number range. `null` if the number is invalid
	UnallocatedRange *bool `json:"unallocated_range,omitempty" url:"unallocated_range,omitempty"`
	// Indicates whether the number is registered in a mobile network. For mobile phone numbers only. `null` if the number is invalid
	Reachable *bool `json:"reachable,omitempty" url:"reachable,omitempty"`
	// Indicates whether the number is roaming. For mobile phone numbers only. `null` if the number is invalid
	Roaming *bool `json:"roaming,omitempty" url:"roaming,omitempty"`
	// Time zone based on the phone number's country and area code.
	//
	//	`null` if the number is invalid.
	Timezone *string `json:"timezone,omitempty" url:"timezone,omitempty"`
	// Charge for the validation.
	Charge string `json:"charge" url:"charge"`
	// Error code for the request. `000` indicates success.
	// Possible values:
	// - `013`: — Internal service error
	// - `021`: — Invalid phone number length or format
	// - `041`: — Request timeout
	// - `042`: — Request failed
	// - `091`: — Insufficient funds
	ErrorCode string `json:"error_code" url:"error_code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetNumberValidatorResponse) GetPhoneNumber() string {
	if g == nil {
		return ""
	}
	return g.PhoneNumber
}

func (g *GetNumberValidatorResponse) GetValid() bool {
	if g == nil {
		return false
	}
	return g.Valid
}

func (g *GetNumberValidatorResponse) GetCountryCode() *string {
	if g == nil {
		return nil
	}
	return g.CountryCode
}

func (g *GetNumberValidatorResponse) GetE164Format() string {
	if g == nil {
		return ""
	}
	return g.E164Format
}

func (g *GetNumberValidatorResponse) GetNationalFormat() string {
	if g == nil {
		return ""
	}
	return g.NationalFormat
}

func (g *GetNumberValidatorResponse) GetPorted() *bool {
	if g == nil {
		return nil
	}
	return g.Ported
}

func (g *GetNumberValidatorResponse) GetMcc() *string {
	if g == nil {
		return nil
	}
	return g.Mcc
}

func (g *GetNumberValidatorResponse) GetMnc() *string {
	if g == nil {
		return nil
	}
	return g.Mnc
}

func (g *GetNumberValidatorResponse) GetNumberType() *string {
	if g == nil {
		return nil
	}
	return g.NumberType
}

func (g *GetNumberValidatorResponse) GetCarrierName() *string {
	if g == nil {
		return nil
	}
	return g.CarrierName
}

func (g *GetNumberValidatorResponse) GetRiskyDestination() *bool {
	if g == nil {
		return nil
	}
	return g.RiskyDestination
}

func (g *GetNumberValidatorResponse) GetUnallocatedRange() *bool {
	if g == nil {
		return nil
	}
	return g.UnallocatedRange
}

func (g *GetNumberValidatorResponse) GetReachable() *bool {
	if g == nil {
		return nil
	}
	return g.Reachable
}

func (g *GetNumberValidatorResponse) GetRoaming() *bool {
	if g == nil {
		return nil
	}
	return g.Roaming
}

func (g *GetNumberValidatorResponse) GetTimezone() *string {
	if g == nil {
		return nil
	}
	return g.Timezone
}

func (g *GetNumberValidatorResponse) GetCharge() string {
	if g == nil {
		return ""
	}
	return g.Charge
}

func (g *GetNumberValidatorResponse) GetErrorCode() string {
	if g == nil {
		return ""
	}
	return g.ErrorCode
}

func (g *GetNumberValidatorResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetNumberValidatorResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetPhoneNumber(phoneNumber string) {
	g.PhoneNumber = phoneNumber
	g.require(getNumberValidatorResponseFieldPhoneNumber)
}

// SetValid sets the Valid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetValid(valid bool) {
	g.Valid = valid
	g.require(getNumberValidatorResponseFieldValid)
}

// SetCountryCode sets the CountryCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetCountryCode(countryCode *string) {
	g.CountryCode = countryCode
	g.require(getNumberValidatorResponseFieldCountryCode)
}

// SetE164Format sets the E164Format field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetE164Format(e164Format string) {
	g.E164Format = e164Format
	g.require(getNumberValidatorResponseFieldE164Format)
}

// SetNationalFormat sets the NationalFormat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetNationalFormat(nationalFormat string) {
	g.NationalFormat = nationalFormat
	g.require(getNumberValidatorResponseFieldNationalFormat)
}

// SetPorted sets the Ported field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetPorted(ported *bool) {
	g.Ported = ported
	g.require(getNumberValidatorResponseFieldPorted)
}

// SetMcc sets the Mcc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetMcc(mcc *string) {
	g.Mcc = mcc
	g.require(getNumberValidatorResponseFieldMcc)
}

// SetMnc sets the Mnc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetMnc(mnc *string) {
	g.Mnc = mnc
	g.require(getNumberValidatorResponseFieldMnc)
}

// SetNumberType sets the NumberType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetNumberType(numberType *string) {
	g.NumberType = numberType
	g.require(getNumberValidatorResponseFieldNumberType)
}

// SetCarrierName sets the CarrierName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetCarrierName(carrierName *string) {
	g.CarrierName = carrierName
	g.require(getNumberValidatorResponseFieldCarrierName)
}

// SetRiskyDestination sets the RiskyDestination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetRiskyDestination(riskyDestination *bool) {
	g.RiskyDestination = riskyDestination
	g.require(getNumberValidatorResponseFieldRiskyDestination)
}

// SetUnallocatedRange sets the UnallocatedRange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetUnallocatedRange(unallocatedRange *bool) {
	g.UnallocatedRange = unallocatedRange
	g.require(getNumberValidatorResponseFieldUnallocatedRange)
}

// SetReachable sets the Reachable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetReachable(reachable *bool) {
	g.Reachable = reachable
	g.require(getNumberValidatorResponseFieldReachable)
}

// SetRoaming sets the Roaming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetRoaming(roaming *bool) {
	g.Roaming = roaming
	g.require(getNumberValidatorResponseFieldRoaming)
}

// SetTimezone sets the Timezone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetTimezone(timezone *string) {
	g.Timezone = timezone
	g.require(getNumberValidatorResponseFieldTimezone)
}

// SetCharge sets the Charge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetCharge(charge string) {
	g.Charge = charge
	g.require(getNumberValidatorResponseFieldCharge)
}

// SetErrorCode sets the ErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNumberValidatorResponse) SetErrorCode(errorCode string) {
	g.ErrorCode = errorCode
	g.require(getNumberValidatorResponseFieldErrorCode)
}

func (g *GetNumberValidatorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetNumberValidatorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetNumberValidatorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetNumberValidatorResponse) MarshalJSON() ([]byte, error) {
	type embed GetNumberValidatorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetNumberValidatorResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
