// Code generated by Fern. DO NOT EDIT.

package speechanalytics

import (
	big "math/big"
)

var (
	getFileRequestFieldRequestID = big.NewInt(1 << 0)
)

type GetFileRequest struct {
	// The `request_id` of the transcription, returned when the file was uploaded.
	RequestID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFileRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRequest) SetRequestID(requestID string) {
	g.RequestID = requestID
	g.require(getFileRequestFieldRequestID)
}
