// Code generated by Fern. DO NOT EDIT.

package smsandmms

import (
	json "encoding/json"
	fmt "fmt"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	senderIDCreateRequestFieldSenderID      = big.NewInt(1 << 0)
	senderIDCreateRequestFieldType          = big.NewInt(1 << 1)
	senderIDCreateRequestFieldCountries     = big.NewInt(1 << 2)
	senderIDCreateRequestFieldUsecase       = big.NewInt(1 << 3)
	senderIDCreateRequestFieldMonthlyVolume = big.NewInt(1 << 4)
	senderIDCreateRequestFieldSamples       = big.NewInt(1 << 5)
)

type SenderIDCreateRequest struct {
	// Sender ID name. Can be either an alphanumeric string or a  phone number.
	SenderID string                  `json:"sender_id" url:"-"`
	Type     wavixgosdk.SenderIDType `json:"type" url:"-"`
	// Two-letter ISO country codes where the Sender ID is allowlisted.
	Countries []string `json:"countries" url:"-"`
	// Primary use case for the Sender ID. One of `transactional` (account or order notifications), `promo` (marketing and promotional messages), or `authentication` (one-time passcodes and verification codes).
	Usecase SenderIDCreateRequestUsecase `json:"usecase" url:"-"`
	// Expected number of messages sent per month from the Sender ID. One of `1-1000`, `1001-20000`, `20001-50000`, `50001-100000`, or `More than 100000`. Each value is the message-count band for the month.
	MonthlyVolume *SenderIDCreateRequestMonthlyVolume `json:"monthly_volume,omitempty" url:"-"`
	// Message samples.
	Samples []string `json:"samples,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SenderIDCreateRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetSenderID(senderID string) {
	s.SenderID = senderID
	s.require(senderIDCreateRequestFieldSenderID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetType(type_ wavixgosdk.SenderIDType) {
	s.Type = type_
	s.require(senderIDCreateRequestFieldType)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetCountries(countries []string) {
	s.Countries = countries
	s.require(senderIDCreateRequestFieldCountries)
}

// SetUsecase sets the Usecase field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetUsecase(usecase SenderIDCreateRequestUsecase) {
	s.Usecase = usecase
	s.require(senderIDCreateRequestFieldUsecase)
}

// SetMonthlyVolume sets the MonthlyVolume field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetMonthlyVolume(monthlyVolume *SenderIDCreateRequestMonthlyVolume) {
	s.MonthlyVolume = monthlyVolume
	s.require(senderIDCreateRequestFieldMonthlyVolume)
}

// SetSamples sets the Samples field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SenderIDCreateRequest) SetSamples(samples []string) {
	s.Samples = samples
	s.require(senderIDCreateRequestFieldSamples)
}

func (s *SenderIDCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SenderIDCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SenderIDCreateRequest(body)
	return nil
}

func (s *SenderIDCreateRequest) MarshalJSON() ([]byte, error) {
	type embed SenderIDCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteSenderIDsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteSenderIDsRequest struct {
	// The unique ID of the Sender ID.
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSenderIDsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSenderIDsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteSenderIDsRequestFieldID)
}

var (
	getSenderIDsRequestFieldID = big.NewInt(1 << 0)
)

type GetSenderIDsRequest struct {
	// The unique ID of the Sender ID.
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSenderIDsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSenderIDsRequest) SetID(id string) {
	g.ID = id
	g.require(getSenderIDsRequestFieldID)
}

var (
	deleteSenderIDsResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeleteSenderIDsResponse struct {
	// Indicates whether the request was successful.
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteSenderIDsResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteSenderIDsResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteSenderIDsResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSenderIDsResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deleteSenderIDsResponseFieldSuccess)
}

func (d *DeleteSenderIDsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteSenderIDsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteSenderIDsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteSenderIDsResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteSenderIDsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteSenderIDsResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Expected number of messages sent per month from the Sender ID. One of `1-1000`, `1001-20000`, `20001-50000`, `50001-100000`, or `More than 100000`. Each value is the message-count band for the month.
type SenderIDCreateRequestMonthlyVolume string

const (
	SenderIDCreateRequestMonthlyVolumeOne1000             SenderIDCreateRequestMonthlyVolume = "1-1000"
	SenderIDCreateRequestMonthlyVolumeOneThousandOne20000 SenderIDCreateRequestMonthlyVolume = "1001-20000"
	SenderIDCreateRequestMonthlyVolumeUndefined50000      SenderIDCreateRequestMonthlyVolume = "20001-50000"
	SenderIDCreateRequestMonthlyVolumeUndefined100000     SenderIDCreateRequestMonthlyVolume = "50001-100000"
	SenderIDCreateRequestMonthlyVolumeMoreThan100000      SenderIDCreateRequestMonthlyVolume = "More than 100000"
)

func NewSenderIDCreateRequestMonthlyVolumeFromString(s string) (SenderIDCreateRequestMonthlyVolume, error) {
	switch s {
	case "1-1000":
		return SenderIDCreateRequestMonthlyVolumeOne1000, nil
	case "1001-20000":
		return SenderIDCreateRequestMonthlyVolumeOneThousandOne20000, nil
	case "20001-50000":
		return SenderIDCreateRequestMonthlyVolumeUndefined50000, nil
	case "50001-100000":
		return SenderIDCreateRequestMonthlyVolumeUndefined100000, nil
	case "More than 100000":
		return SenderIDCreateRequestMonthlyVolumeMoreThan100000, nil
	}
	var t SenderIDCreateRequestMonthlyVolume
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SenderIDCreateRequestMonthlyVolume) Ptr() *SenderIDCreateRequestMonthlyVolume {
	return &s
}

// Primary use case for the Sender ID. One of `transactional` (account or order notifications), `promo` (marketing and promotional messages), or `authentication` (one-time passcodes and verification codes).
type SenderIDCreateRequestUsecase string

const (
	SenderIDCreateRequestUsecaseTransactional  SenderIDCreateRequestUsecase = "transactional"
	SenderIDCreateRequestUsecasePromo          SenderIDCreateRequestUsecase = "promo"
	SenderIDCreateRequestUsecaseAuthentication SenderIDCreateRequestUsecase = "authentication"
)

func NewSenderIDCreateRequestUsecaseFromString(s string) (SenderIDCreateRequestUsecase, error) {
	switch s {
	case "transactional":
		return SenderIDCreateRequestUsecaseTransactional, nil
	case "promo":
		return SenderIDCreateRequestUsecasePromo, nil
	case "authentication":
		return SenderIDCreateRequestUsecaseAuthentication, nil
	}
	var t SenderIDCreateRequestUsecase
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SenderIDCreateRequestUsecase) Ptr() *SenderIDCreateRequestUsecase {
	return &s
}
