// Code generated by Fern. DO NOT EDIT.

package tendlc

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateBrandAppealsRequest(t *testing.T) {
	t.Run("SetBrandID", func(t *testing.T) {
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueBrandID string
		obj.SetBrandID(fernTestValueBrandID)
		assert.Equal(t, fernTestValueBrandID, obj.BrandID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAppealCategories", func(t *testing.T) {
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueAppealCategories []CreateBrandAppealsRequestAppealCategoriesItem
		obj.SetAppealCategories(fernTestValueAppealCategories)
		assert.Equal(t, fernTestValueAppealCategories, obj.AppealCategories)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEvidence", func(t *testing.T) {
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueEvidence []string
		obj.SetEvidence(fernTestValueEvidence)
		assert.Equal(t, fernTestValueEvidence, obj.Evidence)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExplanation", func(t *testing.T) {
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueExplanation *string
		obj.SetExplanation(fernTestValueExplanation)
		assert.Equal(t, fernTestValueExplanation, obj.Explanation)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateBrandAppealsRequest(t *testing.T) {
	t.Run("SetBrandID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueBrandID string

		// Act
		obj.SetBrandID(fernTestValueBrandID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAppealCategories_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueAppealCategories []CreateBrandAppealsRequestAppealCategoriesItem

		// Act
		obj.SetAppealCategories(fernTestValueAppealCategories)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEvidence_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueEvidence []string

		// Act
		obj.SetEvidence(fernTestValueEvidence)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExplanation_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateBrandAppealsRequest{}
		var fernTestValueExplanation *string

		// Act
		obj.SetExplanation(fernTestValueExplanation)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListBrandAppealsRequest(t *testing.T) {
	t.Run("SetBrandID", func(t *testing.T) {
		obj := &ListBrandAppealsRequest{}
		var fernTestValueBrandID string
		obj.SetBrandID(fernTestValueBrandID)
		assert.Equal(t, fernTestValueBrandID, obj.BrandID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListBrandAppealsRequest(t *testing.T) {
	t.Run("SetBrandID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListBrandAppealsRequest{}
		var fernTestValueBrandID string

		// Act
		obj.SetBrandID(fernTestValueBrandID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumCreateBrandAppealsRequestAppealCategoriesItem(t *testing.T) {
	t.Run("NewFromString_VERIFY_TAX_ID", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateBrandAppealsRequestAppealCategoriesItemFromString("VERIFY_TAX_ID")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateBrandAppealsRequestAppealCategoriesItem("VERIFY_TAX_ID"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_VERIFY_NON_PROFIT", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateBrandAppealsRequestAppealCategoriesItemFromString("VERIFY_NON_PROFIT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateBrandAppealsRequestAppealCategoriesItem("VERIFY_NON_PROFIT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_VERIFY_GOVERNMENT", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateBrandAppealsRequestAppealCategoriesItemFromString("VERIFY_GOVERNMENT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateBrandAppealsRequestAppealCategoriesItem("VERIFY_GOVERNMENT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateBrandAppealsRequestAppealCategoriesItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateBrandAppealsRequestAppealCategoriesItemFromString("VERIFY_TAX_ID")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
