// Code generated by Fern. DO NOT EDIT.

package tendlc

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	tenDlcBrandVettingAppealCreateRequestFieldBrandID          = big.NewInt(1 << 0)
	tenDlcBrandVettingAppealCreateRequestFieldAppealCategories = big.NewInt(1 << 1)
	tenDlcBrandVettingAppealCreateRequestFieldEvidence         = big.NewInt(1 << 2)
	tenDlcBrandVettingAppealCreateRequestFieldExplanation      = big.NewInt(1 << 3)
	tenDlcBrandVettingAppealCreateRequestFieldEvpID            = big.NewInt(1 << 4)
	tenDlcBrandVettingAppealCreateRequestFieldVettingID        = big.NewInt(1 << 5)
)

type TenDlcBrandVettingAppealCreateRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`
	// List of appeal categories. Allowed values: `VERIFY_TAX_ID`, `VERIFY_NON_PROFIT`, `VERIFY_GOVERNMENT`, `LOW_SCORE`. `LOW_SCORE` is only valid for vetting appeals — brand identity appeals (`ten_dlc_brand_appeals_create`) do not accept it.
	AppealCategories []TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem `json:"appeal_categories" url:"-"`
	// List of evidence IDs associated with the appeal.
	Evidence []string `json:"evidence" url:"-"`
	// Appeal comment or justification.
	Explanation *string `json:"explanation,omitempty" url:"-"`
	// EVP ID.
	EvpID *string `json:"evp_id,omitempty" url:"-"`
	// Vetting ID.
	VettingID *string `json:"vetting_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TenDlcBrandVettingAppealCreateRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetBrandID(brandID string) {
	t.BrandID = brandID
	t.require(tenDlcBrandVettingAppealCreateRequestFieldBrandID)
}

// SetAppealCategories sets the AppealCategories field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetAppealCategories(appealCategories []TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem) {
	t.AppealCategories = appealCategories
	t.require(tenDlcBrandVettingAppealCreateRequestFieldAppealCategories)
}

// SetEvidence sets the Evidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetEvidence(evidence []string) {
	t.Evidence = evidence
	t.require(tenDlcBrandVettingAppealCreateRequestFieldEvidence)
}

// SetExplanation sets the Explanation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetExplanation(explanation *string) {
	t.Explanation = explanation
	t.require(tenDlcBrandVettingAppealCreateRequestFieldExplanation)
}

// SetEvpID sets the EvpID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetEvpID(evpID *string) {
	t.EvpID = evpID
	t.require(tenDlcBrandVettingAppealCreateRequestFieldEvpID)
}

// SetVettingID sets the VettingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandVettingAppealCreateRequest) SetVettingID(vettingID *string) {
	t.VettingID = vettingID
	t.require(tenDlcBrandVettingAppealCreateRequestFieldVettingID)
}

func (t *TenDlcBrandVettingAppealCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler TenDlcBrandVettingAppealCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*t = TenDlcBrandVettingAppealCreateRequest(body)
	return nil
}

func (t *TenDlcBrandVettingAppealCreateRequest) MarshalJSON() ([]byte, error) {
	type embed TenDlcBrandVettingAppealCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listBrandVettingAppealsRequestFieldBrandID = big.NewInt(1 << 0)
)

type ListBrandVettingAppealsRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListBrandVettingAppealsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandVettingAppealsRequest) SetBrandID(brandID string) {
	l.BrandID = brandID
	l.require(listBrandVettingAppealsRequestFieldBrandID)
}

type TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem string

const (
	TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyTaxID      TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem = "VERIFY_TAX_ID"
	TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyNonProfit  TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem = "VERIFY_NON_PROFIT"
	TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyGovernment TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem = "VERIFY_GOVERNMENT"
	TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemLowScore         TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem = "LOW_SCORE"
)

func NewTenDlcBrandVettingAppealCreateRequestAppealCategoriesItemFromString(s string) (TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem, error) {
	switch s {
	case "VERIFY_TAX_ID":
		return TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyTaxID, nil
	case "VERIFY_NON_PROFIT":
		return TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyNonProfit, nil
	case "VERIFY_GOVERNMENT":
		return TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemVerifyGovernment, nil
	case "LOW_SCORE":
		return TenDlcBrandVettingAppealCreateRequestAppealCategoriesItemLowScore, nil
	}
	var t TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem) Ptr() *TenDlcBrandVettingAppealCreateRequestAppealCategoriesItem {
	return &t
}
