// Code generated by Fern. DO NOT EDIT.

package tendlc

import (
	json "encoding/json"
	fmt "fmt"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	deleteBrandsRequestFieldBrandID = big.NewInt(1 << 0)
)

type DeleteBrandsRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteBrandsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteBrandsRequest) SetBrandID(brandID string) {
	d.BrandID = brandID
	d.require(deleteBrandsRequestFieldBrandID)
}

var (
	getBrandsRequestFieldBrandID = big.NewInt(1 << 0)
)

type GetBrandsRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetBrandsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsRequest) SetBrandID(brandID string) {
	g.BrandID = brandID
	g.require(getBrandsRequestFieldBrandID)
}

var (
	listBrandsRequestFieldDbaName       = big.NewInt(1 << 0)
	listBrandsRequestFieldCompanyName   = big.NewInt(1 << 1)
	listBrandsRequestFieldEntityType    = big.NewInt(1 << 2)
	listBrandsRequestFieldStatus        = big.NewInt(1 << 3)
	listBrandsRequestFieldCountry       = big.NewInt(1 << 4)
	listBrandsRequestFieldShowDeleted   = big.NewInt(1 << 5)
	listBrandsRequestFieldEinTaxid      = big.NewInt(1 << 6)
	listBrandsRequestFieldMock          = big.NewInt(1 << 7)
	listBrandsRequestFieldCreatedBefore = big.NewInt(1 << 8)
	listBrandsRequestFieldCreatedAfter  = big.NewInt(1 << 9)
	listBrandsRequestFieldPage          = big.NewInt(1 << 10)
	listBrandsRequestFieldPerPage       = big.NewInt(1 << 11)
)

type ListBrandsRequest struct {
	// Filters Brands by `dba_name` (doing-business-as name). Matches partial values.
	DbaName *string `json:"-" url:"dba_name,omitempty"`
	// Filters Brands by `company_name` (registered legal name). Matches partial values.
	CompanyName *string `json:"-" url:"company_name,omitempty"`
	// Filters Brands by business entity type, such as `PRIVATE_PROFIT`.
	EntityType *string `json:"-" url:"entity_type,omitempty"`
	// Filters Brands by identity verification status, such as `VERIFIED`.
	Status *string `json:"-" url:"status,omitempty"`
	// Filters Brands by registration country, as an ISO 3166-1 alpha-2 code (e.g., `US`).
	Country *string `json:"-" url:"country,omitempty"`
	// When `true`, includes deleted Brands in the results. Default `false`.
	ShowDeleted *bool `json:"-" url:"show_deleted,omitempty"`
	// Filters Brands by their Employer Identification Number (EIN) or tax ID.
	EinTaxid *string `json:"-" url:"ein_taxid,omitempty"`
	// When `true`, returns only mock Brands used for testing. Default `false`.
	Mock *bool `json:"-" url:"mock,omitempty"`
	// Returns brands created on or before this date, in `YYYY-MM-DD` format.
	CreatedBefore *string `json:"-" url:"created_before,omitempty"`
	// Returns brands created on or after this date, in `YYYY-MM-DD` format.
	CreatedAfter *string `json:"-" url:"created_after,omitempty"`
	// Page number to retrieve. Default `1`.
	Page *int `json:"-" url:"page,omitempty"`
	// Number of records to return per page. Default `25`.
	PerPage *int `json:"-" url:"per_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListBrandsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetDbaName sets the DbaName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetDbaName(dbaName *string) {
	l.DbaName = dbaName
	l.require(listBrandsRequestFieldDbaName)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetCompanyName(companyName *string) {
	l.CompanyName = companyName
	l.require(listBrandsRequestFieldCompanyName)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetEntityType(entityType *string) {
	l.EntityType = entityType
	l.require(listBrandsRequestFieldEntityType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetStatus(status *string) {
	l.Status = status
	l.require(listBrandsRequestFieldStatus)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetCountry(country *string) {
	l.Country = country
	l.require(listBrandsRequestFieldCountry)
}

// SetShowDeleted sets the ShowDeleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetShowDeleted(showDeleted *bool) {
	l.ShowDeleted = showDeleted
	l.require(listBrandsRequestFieldShowDeleted)
}

// SetEinTaxid sets the EinTaxid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetEinTaxid(einTaxid *string) {
	l.EinTaxid = einTaxid
	l.require(listBrandsRequestFieldEinTaxid)
}

// SetMock sets the Mock field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetMock(mock *bool) {
	l.Mock = mock
	l.require(listBrandsRequestFieldMock)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetCreatedBefore(createdBefore *string) {
	l.CreatedBefore = createdBefore
	l.require(listBrandsRequestFieldCreatedBefore)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetCreatedAfter(createdAfter *string) {
	l.CreatedAfter = createdAfter
	l.require(listBrandsRequestFieldCreatedAfter)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listBrandsRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listBrandsRequestFieldPerPage)
}

var (
	qualifyUsecaseBrandsRequestFieldBrandID = big.NewInt(1 << 0)
	qualifyUsecaseBrandsRequestFieldUseCase = big.NewInt(1 << 1)
)

type QualifyUsecaseBrandsRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`
	// Name of the use case to qualify the Brand for.
	UseCase QualifyUsecaseBrandsRequestUseCase `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QualifyUsecaseBrandsRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QualifyUsecaseBrandsRequest) SetBrandID(brandID string) {
	q.BrandID = brandID
	q.require(qualifyUsecaseBrandsRequestFieldBrandID)
}

// SetUseCase sets the UseCase field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QualifyUsecaseBrandsRequest) SetUseCase(useCase QualifyUsecaseBrandsRequestUseCase) {
	q.UseCase = useCase
	q.require(qualifyUsecaseBrandsRequestFieldUseCase)
}

// Represents a 10DLC brand registered for application-to-person messaging. A Brand identifies the business behind one or more messaging campaigns.
var (
	createBrandsResponseFieldBrandID         = big.NewInt(1 << 0)
	createBrandsResponseFieldDbaName         = big.NewInt(1 << 1)
	createBrandsResponseFieldCompanyName     = big.NewInt(1 << 2)
	createBrandsResponseFieldEntityType      = big.NewInt(1 << 3)
	createBrandsResponseFieldVertical        = big.NewInt(1 << 4)
	createBrandsResponseFieldEinTaxid        = big.NewInt(1 << 5)
	createBrandsResponseFieldEinTaxidCountry = big.NewInt(1 << 6)
	createBrandsResponseFieldStatus          = big.NewInt(1 << 7)
	createBrandsResponseFieldWebsite         = big.NewInt(1 << 8)
	createBrandsResponseFieldStockSymbol     = big.NewInt(1 << 9)
	createBrandsResponseFieldStockExchange   = big.NewInt(1 << 10)
	createBrandsResponseFieldFirstName       = big.NewInt(1 << 11)
	createBrandsResponseFieldLastName        = big.NewInt(1 << 12)
	createBrandsResponseFieldPhoneNumber     = big.NewInt(1 << 13)
	createBrandsResponseFieldEmail           = big.NewInt(1 << 14)
	createBrandsResponseFieldStreetAddress   = big.NewInt(1 << 15)
	createBrandsResponseFieldCity            = big.NewInt(1 << 16)
	createBrandsResponseFieldStateOrProvince = big.NewInt(1 << 17)
	createBrandsResponseFieldCountry         = big.NewInt(1 << 18)
	createBrandsResponseFieldZip             = big.NewInt(1 << 19)
	createBrandsResponseFieldFeedback        = big.NewInt(1 << 20)
	createBrandsResponseFieldMock            = big.NewInt(1 << 21)
	createBrandsResponseFieldCreatedAt       = big.NewInt(1 << 22)
	createBrandsResponseFieldUpdatedAt       = big.NewInt(1 << 23)
)

type CreateBrandsResponse struct {
	// Unique identifier of the Brand assigned by the registry.
	BrandID string `json:"brand_id" url:"brand_id"`
	// Doing-business-as name, or the public-facing brand name.
	DbaName string `json:"dba_name" url:"dba_name"`
	// Registered legal name of the company that owns the Brand.
	CompanyName string `json:"company_name" url:"company_name"`
	// Company entity type.
	EntityType CreateBrandsResponseEntityType `json:"entity_type" url:"entity_type"`
	// Industry vertical the Brand operates in.
	Vertical string `json:"vertical" url:"vertical"`
	// IRS Employer Identification Number (EIN) or other tax ID of the company.
	EinTaxid string `json:"ein_taxid" url:"ein_taxid"`
	// ISO 3166-1 alpha-2 country code where the Tax ID was issued.
	EinTaxidCountry string `json:"ein_taxid_country" url:"ein_taxid_country"`
	// Brand identity verification status.
	Status CreateBrandsResponseStatus `json:"status" url:"status"`
	// Business website URL.
	Website *string `json:"website,omitempty" url:"website,omitempty"`
	// Stock ticker symbol of the company. Required for publicly traded companies.
	StockSymbol *string `json:"stock_symbol,omitempty" url:"stock_symbol,omitempty"`
	// Code of the stock exchange the company is listed on. Required for publicly traded companies.
	StockExchange *string `json:"stock_exchange,omitempty" url:"stock_exchange,omitempty"`
	// Business contact first name.
	FirstName string `json:"first_name" url:"first_name"`
	// Business contact last name.
	LastName string `json:"last_name" url:"last_name"`
	// Support contact phone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"phone_number"`
	// Support contact email address.
	Email string `json:"email" url:"email"`
	// Street address of the business.
	StreetAddress string `json:"street_address" url:"street_address"`
	// City of the business address.
	City string `json:"city" url:"city"`
	// State or province of the business address.
	StateOrProvince *string `json:"state_or_province,omitempty" url:"state_or_province,omitempty"`
	// ISO 3166-1 alpha-2 country code of the business address.
	Country string `json:"country" url:"country"`
	// ZIP or postal code of the business address.
	Zip string `json:"zip" url:"zip"`
	// Feedback from the identity verification process explaining the current `status`.
	Feedback *string `json:"feedback,omitempty" url:"feedback,omitempty"`
	// Indicates whether the Brand is a mock brand for testing.
	Mock *bool `json:"mock,omitempty" url:"mock,omitempty"`
	// Timestamp when the Brand was created, in ISO 8601 format.
	CreatedAt string `json:"created_at" url:"created_at"`
	// Timestamp when the Brand was last updated, in ISO 8601 format.
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateBrandsResponse) GetBrandID() string {
	if c == nil {
		return ""
	}
	return c.BrandID
}

func (c *CreateBrandsResponse) GetDbaName() string {
	if c == nil {
		return ""
	}
	return c.DbaName
}

func (c *CreateBrandsResponse) GetCompanyName() string {
	if c == nil {
		return ""
	}
	return c.CompanyName
}

func (c *CreateBrandsResponse) GetEntityType() CreateBrandsResponseEntityType {
	if c == nil {
		return ""
	}
	return c.EntityType
}

func (c *CreateBrandsResponse) GetVertical() string {
	if c == nil {
		return ""
	}
	return c.Vertical
}

func (c *CreateBrandsResponse) GetEinTaxid() string {
	if c == nil {
		return ""
	}
	return c.EinTaxid
}

func (c *CreateBrandsResponse) GetEinTaxidCountry() string {
	if c == nil {
		return ""
	}
	return c.EinTaxidCountry
}

func (c *CreateBrandsResponse) GetStatus() CreateBrandsResponseStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateBrandsResponse) GetWebsite() *string {
	if c == nil {
		return nil
	}
	return c.Website
}

func (c *CreateBrandsResponse) GetStockSymbol() *string {
	if c == nil {
		return nil
	}
	return c.StockSymbol
}

func (c *CreateBrandsResponse) GetStockExchange() *string {
	if c == nil {
		return nil
	}
	return c.StockExchange
}

func (c *CreateBrandsResponse) GetFirstName() string {
	if c == nil {
		return ""
	}
	return c.FirstName
}

func (c *CreateBrandsResponse) GetLastName() string {
	if c == nil {
		return ""
	}
	return c.LastName
}

func (c *CreateBrandsResponse) GetPhoneNumber() string {
	if c == nil {
		return ""
	}
	return c.PhoneNumber
}

func (c *CreateBrandsResponse) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CreateBrandsResponse) GetStreetAddress() string {
	if c == nil {
		return ""
	}
	return c.StreetAddress
}

func (c *CreateBrandsResponse) GetCity() string {
	if c == nil {
		return ""
	}
	return c.City
}

func (c *CreateBrandsResponse) GetStateOrProvince() *string {
	if c == nil {
		return nil
	}
	return c.StateOrProvince
}

func (c *CreateBrandsResponse) GetCountry() string {
	if c == nil {
		return ""
	}
	return c.Country
}

func (c *CreateBrandsResponse) GetZip() string {
	if c == nil {
		return ""
	}
	return c.Zip
}

func (c *CreateBrandsResponse) GetFeedback() *string {
	if c == nil {
		return nil
	}
	return c.Feedback
}

func (c *CreateBrandsResponse) GetMock() *bool {
	if c == nil {
		return nil
	}
	return c.Mock
}

func (c *CreateBrandsResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateBrandsResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateBrandsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateBrandsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetBrandID(brandID string) {
	c.BrandID = brandID
	c.require(createBrandsResponseFieldBrandID)
}

// SetDbaName sets the DbaName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetDbaName(dbaName string) {
	c.DbaName = dbaName
	c.require(createBrandsResponseFieldDbaName)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetCompanyName(companyName string) {
	c.CompanyName = companyName
	c.require(createBrandsResponseFieldCompanyName)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetEntityType(entityType CreateBrandsResponseEntityType) {
	c.EntityType = entityType
	c.require(createBrandsResponseFieldEntityType)
}

// SetVertical sets the Vertical field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetVertical(vertical string) {
	c.Vertical = vertical
	c.require(createBrandsResponseFieldVertical)
}

// SetEinTaxid sets the EinTaxid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetEinTaxid(einTaxid string) {
	c.EinTaxid = einTaxid
	c.require(createBrandsResponseFieldEinTaxid)
}

// SetEinTaxidCountry sets the EinTaxidCountry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetEinTaxidCountry(einTaxidCountry string) {
	c.EinTaxidCountry = einTaxidCountry
	c.require(createBrandsResponseFieldEinTaxidCountry)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetStatus(status CreateBrandsResponseStatus) {
	c.Status = status
	c.require(createBrandsResponseFieldStatus)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetWebsite(website *string) {
	c.Website = website
	c.require(createBrandsResponseFieldWebsite)
}

// SetStockSymbol sets the StockSymbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetStockSymbol(stockSymbol *string) {
	c.StockSymbol = stockSymbol
	c.require(createBrandsResponseFieldStockSymbol)
}

// SetStockExchange sets the StockExchange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetStockExchange(stockExchange *string) {
	c.StockExchange = stockExchange
	c.require(createBrandsResponseFieldStockExchange)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetFirstName(firstName string) {
	c.FirstName = firstName
	c.require(createBrandsResponseFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetLastName(lastName string) {
	c.LastName = lastName
	c.require(createBrandsResponseFieldLastName)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetPhoneNumber(phoneNumber string) {
	c.PhoneNumber = phoneNumber
	c.require(createBrandsResponseFieldPhoneNumber)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetEmail(email string) {
	c.Email = email
	c.require(createBrandsResponseFieldEmail)
}

// SetStreetAddress sets the StreetAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetStreetAddress(streetAddress string) {
	c.StreetAddress = streetAddress
	c.require(createBrandsResponseFieldStreetAddress)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetCity(city string) {
	c.City = city
	c.require(createBrandsResponseFieldCity)
}

// SetStateOrProvince sets the StateOrProvince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetStateOrProvince(stateOrProvince *string) {
	c.StateOrProvince = stateOrProvince
	c.require(createBrandsResponseFieldStateOrProvince)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetCountry(country string) {
	c.Country = country
	c.require(createBrandsResponseFieldCountry)
}

// SetZip sets the Zip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetZip(zip string) {
	c.Zip = zip
	c.require(createBrandsResponseFieldZip)
}

// SetFeedback sets the Feedback field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetFeedback(feedback *string) {
	c.Feedback = feedback
	c.require(createBrandsResponseFieldFeedback)
}

// SetMock sets the Mock field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetMock(mock *bool) {
	c.Mock = mock
	c.require(createBrandsResponseFieldMock)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createBrandsResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBrandsResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createBrandsResponseFieldUpdatedAt)
}

func (c *CreateBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed CreateBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateBrandsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Company entity type.
type CreateBrandsResponseEntityType string

const (
	CreateBrandsResponseEntityTypePrivateProfit CreateBrandsResponseEntityType = "PRIVATE_PROFIT"
	CreateBrandsResponseEntityTypePublicProfit  CreateBrandsResponseEntityType = "PUBLIC_PROFIT"
	CreateBrandsResponseEntityTypeNonProfit     CreateBrandsResponseEntityType = "NON_PROFIT"
	CreateBrandsResponseEntityTypeGovernment    CreateBrandsResponseEntityType = "GOVERNMENT"
)

func NewCreateBrandsResponseEntityTypeFromString(s string) (CreateBrandsResponseEntityType, error) {
	switch s {
	case "PRIVATE_PROFIT":
		return CreateBrandsResponseEntityTypePrivateProfit, nil
	case "PUBLIC_PROFIT":
		return CreateBrandsResponseEntityTypePublicProfit, nil
	case "NON_PROFIT":
		return CreateBrandsResponseEntityTypeNonProfit, nil
	case "GOVERNMENT":
		return CreateBrandsResponseEntityTypeGovernment, nil
	}
	var t CreateBrandsResponseEntityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateBrandsResponseEntityType) Ptr() *CreateBrandsResponseEntityType {
	return &c
}

// Brand identity verification status.
type CreateBrandsResponseStatus string

const (
	CreateBrandsResponseStatusReview         CreateBrandsResponseStatus = "REVIEW"
	CreateBrandsResponseStatusVerified       CreateBrandsResponseStatus = "VERIFIED"
	CreateBrandsResponseStatusUnverified     CreateBrandsResponseStatus = "UNVERIFIED"
	CreateBrandsResponseStatusVettedVerified CreateBrandsResponseStatus = "VETTED_VERIFIED"
	CreateBrandsResponseStatusSuspended      CreateBrandsResponseStatus = "SUSPENDED"
)

func NewCreateBrandsResponseStatusFromString(s string) (CreateBrandsResponseStatus, error) {
	switch s {
	case "REVIEW":
		return CreateBrandsResponseStatusReview, nil
	case "VERIFIED":
		return CreateBrandsResponseStatusVerified, nil
	case "UNVERIFIED":
		return CreateBrandsResponseStatusUnverified, nil
	case "VETTED_VERIFIED":
		return CreateBrandsResponseStatusVettedVerified, nil
	case "SUSPENDED":
		return CreateBrandsResponseStatusSuspended, nil
	}
	var t CreateBrandsResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateBrandsResponseStatus) Ptr() *CreateBrandsResponseStatus {
	return &c
}

var (
	deleteBrandsResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeleteBrandsResponse struct {
	// Indicates whether the request was successful.
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteBrandsResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteBrandsResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteBrandsResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteBrandsResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deleteBrandsResponseFieldSuccess)
}

func (d *DeleteBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteBrandsResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Represents a 10DLC brand registered for application-to-person messaging. A Brand identifies the business behind one or more messaging campaigns.
var (
	getBrandsResponseFieldBrandID         = big.NewInt(1 << 0)
	getBrandsResponseFieldDbaName         = big.NewInt(1 << 1)
	getBrandsResponseFieldCompanyName     = big.NewInt(1 << 2)
	getBrandsResponseFieldEntityType      = big.NewInt(1 << 3)
	getBrandsResponseFieldVertical        = big.NewInt(1 << 4)
	getBrandsResponseFieldEinTaxid        = big.NewInt(1 << 5)
	getBrandsResponseFieldEinTaxidCountry = big.NewInt(1 << 6)
	getBrandsResponseFieldStatus          = big.NewInt(1 << 7)
	getBrandsResponseFieldWebsite         = big.NewInt(1 << 8)
	getBrandsResponseFieldStockSymbol     = big.NewInt(1 << 9)
	getBrandsResponseFieldStockExchange   = big.NewInt(1 << 10)
	getBrandsResponseFieldFirstName       = big.NewInt(1 << 11)
	getBrandsResponseFieldLastName        = big.NewInt(1 << 12)
	getBrandsResponseFieldPhoneNumber     = big.NewInt(1 << 13)
	getBrandsResponseFieldEmail           = big.NewInt(1 << 14)
	getBrandsResponseFieldStreetAddress   = big.NewInt(1 << 15)
	getBrandsResponseFieldCity            = big.NewInt(1 << 16)
	getBrandsResponseFieldStateOrProvince = big.NewInt(1 << 17)
	getBrandsResponseFieldCountry         = big.NewInt(1 << 18)
	getBrandsResponseFieldZip             = big.NewInt(1 << 19)
	getBrandsResponseFieldFeedback        = big.NewInt(1 << 20)
	getBrandsResponseFieldMock            = big.NewInt(1 << 21)
	getBrandsResponseFieldCreatedAt       = big.NewInt(1 << 22)
	getBrandsResponseFieldUpdatedAt       = big.NewInt(1 << 23)
)

type GetBrandsResponse struct {
	// Unique identifier of the Brand assigned by the registry.
	BrandID string `json:"brand_id" url:"brand_id"`
	// Doing-business-as name, or the public-facing brand name.
	DbaName string `json:"dba_name" url:"dba_name"`
	// Registered legal name of the company that owns the Brand.
	CompanyName string `json:"company_name" url:"company_name"`
	// Company entity type.
	EntityType GetBrandsResponseEntityType `json:"entity_type" url:"entity_type"`
	// Industry vertical the Brand operates in.
	Vertical string `json:"vertical" url:"vertical"`
	// IRS Employer Identification Number (EIN) or other tax ID of the company.
	EinTaxid string `json:"ein_taxid" url:"ein_taxid"`
	// ISO 3166-1 alpha-2 country code where the Tax ID was issued.
	EinTaxidCountry string `json:"ein_taxid_country" url:"ein_taxid_country"`
	// Brand identity verification status.
	Status GetBrandsResponseStatus `json:"status" url:"status"`
	// Business website URL.
	Website *string `json:"website,omitempty" url:"website,omitempty"`
	// Stock ticker symbol of the company. Required for publicly traded companies.
	StockSymbol *string `json:"stock_symbol,omitempty" url:"stock_symbol,omitempty"`
	// Code of the stock exchange the company is listed on. Required for publicly traded companies.
	StockExchange *string `json:"stock_exchange,omitempty" url:"stock_exchange,omitempty"`
	// Business contact first name.
	FirstName string `json:"first_name" url:"first_name"`
	// Business contact last name.
	LastName string `json:"last_name" url:"last_name"`
	// Support contact phone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"phone_number"`
	// Support contact email address.
	Email string `json:"email" url:"email"`
	// Street address of the business.
	StreetAddress string `json:"street_address" url:"street_address"`
	// City of the business address.
	City string `json:"city" url:"city"`
	// State or province of the business address.
	StateOrProvince *string `json:"state_or_province,omitempty" url:"state_or_province,omitempty"`
	// ISO 3166-1 alpha-2 country code of the business address.
	Country string `json:"country" url:"country"`
	// ZIP or postal code of the business address.
	Zip string `json:"zip" url:"zip"`
	// Feedback from the identity verification process explaining the current `status`.
	Feedback *string `json:"feedback,omitempty" url:"feedback,omitempty"`
	// Indicates whether the Brand is a mock brand for testing.
	Mock *bool `json:"mock,omitempty" url:"mock,omitempty"`
	// Timestamp when the Brand was created, in ISO 8601 format.
	CreatedAt string `json:"created_at" url:"created_at"`
	// Timestamp when the Brand was last updated, in ISO 8601 format.
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetBrandsResponse) GetBrandID() string {
	if g == nil {
		return ""
	}
	return g.BrandID
}

func (g *GetBrandsResponse) GetDbaName() string {
	if g == nil {
		return ""
	}
	return g.DbaName
}

func (g *GetBrandsResponse) GetCompanyName() string {
	if g == nil {
		return ""
	}
	return g.CompanyName
}

func (g *GetBrandsResponse) GetEntityType() GetBrandsResponseEntityType {
	if g == nil {
		return ""
	}
	return g.EntityType
}

func (g *GetBrandsResponse) GetVertical() string {
	if g == nil {
		return ""
	}
	return g.Vertical
}

func (g *GetBrandsResponse) GetEinTaxid() string {
	if g == nil {
		return ""
	}
	return g.EinTaxid
}

func (g *GetBrandsResponse) GetEinTaxidCountry() string {
	if g == nil {
		return ""
	}
	return g.EinTaxidCountry
}

func (g *GetBrandsResponse) GetStatus() GetBrandsResponseStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetBrandsResponse) GetWebsite() *string {
	if g == nil {
		return nil
	}
	return g.Website
}

func (g *GetBrandsResponse) GetStockSymbol() *string {
	if g == nil {
		return nil
	}
	return g.StockSymbol
}

func (g *GetBrandsResponse) GetStockExchange() *string {
	if g == nil {
		return nil
	}
	return g.StockExchange
}

func (g *GetBrandsResponse) GetFirstName() string {
	if g == nil {
		return ""
	}
	return g.FirstName
}

func (g *GetBrandsResponse) GetLastName() string {
	if g == nil {
		return ""
	}
	return g.LastName
}

func (g *GetBrandsResponse) GetPhoneNumber() string {
	if g == nil {
		return ""
	}
	return g.PhoneNumber
}

func (g *GetBrandsResponse) GetEmail() string {
	if g == nil {
		return ""
	}
	return g.Email
}

func (g *GetBrandsResponse) GetStreetAddress() string {
	if g == nil {
		return ""
	}
	return g.StreetAddress
}

func (g *GetBrandsResponse) GetCity() string {
	if g == nil {
		return ""
	}
	return g.City
}

func (g *GetBrandsResponse) GetStateOrProvince() *string {
	if g == nil {
		return nil
	}
	return g.StateOrProvince
}

func (g *GetBrandsResponse) GetCountry() string {
	if g == nil {
		return ""
	}
	return g.Country
}

func (g *GetBrandsResponse) GetZip() string {
	if g == nil {
		return ""
	}
	return g.Zip
}

func (g *GetBrandsResponse) GetFeedback() *string {
	if g == nil {
		return nil
	}
	return g.Feedback
}

func (g *GetBrandsResponse) GetMock() *bool {
	if g == nil {
		return nil
	}
	return g.Mock
}

func (g *GetBrandsResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetBrandsResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetBrandsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetBrandsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetBrandID(brandID string) {
	g.BrandID = brandID
	g.require(getBrandsResponseFieldBrandID)
}

// SetDbaName sets the DbaName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetDbaName(dbaName string) {
	g.DbaName = dbaName
	g.require(getBrandsResponseFieldDbaName)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetCompanyName(companyName string) {
	g.CompanyName = companyName
	g.require(getBrandsResponseFieldCompanyName)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetEntityType(entityType GetBrandsResponseEntityType) {
	g.EntityType = entityType
	g.require(getBrandsResponseFieldEntityType)
}

// SetVertical sets the Vertical field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetVertical(vertical string) {
	g.Vertical = vertical
	g.require(getBrandsResponseFieldVertical)
}

// SetEinTaxid sets the EinTaxid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetEinTaxid(einTaxid string) {
	g.EinTaxid = einTaxid
	g.require(getBrandsResponseFieldEinTaxid)
}

// SetEinTaxidCountry sets the EinTaxidCountry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetEinTaxidCountry(einTaxidCountry string) {
	g.EinTaxidCountry = einTaxidCountry
	g.require(getBrandsResponseFieldEinTaxidCountry)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetStatus(status GetBrandsResponseStatus) {
	g.Status = status
	g.require(getBrandsResponseFieldStatus)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetWebsite(website *string) {
	g.Website = website
	g.require(getBrandsResponseFieldWebsite)
}

// SetStockSymbol sets the StockSymbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetStockSymbol(stockSymbol *string) {
	g.StockSymbol = stockSymbol
	g.require(getBrandsResponseFieldStockSymbol)
}

// SetStockExchange sets the StockExchange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetStockExchange(stockExchange *string) {
	g.StockExchange = stockExchange
	g.require(getBrandsResponseFieldStockExchange)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetFirstName(firstName string) {
	g.FirstName = firstName
	g.require(getBrandsResponseFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetLastName(lastName string) {
	g.LastName = lastName
	g.require(getBrandsResponseFieldLastName)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetPhoneNumber(phoneNumber string) {
	g.PhoneNumber = phoneNumber
	g.require(getBrandsResponseFieldPhoneNumber)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetEmail(email string) {
	g.Email = email
	g.require(getBrandsResponseFieldEmail)
}

// SetStreetAddress sets the StreetAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetStreetAddress(streetAddress string) {
	g.StreetAddress = streetAddress
	g.require(getBrandsResponseFieldStreetAddress)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetCity(city string) {
	g.City = city
	g.require(getBrandsResponseFieldCity)
}

// SetStateOrProvince sets the StateOrProvince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetStateOrProvince(stateOrProvince *string) {
	g.StateOrProvince = stateOrProvince
	g.require(getBrandsResponseFieldStateOrProvince)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetCountry(country string) {
	g.Country = country
	g.require(getBrandsResponseFieldCountry)
}

// SetZip sets the Zip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetZip(zip string) {
	g.Zip = zip
	g.require(getBrandsResponseFieldZip)
}

// SetFeedback sets the Feedback field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetFeedback(feedback *string) {
	g.Feedback = feedback
	g.require(getBrandsResponseFieldFeedback)
}

// SetMock sets the Mock field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetMock(mock *bool) {
	g.Mock = mock
	g.require(getBrandsResponseFieldMock)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getBrandsResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBrandsResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getBrandsResponseFieldUpdatedAt)
}

func (g *GetBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed GetBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetBrandsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Company entity type.
type GetBrandsResponseEntityType string

const (
	GetBrandsResponseEntityTypePrivateProfit GetBrandsResponseEntityType = "PRIVATE_PROFIT"
	GetBrandsResponseEntityTypePublicProfit  GetBrandsResponseEntityType = "PUBLIC_PROFIT"
	GetBrandsResponseEntityTypeNonProfit     GetBrandsResponseEntityType = "NON_PROFIT"
	GetBrandsResponseEntityTypeGovernment    GetBrandsResponseEntityType = "GOVERNMENT"
)

func NewGetBrandsResponseEntityTypeFromString(s string) (GetBrandsResponseEntityType, error) {
	switch s {
	case "PRIVATE_PROFIT":
		return GetBrandsResponseEntityTypePrivateProfit, nil
	case "PUBLIC_PROFIT":
		return GetBrandsResponseEntityTypePublicProfit, nil
	case "NON_PROFIT":
		return GetBrandsResponseEntityTypeNonProfit, nil
	case "GOVERNMENT":
		return GetBrandsResponseEntityTypeGovernment, nil
	}
	var t GetBrandsResponseEntityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetBrandsResponseEntityType) Ptr() *GetBrandsResponseEntityType {
	return &g
}

// Brand identity verification status.
type GetBrandsResponseStatus string

const (
	GetBrandsResponseStatusReview         GetBrandsResponseStatus = "REVIEW"
	GetBrandsResponseStatusVerified       GetBrandsResponseStatus = "VERIFIED"
	GetBrandsResponseStatusUnverified     GetBrandsResponseStatus = "UNVERIFIED"
	GetBrandsResponseStatusVettedVerified GetBrandsResponseStatus = "VETTED_VERIFIED"
	GetBrandsResponseStatusSuspended      GetBrandsResponseStatus = "SUSPENDED"
)

func NewGetBrandsResponseStatusFromString(s string) (GetBrandsResponseStatus, error) {
	switch s {
	case "REVIEW":
		return GetBrandsResponseStatusReview, nil
	case "VERIFIED":
		return GetBrandsResponseStatusVerified, nil
	case "UNVERIFIED":
		return GetBrandsResponseStatusUnverified, nil
	case "VETTED_VERIFIED":
		return GetBrandsResponseStatusVettedVerified, nil
	case "SUSPENDED":
		return GetBrandsResponseStatusSuspended, nil
	}
	var t GetBrandsResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetBrandsResponseStatus) Ptr() *GetBrandsResponseStatus {
	return &g
}

// A list of 10DLC Brands
var (
	listBrandsResponseFieldItems      = big.NewInt(1 << 0)
	listBrandsResponseFieldPagination = big.NewInt(1 << 1)
)

type ListBrandsResponse struct {
	// A paginated list of 10DLC Brands matching the filter criteria
	Items []*wavixgosdk.TenDlcBrand `json:"items" url:"items"`
	// Pagination details
	Pagination *ListBrandsResponsePagination `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListBrandsResponse) GetItems() []*wavixgosdk.TenDlcBrand {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListBrandsResponse) GetPagination() *ListBrandsResponsePagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

func (l *ListBrandsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListBrandsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponse) SetItems(items []*wavixgosdk.TenDlcBrand) {
	l.Items = items
	l.require(listBrandsResponseFieldItems)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponse) SetPagination(pagination *ListBrandsResponsePagination) {
	l.Pagination = pagination
	l.require(listBrandsResponseFieldPagination)
}

func (l *ListBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed ListBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListBrandsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Pagination details
var (
	listBrandsResponsePaginationFieldCurrentPage = big.NewInt(1 << 0)
	listBrandsResponsePaginationFieldPerPage     = big.NewInt(1 << 1)
	listBrandsResponsePaginationFieldTotal       = big.NewInt(1 << 2)
	listBrandsResponsePaginationFieldTotalPages  = big.NewInt(1 << 3)
)

type ListBrandsResponsePagination struct {
	// Current page number.
	CurrentPage int `json:"current_page" url:"current_page"`
	// Number of records per page.
	PerPage int `json:"per_page" url:"per_page"`
	// Total number of records.
	Total int `json:"total" url:"total"`
	// Total number of pages.
	TotalPages int `json:"total_pages" url:"total_pages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListBrandsResponsePagination) GetCurrentPage() int {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListBrandsResponsePagination) GetPerPage() int {
	if l == nil {
		return 0
	}
	return l.PerPage
}

func (l *ListBrandsResponsePagination) GetTotal() int {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListBrandsResponsePagination) GetTotalPages() int {
	if l == nil {
		return 0
	}
	return l.TotalPages
}

func (l *ListBrandsResponsePagination) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListBrandsResponsePagination) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCurrentPage sets the CurrentPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponsePagination) SetCurrentPage(currentPage int) {
	l.CurrentPage = currentPage
	l.require(listBrandsResponsePaginationFieldCurrentPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponsePagination) SetPerPage(perPage int) {
	l.PerPage = perPage
	l.require(listBrandsResponsePaginationFieldPerPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponsePagination) SetTotal(total int) {
	l.Total = total
	l.require(listBrandsResponsePaginationFieldTotal)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBrandsResponsePagination) SetTotalPages(totalPages int) {
	l.TotalPages = totalPages
	l.require(listBrandsResponsePaginationFieldTotalPages)
}

func (l *ListBrandsResponsePagination) UnmarshalJSON(data []byte) error {
	type unmarshaler ListBrandsResponsePagination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListBrandsResponsePagination(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListBrandsResponsePagination) MarshalJSON() ([]byte, error) {
	type embed ListBrandsResponsePagination
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListBrandsResponsePagination) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type QualifyUsecaseBrandsRequestUseCase string

const (
	QualifyUsecaseBrandsRequestUseCaseAgentsFranchises          QualifyUsecaseBrandsRequestUseCase = "AGENTS_FRANCHISES"
	QualifyUsecaseBrandsRequestUseCaseCarrierExempt             QualifyUsecaseBrandsRequestUseCase = "CARRIER_EXEMPT"
	QualifyUsecaseBrandsRequestUseCaseCharity                   QualifyUsecaseBrandsRequestUseCase = "CHARITY"
	QualifyUsecaseBrandsRequestUseCaseEmergency                 QualifyUsecaseBrandsRequestUseCase = "EMERGENCY"
	QualifyUsecaseBrandsRequestUseCaseK12Education              QualifyUsecaseBrandsRequestUseCase = "K12_EDUCATION"
	QualifyUsecaseBrandsRequestUseCaseLowVolume                 QualifyUsecaseBrandsRequestUseCase = "LOW_VOLUME"
	QualifyUsecaseBrandsRequestUseCaseM2M                       QualifyUsecaseBrandsRequestUseCase = "M2M"
	QualifyUsecaseBrandsRequestUseCaseMixed                     QualifyUsecaseBrandsRequestUseCase = "MIXED"
	QualifyUsecaseBrandsRequestUseCasePolitical                 QualifyUsecaseBrandsRequestUseCase = "POLITICAL"
	QualifyUsecaseBrandsRequestUseCaseProxy                     QualifyUsecaseBrandsRequestUseCase = "PROXY"
	QualifyUsecaseBrandsRequestUseCaseSocial                    QualifyUsecaseBrandsRequestUseCase = "SOCIAL"
	QualifyUsecaseBrandsRequestUseCaseSoleProprietor            QualifyUsecaseBrandsRequestUseCase = "SOLE_PROPRIETOR"
	QualifyUsecaseBrandsRequestUseCaseSweepstake                QualifyUsecaseBrandsRequestUseCase = "SWEEPSTAKE"
	QualifyUsecaseBrandsRequestUseCaseTrial                     QualifyUsecaseBrandsRequestUseCase = "TRIAL"
	QualifyUsecaseBrandsRequestUseCaseUcaasHigh                 QualifyUsecaseBrandsRequestUseCase = "UCAAS_HIGH"
	QualifyUsecaseBrandsRequestUseCaseUcaasLow                  QualifyUsecaseBrandsRequestUseCase = "UCAAS_LOW"
	QualifyUsecaseBrandsRequestUseCaseTwoFa                     QualifyUsecaseBrandsRequestUseCase = "2FA"
	QualifyUsecaseBrandsRequestUseCaseAccountNotification       QualifyUsecaseBrandsRequestUseCase = "ACCOUNT_NOTIFICATION"
	QualifyUsecaseBrandsRequestUseCaseCustomerCare              QualifyUsecaseBrandsRequestUseCase = "CUSTOMER_CARE"
	QualifyUsecaseBrandsRequestUseCaseDeliveryNotification      QualifyUsecaseBrandsRequestUseCase = "DELIVERY_NOTIFICATION"
	QualifyUsecaseBrandsRequestUseCaseFraudAlert                QualifyUsecaseBrandsRequestUseCase = "FRAUD_ALERT"
	QualifyUsecaseBrandsRequestUseCaseHigherEducation           QualifyUsecaseBrandsRequestUseCase = "HIGHER_EDUCATION"
	QualifyUsecaseBrandsRequestUseCaseMarketing                 QualifyUsecaseBrandsRequestUseCase = "MARKETING"
	QualifyUsecaseBrandsRequestUseCasePollingVoting             QualifyUsecaseBrandsRequestUseCase = "POLLING_VOTING"
	QualifyUsecaseBrandsRequestUseCasePublicServiceAnnouncement QualifyUsecaseBrandsRequestUseCase = "PUBLIC_SERVICE_ANNOUNCEMENT"
	QualifyUsecaseBrandsRequestUseCaseSecurityAlert             QualifyUsecaseBrandsRequestUseCase = "SECURITY_ALERT"
)

func NewQualifyUsecaseBrandsRequestUseCaseFromString(s string) (QualifyUsecaseBrandsRequestUseCase, error) {
	switch s {
	case "AGENTS_FRANCHISES":
		return QualifyUsecaseBrandsRequestUseCaseAgentsFranchises, nil
	case "CARRIER_EXEMPT":
		return QualifyUsecaseBrandsRequestUseCaseCarrierExempt, nil
	case "CHARITY":
		return QualifyUsecaseBrandsRequestUseCaseCharity, nil
	case "EMERGENCY":
		return QualifyUsecaseBrandsRequestUseCaseEmergency, nil
	case "K12_EDUCATION":
		return QualifyUsecaseBrandsRequestUseCaseK12Education, nil
	case "LOW_VOLUME":
		return QualifyUsecaseBrandsRequestUseCaseLowVolume, nil
	case "M2M":
		return QualifyUsecaseBrandsRequestUseCaseM2M, nil
	case "MIXED":
		return QualifyUsecaseBrandsRequestUseCaseMixed, nil
	case "POLITICAL":
		return QualifyUsecaseBrandsRequestUseCasePolitical, nil
	case "PROXY":
		return QualifyUsecaseBrandsRequestUseCaseProxy, nil
	case "SOCIAL":
		return QualifyUsecaseBrandsRequestUseCaseSocial, nil
	case "SOLE_PROPRIETOR":
		return QualifyUsecaseBrandsRequestUseCaseSoleProprietor, nil
	case "SWEEPSTAKE":
		return QualifyUsecaseBrandsRequestUseCaseSweepstake, nil
	case "TRIAL":
		return QualifyUsecaseBrandsRequestUseCaseTrial, nil
	case "UCAAS_HIGH":
		return QualifyUsecaseBrandsRequestUseCaseUcaasHigh, nil
	case "UCAAS_LOW":
		return QualifyUsecaseBrandsRequestUseCaseUcaasLow, nil
	case "2FA":
		return QualifyUsecaseBrandsRequestUseCaseTwoFa, nil
	case "ACCOUNT_NOTIFICATION":
		return QualifyUsecaseBrandsRequestUseCaseAccountNotification, nil
	case "CUSTOMER_CARE":
		return QualifyUsecaseBrandsRequestUseCaseCustomerCare, nil
	case "DELIVERY_NOTIFICATION":
		return QualifyUsecaseBrandsRequestUseCaseDeliveryNotification, nil
	case "FRAUD_ALERT":
		return QualifyUsecaseBrandsRequestUseCaseFraudAlert, nil
	case "HIGHER_EDUCATION":
		return QualifyUsecaseBrandsRequestUseCaseHigherEducation, nil
	case "MARKETING":
		return QualifyUsecaseBrandsRequestUseCaseMarketing, nil
	case "POLLING_VOTING":
		return QualifyUsecaseBrandsRequestUseCasePollingVoting, nil
	case "PUBLIC_SERVICE_ANNOUNCEMENT":
		return QualifyUsecaseBrandsRequestUseCasePublicServiceAnnouncement, nil
	case "SECURITY_ALERT":
		return QualifyUsecaseBrandsRequestUseCaseSecurityAlert, nil
	}
	var t QualifyUsecaseBrandsRequestUseCase
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QualifyUsecaseBrandsRequestUseCase) Ptr() *QualifyUsecaseBrandsRequestUseCase {
	return &q
}

var (
	qualifyUsecaseBrandsResponseFieldMnoMetadata = big.NewInt(1 << 0)
	qualifyUsecaseBrandsResponseFieldMonthlyFee  = big.NewInt(1 << 1)
	qualifyUsecaseBrandsResponseFieldUsecase     = big.NewInt(1 << 2)
)

type QualifyUsecaseBrandsResponse struct {
	// An array MNO-specific attributes (e.g. AT&T message class) for every MNO the Brand is qualified to run a Campaign with the specified use case.
	MnoMetadata []*wavixgosdk.TenDlcmnoMetadata `json:"mno_metadata" url:"mno_metadata"`
	// Monthly fee associated with any Campaign with this use case
	MonthlyFee float64 `json:"monthly_fee" url:"monthly_fee"`
	// The use case name
	Usecase string `json:"usecase" url:"usecase"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QualifyUsecaseBrandsResponse) GetMnoMetadata() []*wavixgosdk.TenDlcmnoMetadata {
	if q == nil {
		return nil
	}
	return q.MnoMetadata
}

func (q *QualifyUsecaseBrandsResponse) GetMonthlyFee() float64 {
	if q == nil {
		return 0
	}
	return q.MonthlyFee
}

func (q *QualifyUsecaseBrandsResponse) GetUsecase() string {
	if q == nil {
		return ""
	}
	return q.Usecase
}

func (q *QualifyUsecaseBrandsResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QualifyUsecaseBrandsResponse) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetMnoMetadata sets the MnoMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QualifyUsecaseBrandsResponse) SetMnoMetadata(mnoMetadata []*wavixgosdk.TenDlcmnoMetadata) {
	q.MnoMetadata = mnoMetadata
	q.require(qualifyUsecaseBrandsResponseFieldMnoMetadata)
}

// SetMonthlyFee sets the MonthlyFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QualifyUsecaseBrandsResponse) SetMonthlyFee(monthlyFee float64) {
	q.MonthlyFee = monthlyFee
	q.require(qualifyUsecaseBrandsResponseFieldMonthlyFee)
}

// SetUsecase sets the Usecase field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QualifyUsecaseBrandsResponse) SetUsecase(usecase string) {
	q.Usecase = usecase
	q.require(qualifyUsecaseBrandsResponseFieldUsecase)
}

func (q *QualifyUsecaseBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler QualifyUsecaseBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QualifyUsecaseBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QualifyUsecaseBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed QualifyUsecaseBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QualifyUsecaseBrandsResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

// Legal entity type of the company. One of `PRIVATE_PROFIT` (privately held for-profit company), `PUBLIC_PROFIT` (publicly traded for-profit company), `NON_PROFIT` (non-profit organization), or `GOVERNMENT` (government entity).
type TenDlcBrandUpdateRequestEntityType string

const (
	TenDlcBrandUpdateRequestEntityTypePrivateProfit TenDlcBrandUpdateRequestEntityType = "PRIVATE_PROFIT"
	TenDlcBrandUpdateRequestEntityTypePublicProfit  TenDlcBrandUpdateRequestEntityType = "PUBLIC_PROFIT"
	TenDlcBrandUpdateRequestEntityTypeNonProfit     TenDlcBrandUpdateRequestEntityType = "NON_PROFIT"
	TenDlcBrandUpdateRequestEntityTypeGovernment    TenDlcBrandUpdateRequestEntityType = "GOVERNMENT"
)

func NewTenDlcBrandUpdateRequestEntityTypeFromString(s string) (TenDlcBrandUpdateRequestEntityType, error) {
	switch s {
	case "PRIVATE_PROFIT":
		return TenDlcBrandUpdateRequestEntityTypePrivateProfit, nil
	case "PUBLIC_PROFIT":
		return TenDlcBrandUpdateRequestEntityTypePublicProfit, nil
	case "NON_PROFIT":
		return TenDlcBrandUpdateRequestEntityTypeNonProfit, nil
	case "GOVERNMENT":
		return TenDlcBrandUpdateRequestEntityTypeGovernment, nil
	}
	var t TenDlcBrandUpdateRequestEntityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TenDlcBrandUpdateRequestEntityType) Ptr() *TenDlcBrandUpdateRequestEntityType {
	return &t
}

// Business segment the Brand operates in. One of:
//
// - `HEALTHCARE` — healthcare.
// - `PROFESSIONAL` — professional services.
// - `RETAIL` — retail.
// - `TECHNOLOGY` — technology.
// - `EDUCATION` — education.
// - `FINANCIAL` — financial services.
// - `NON_PROFIT` — non-profit organizations.
// - `GOVERNMENT` — government entities.
// - `OTHER` — any segment not listed above.
type TenDlcBrandUpdateRequestVertical string

const (
	TenDlcBrandUpdateRequestVerticalHealthcare   TenDlcBrandUpdateRequestVertical = "HEALTHCARE"
	TenDlcBrandUpdateRequestVerticalProfessional TenDlcBrandUpdateRequestVertical = "PROFESSIONAL"
	TenDlcBrandUpdateRequestVerticalRetail       TenDlcBrandUpdateRequestVertical = "RETAIL"
	TenDlcBrandUpdateRequestVerticalTechnology   TenDlcBrandUpdateRequestVertical = "TECHNOLOGY"
	TenDlcBrandUpdateRequestVerticalEducation    TenDlcBrandUpdateRequestVertical = "EDUCATION"
	TenDlcBrandUpdateRequestVerticalFinancial    TenDlcBrandUpdateRequestVertical = "FINANCIAL"
	TenDlcBrandUpdateRequestVerticalNonProfit    TenDlcBrandUpdateRequestVertical = "NON_PROFIT"
	TenDlcBrandUpdateRequestVerticalGovernment   TenDlcBrandUpdateRequestVertical = "GOVERNMENT"
	TenDlcBrandUpdateRequestVerticalOther        TenDlcBrandUpdateRequestVertical = "OTHER"
)

func NewTenDlcBrandUpdateRequestVerticalFromString(s string) (TenDlcBrandUpdateRequestVertical, error) {
	switch s {
	case "HEALTHCARE":
		return TenDlcBrandUpdateRequestVerticalHealthcare, nil
	case "PROFESSIONAL":
		return TenDlcBrandUpdateRequestVerticalProfessional, nil
	case "RETAIL":
		return TenDlcBrandUpdateRequestVerticalRetail, nil
	case "TECHNOLOGY":
		return TenDlcBrandUpdateRequestVerticalTechnology, nil
	case "EDUCATION":
		return TenDlcBrandUpdateRequestVerticalEducation, nil
	case "FINANCIAL":
		return TenDlcBrandUpdateRequestVerticalFinancial, nil
	case "NON_PROFIT":
		return TenDlcBrandUpdateRequestVerticalNonProfit, nil
	case "GOVERNMENT":
		return TenDlcBrandUpdateRequestVerticalGovernment, nil
	case "OTHER":
		return TenDlcBrandUpdateRequestVerticalOther, nil
	}
	var t TenDlcBrandUpdateRequestVertical
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TenDlcBrandUpdateRequestVertical) Ptr() *TenDlcBrandUpdateRequestVertical {
	return &t
}

// Represents a 10DLC brand registered for application-to-person messaging. A Brand identifies the business behind one or more messaging campaigns.
var (
	updateBrandsResponseFieldBrandID         = big.NewInt(1 << 0)
	updateBrandsResponseFieldDbaName         = big.NewInt(1 << 1)
	updateBrandsResponseFieldCompanyName     = big.NewInt(1 << 2)
	updateBrandsResponseFieldEntityType      = big.NewInt(1 << 3)
	updateBrandsResponseFieldVertical        = big.NewInt(1 << 4)
	updateBrandsResponseFieldEinTaxid        = big.NewInt(1 << 5)
	updateBrandsResponseFieldEinTaxidCountry = big.NewInt(1 << 6)
	updateBrandsResponseFieldStatus          = big.NewInt(1 << 7)
	updateBrandsResponseFieldWebsite         = big.NewInt(1 << 8)
	updateBrandsResponseFieldStockSymbol     = big.NewInt(1 << 9)
	updateBrandsResponseFieldStockExchange   = big.NewInt(1 << 10)
	updateBrandsResponseFieldFirstName       = big.NewInt(1 << 11)
	updateBrandsResponseFieldLastName        = big.NewInt(1 << 12)
	updateBrandsResponseFieldPhoneNumber     = big.NewInt(1 << 13)
	updateBrandsResponseFieldEmail           = big.NewInt(1 << 14)
	updateBrandsResponseFieldStreetAddress   = big.NewInt(1 << 15)
	updateBrandsResponseFieldCity            = big.NewInt(1 << 16)
	updateBrandsResponseFieldStateOrProvince = big.NewInt(1 << 17)
	updateBrandsResponseFieldCountry         = big.NewInt(1 << 18)
	updateBrandsResponseFieldZip             = big.NewInt(1 << 19)
	updateBrandsResponseFieldFeedback        = big.NewInt(1 << 20)
	updateBrandsResponseFieldMock            = big.NewInt(1 << 21)
	updateBrandsResponseFieldCreatedAt       = big.NewInt(1 << 22)
	updateBrandsResponseFieldUpdatedAt       = big.NewInt(1 << 23)
)

type UpdateBrandsResponse struct {
	// Unique identifier of the Brand assigned by the registry.
	BrandID string `json:"brand_id" url:"brand_id"`
	// Doing-business-as name, or the public-facing brand name.
	DbaName string `json:"dba_name" url:"dba_name"`
	// Registered legal name of the company that owns the Brand.
	CompanyName string `json:"company_name" url:"company_name"`
	// Company entity type.
	EntityType UpdateBrandsResponseEntityType `json:"entity_type" url:"entity_type"`
	// Industry vertical the Brand operates in.
	Vertical string `json:"vertical" url:"vertical"`
	// IRS Employer Identification Number (EIN) or other tax ID of the company.
	EinTaxid string `json:"ein_taxid" url:"ein_taxid"`
	// ISO 3166-1 alpha-2 country code where the Tax ID was issued.
	EinTaxidCountry string `json:"ein_taxid_country" url:"ein_taxid_country"`
	// Brand identity verification status.
	Status UpdateBrandsResponseStatus `json:"status" url:"status"`
	// Business website URL.
	Website *string `json:"website,omitempty" url:"website,omitempty"`
	// Stock ticker symbol of the company. Required for publicly traded companies.
	StockSymbol *string `json:"stock_symbol,omitempty" url:"stock_symbol,omitempty"`
	// Code of the stock exchange the company is listed on. Required for publicly traded companies.
	StockExchange *string `json:"stock_exchange,omitempty" url:"stock_exchange,omitempty"`
	// Business contact first name.
	FirstName string `json:"first_name" url:"first_name"`
	// Business contact last name.
	LastName string `json:"last_name" url:"last_name"`
	// Support contact phone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"phone_number"`
	// Support contact email address.
	Email string `json:"email" url:"email"`
	// Street address of the business.
	StreetAddress string `json:"street_address" url:"street_address"`
	// City of the business address.
	City string `json:"city" url:"city"`
	// State or province of the business address.
	StateOrProvince *string `json:"state_or_province,omitempty" url:"state_or_province,omitempty"`
	// ISO 3166-1 alpha-2 country code of the business address.
	Country string `json:"country" url:"country"`
	// ZIP or postal code of the business address.
	Zip string `json:"zip" url:"zip"`
	// Feedback from the identity verification process explaining the current `status`.
	Feedback *string `json:"feedback,omitempty" url:"feedback,omitempty"`
	// Indicates whether the Brand is a mock brand for testing.
	Mock *bool `json:"mock,omitempty" url:"mock,omitempty"`
	// Timestamp when the Brand was created, in ISO 8601 format.
	CreatedAt string `json:"created_at" url:"created_at"`
	// Timestamp when the Brand was last updated, in ISO 8601 format.
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateBrandsResponse) GetBrandID() string {
	if u == nil {
		return ""
	}
	return u.BrandID
}

func (u *UpdateBrandsResponse) GetDbaName() string {
	if u == nil {
		return ""
	}
	return u.DbaName
}

func (u *UpdateBrandsResponse) GetCompanyName() string {
	if u == nil {
		return ""
	}
	return u.CompanyName
}

func (u *UpdateBrandsResponse) GetEntityType() UpdateBrandsResponseEntityType {
	if u == nil {
		return ""
	}
	return u.EntityType
}

func (u *UpdateBrandsResponse) GetVertical() string {
	if u == nil {
		return ""
	}
	return u.Vertical
}

func (u *UpdateBrandsResponse) GetEinTaxid() string {
	if u == nil {
		return ""
	}
	return u.EinTaxid
}

func (u *UpdateBrandsResponse) GetEinTaxidCountry() string {
	if u == nil {
		return ""
	}
	return u.EinTaxidCountry
}

func (u *UpdateBrandsResponse) GetStatus() UpdateBrandsResponseStatus {
	if u == nil {
		return ""
	}
	return u.Status
}

func (u *UpdateBrandsResponse) GetWebsite() *string {
	if u == nil {
		return nil
	}
	return u.Website
}

func (u *UpdateBrandsResponse) GetStockSymbol() *string {
	if u == nil {
		return nil
	}
	return u.StockSymbol
}

func (u *UpdateBrandsResponse) GetStockExchange() *string {
	if u == nil {
		return nil
	}
	return u.StockExchange
}

func (u *UpdateBrandsResponse) GetFirstName() string {
	if u == nil {
		return ""
	}
	return u.FirstName
}

func (u *UpdateBrandsResponse) GetLastName() string {
	if u == nil {
		return ""
	}
	return u.LastName
}

func (u *UpdateBrandsResponse) GetPhoneNumber() string {
	if u == nil {
		return ""
	}
	return u.PhoneNumber
}

func (u *UpdateBrandsResponse) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *UpdateBrandsResponse) GetStreetAddress() string {
	if u == nil {
		return ""
	}
	return u.StreetAddress
}

func (u *UpdateBrandsResponse) GetCity() string {
	if u == nil {
		return ""
	}
	return u.City
}

func (u *UpdateBrandsResponse) GetStateOrProvince() *string {
	if u == nil {
		return nil
	}
	return u.StateOrProvince
}

func (u *UpdateBrandsResponse) GetCountry() string {
	if u == nil {
		return ""
	}
	return u.Country
}

func (u *UpdateBrandsResponse) GetZip() string {
	if u == nil {
		return ""
	}
	return u.Zip
}

func (u *UpdateBrandsResponse) GetFeedback() *string {
	if u == nil {
		return nil
	}
	return u.Feedback
}

func (u *UpdateBrandsResponse) GetMock() *bool {
	if u == nil {
		return nil
	}
	return u.Mock
}

func (u *UpdateBrandsResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateBrandsResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateBrandsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateBrandsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetBrandID(brandID string) {
	u.BrandID = brandID
	u.require(updateBrandsResponseFieldBrandID)
}

// SetDbaName sets the DbaName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetDbaName(dbaName string) {
	u.DbaName = dbaName
	u.require(updateBrandsResponseFieldDbaName)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetCompanyName(companyName string) {
	u.CompanyName = companyName
	u.require(updateBrandsResponseFieldCompanyName)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetEntityType(entityType UpdateBrandsResponseEntityType) {
	u.EntityType = entityType
	u.require(updateBrandsResponseFieldEntityType)
}

// SetVertical sets the Vertical field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetVertical(vertical string) {
	u.Vertical = vertical
	u.require(updateBrandsResponseFieldVertical)
}

// SetEinTaxid sets the EinTaxid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetEinTaxid(einTaxid string) {
	u.EinTaxid = einTaxid
	u.require(updateBrandsResponseFieldEinTaxid)
}

// SetEinTaxidCountry sets the EinTaxidCountry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetEinTaxidCountry(einTaxidCountry string) {
	u.EinTaxidCountry = einTaxidCountry
	u.require(updateBrandsResponseFieldEinTaxidCountry)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetStatus(status UpdateBrandsResponseStatus) {
	u.Status = status
	u.require(updateBrandsResponseFieldStatus)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetWebsite(website *string) {
	u.Website = website
	u.require(updateBrandsResponseFieldWebsite)
}

// SetStockSymbol sets the StockSymbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetStockSymbol(stockSymbol *string) {
	u.StockSymbol = stockSymbol
	u.require(updateBrandsResponseFieldStockSymbol)
}

// SetStockExchange sets the StockExchange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetStockExchange(stockExchange *string) {
	u.StockExchange = stockExchange
	u.require(updateBrandsResponseFieldStockExchange)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetFirstName(firstName string) {
	u.FirstName = firstName
	u.require(updateBrandsResponseFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetLastName(lastName string) {
	u.LastName = lastName
	u.require(updateBrandsResponseFieldLastName)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetPhoneNumber(phoneNumber string) {
	u.PhoneNumber = phoneNumber
	u.require(updateBrandsResponseFieldPhoneNumber)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetEmail(email string) {
	u.Email = email
	u.require(updateBrandsResponseFieldEmail)
}

// SetStreetAddress sets the StreetAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetStreetAddress(streetAddress string) {
	u.StreetAddress = streetAddress
	u.require(updateBrandsResponseFieldStreetAddress)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetCity(city string) {
	u.City = city
	u.require(updateBrandsResponseFieldCity)
}

// SetStateOrProvince sets the StateOrProvince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetStateOrProvince(stateOrProvince *string) {
	u.StateOrProvince = stateOrProvince
	u.require(updateBrandsResponseFieldStateOrProvince)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetCountry(country string) {
	u.Country = country
	u.require(updateBrandsResponseFieldCountry)
}

// SetZip sets the Zip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetZip(zip string) {
	u.Zip = zip
	u.require(updateBrandsResponseFieldZip)
}

// SetFeedback sets the Feedback field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetFeedback(feedback *string) {
	u.Feedback = feedback
	u.require(updateBrandsResponseFieldFeedback)
}

// SetMock sets the Mock field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetMock(mock *bool) {
	u.Mock = mock
	u.require(updateBrandsResponseFieldMock)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateBrandsResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBrandsResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateBrandsResponseFieldUpdatedAt)
}

func (u *UpdateBrandsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateBrandsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateBrandsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateBrandsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateBrandsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateBrandsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Company entity type.
type UpdateBrandsResponseEntityType string

const (
	UpdateBrandsResponseEntityTypePrivateProfit UpdateBrandsResponseEntityType = "PRIVATE_PROFIT"
	UpdateBrandsResponseEntityTypePublicProfit  UpdateBrandsResponseEntityType = "PUBLIC_PROFIT"
	UpdateBrandsResponseEntityTypeNonProfit     UpdateBrandsResponseEntityType = "NON_PROFIT"
	UpdateBrandsResponseEntityTypeGovernment    UpdateBrandsResponseEntityType = "GOVERNMENT"
)

func NewUpdateBrandsResponseEntityTypeFromString(s string) (UpdateBrandsResponseEntityType, error) {
	switch s {
	case "PRIVATE_PROFIT":
		return UpdateBrandsResponseEntityTypePrivateProfit, nil
	case "PUBLIC_PROFIT":
		return UpdateBrandsResponseEntityTypePublicProfit, nil
	case "NON_PROFIT":
		return UpdateBrandsResponseEntityTypeNonProfit, nil
	case "GOVERNMENT":
		return UpdateBrandsResponseEntityTypeGovernment, nil
	}
	var t UpdateBrandsResponseEntityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateBrandsResponseEntityType) Ptr() *UpdateBrandsResponseEntityType {
	return &u
}

// Brand identity verification status.
type UpdateBrandsResponseStatus string

const (
	UpdateBrandsResponseStatusReview         UpdateBrandsResponseStatus = "REVIEW"
	UpdateBrandsResponseStatusVerified       UpdateBrandsResponseStatus = "VERIFIED"
	UpdateBrandsResponseStatusUnverified     UpdateBrandsResponseStatus = "UNVERIFIED"
	UpdateBrandsResponseStatusVettedVerified UpdateBrandsResponseStatus = "VETTED_VERIFIED"
	UpdateBrandsResponseStatusSuspended      UpdateBrandsResponseStatus = "SUSPENDED"
)

func NewUpdateBrandsResponseStatusFromString(s string) (UpdateBrandsResponseStatus, error) {
	switch s {
	case "REVIEW":
		return UpdateBrandsResponseStatusReview, nil
	case "VERIFIED":
		return UpdateBrandsResponseStatusVerified, nil
	case "UNVERIFIED":
		return UpdateBrandsResponseStatusUnverified, nil
	case "VETTED_VERIFIED":
		return UpdateBrandsResponseStatusVettedVerified, nil
	case "SUSPENDED":
		return UpdateBrandsResponseStatusSuspended, nil
	}
	var t UpdateBrandsResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateBrandsResponseStatus) Ptr() *UpdateBrandsResponseStatus {
	return &u
}

var (
	tenDlcBrandUpdateRequestFieldBrandID         = big.NewInt(1 << 0)
	tenDlcBrandUpdateRequestFieldDbaName         = big.NewInt(1 << 1)
	tenDlcBrandUpdateRequestFieldCompanyName     = big.NewInt(1 << 2)
	tenDlcBrandUpdateRequestFieldEntityType      = big.NewInt(1 << 3)
	tenDlcBrandUpdateRequestFieldVertical        = big.NewInt(1 << 4)
	tenDlcBrandUpdateRequestFieldEinTaxid        = big.NewInt(1 << 5)
	tenDlcBrandUpdateRequestFieldEinTaxidCountry = big.NewInt(1 << 6)
	tenDlcBrandUpdateRequestFieldWebsite         = big.NewInt(1 << 7)
	tenDlcBrandUpdateRequestFieldStockSymbol     = big.NewInt(1 << 8)
	tenDlcBrandUpdateRequestFieldStockExchange   = big.NewInt(1 << 9)
	tenDlcBrandUpdateRequestFieldFirstName       = big.NewInt(1 << 10)
	tenDlcBrandUpdateRequestFieldLastName        = big.NewInt(1 << 11)
	tenDlcBrandUpdateRequestFieldPhoneNumber     = big.NewInt(1 << 12)
	tenDlcBrandUpdateRequestFieldEmail           = big.NewInt(1 << 13)
	tenDlcBrandUpdateRequestFieldStreetAddress   = big.NewInt(1 << 14)
	tenDlcBrandUpdateRequestFieldCity            = big.NewInt(1 << 15)
	tenDlcBrandUpdateRequestFieldStateOrProvince = big.NewInt(1 << 16)
	tenDlcBrandUpdateRequestFieldZip             = big.NewInt(1 << 17)
	tenDlcBrandUpdateRequestFieldCountry         = big.NewInt(1 << 18)
	tenDlcBrandUpdateRequestFieldMock            = big.NewInt(1 << 19)
)

type TenDlcBrandUpdateRequest struct {
	// The unique ID of the 10DLC Brand.
	BrandID string `json:"-" url:"-"`
	// Brand name or DBA
	DbaName *string `json:"dba_name,omitempty" url:"-"`
	// Legal name of the company
	CompanyName *string `json:"company_name,omitempty" url:"-"`
	// Legal entity type of the company. One of `PRIVATE_PROFIT` (privately held for-profit company), `PUBLIC_PROFIT` (publicly traded for-profit company), `NON_PROFIT` (non-profit organization), or `GOVERNMENT` (government entity).
	EntityType *TenDlcBrandUpdateRequestEntityType `json:"entity_type,omitempty" url:"-"`
	// Business segment the Brand operates in. One of:
	//
	// - `HEALTHCARE` — healthcare.
	// - `PROFESSIONAL` — professional services.
	// - `RETAIL` — retail.
	// - `TECHNOLOGY` — technology.
	// - `EDUCATION` — education.
	// - `FINANCIAL` — financial services.
	// - `NON_PROFIT` — non-profit organizations.
	// - `GOVERNMENT` — government entities.
	// - `OTHER` — any segment not listed above.
	Vertical *TenDlcBrandUpdateRequestVertical `json:"vertical,omitempty" url:"-"`
	// IRS Employee Identification Number (EIN) for US-based or foreign companies with EIN. The numeric portion of Tax ID for companies incorporated in other countries.
	EinTaxid *string `json:"ein_taxid,omitempty" url:"-"`
	// 2-letter ISO country code of the Tax ID issuing country
	EinTaxidCountry *string `json:"ein_taxid_country,omitempty" url:"-"`
	// The website of the business
	Website *string `json:"website,omitempty" url:"-"`
	// The stock symbol of the Brand. For PUBLIC_PROFIT Brands only.
	StockSymbol *string `json:"stock_symbol,omitempty" url:"-"`
	// The stock exchange code. For PUBLIC_PROFIT Brands only.
	StockExchange *string `json:"stock_exchange,omitempty" url:"-"`
	// The first name of the business contact
	FirstName *string `json:"first_name,omitempty" url:"-"`
	// The last name of the business contact
	LastName *string `json:"last_name,omitempty" url:"-"`
	// The support contact telephone in E.164 format
	PhoneNumber *string `json:"phone_number,omitempty" url:"-"`
	// The email address of the support contact
	Email *string `json:"email,omitempty" url:"-"`
	// Street name and house number
	StreetAddress *string `json:"street_address,omitempty" url:"-"`
	// The city name
	City *string `json:"city,omitempty" url:"-"`
	// State or province. For the United States, use 2 character codes.
	StateOrProvince *string `json:"state_or_province,omitempty" url:"-"`
	// The business zip or postal code
	Zip *string `json:"zip,omitempty" url:"-"`
	// 2-letter ISO country code the business address
	Country *string `json:"country,omitempty" url:"-"`
	// Mock flag for testing (optional, defaults to false)
	Mock *bool `json:"mock,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TenDlcBrandUpdateRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetBrandID sets the BrandID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetBrandID(brandID string) {
	t.BrandID = brandID
	t.require(tenDlcBrandUpdateRequestFieldBrandID)
}

// SetDbaName sets the DbaName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetDbaName(dbaName *string) {
	t.DbaName = dbaName
	t.require(tenDlcBrandUpdateRequestFieldDbaName)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetCompanyName(companyName *string) {
	t.CompanyName = companyName
	t.require(tenDlcBrandUpdateRequestFieldCompanyName)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetEntityType(entityType *TenDlcBrandUpdateRequestEntityType) {
	t.EntityType = entityType
	t.require(tenDlcBrandUpdateRequestFieldEntityType)
}

// SetVertical sets the Vertical field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetVertical(vertical *TenDlcBrandUpdateRequestVertical) {
	t.Vertical = vertical
	t.require(tenDlcBrandUpdateRequestFieldVertical)
}

// SetEinTaxid sets the EinTaxid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetEinTaxid(einTaxid *string) {
	t.EinTaxid = einTaxid
	t.require(tenDlcBrandUpdateRequestFieldEinTaxid)
}

// SetEinTaxidCountry sets the EinTaxidCountry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetEinTaxidCountry(einTaxidCountry *string) {
	t.EinTaxidCountry = einTaxidCountry
	t.require(tenDlcBrandUpdateRequestFieldEinTaxidCountry)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetWebsite(website *string) {
	t.Website = website
	t.require(tenDlcBrandUpdateRequestFieldWebsite)
}

// SetStockSymbol sets the StockSymbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetStockSymbol(stockSymbol *string) {
	t.StockSymbol = stockSymbol
	t.require(tenDlcBrandUpdateRequestFieldStockSymbol)
}

// SetStockExchange sets the StockExchange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetStockExchange(stockExchange *string) {
	t.StockExchange = stockExchange
	t.require(tenDlcBrandUpdateRequestFieldStockExchange)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetFirstName(firstName *string) {
	t.FirstName = firstName
	t.require(tenDlcBrandUpdateRequestFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetLastName(lastName *string) {
	t.LastName = lastName
	t.require(tenDlcBrandUpdateRequestFieldLastName)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetPhoneNumber(phoneNumber *string) {
	t.PhoneNumber = phoneNumber
	t.require(tenDlcBrandUpdateRequestFieldPhoneNumber)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetEmail(email *string) {
	t.Email = email
	t.require(tenDlcBrandUpdateRequestFieldEmail)
}

// SetStreetAddress sets the StreetAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetStreetAddress(streetAddress *string) {
	t.StreetAddress = streetAddress
	t.require(tenDlcBrandUpdateRequestFieldStreetAddress)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetCity(city *string) {
	t.City = city
	t.require(tenDlcBrandUpdateRequestFieldCity)
}

// SetStateOrProvince sets the StateOrProvince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetStateOrProvince(stateOrProvince *string) {
	t.StateOrProvince = stateOrProvince
	t.require(tenDlcBrandUpdateRequestFieldStateOrProvince)
}

// SetZip sets the Zip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetZip(zip *string) {
	t.Zip = zip
	t.require(tenDlcBrandUpdateRequestFieldZip)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetCountry(country *string) {
	t.Country = country
	t.require(tenDlcBrandUpdateRequestFieldCountry)
}

// SetMock sets the Mock field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TenDlcBrandUpdateRequest) SetMock(mock *bool) {
	t.Mock = mock
	t.require(tenDlcBrandUpdateRequestFieldMock)
}

func (t *TenDlcBrandUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler TenDlcBrandUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*t = TenDlcBrandUpdateRequest(body)
	return nil
}

func (t *TenDlcBrandUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed TenDlcBrandUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}
