// Code generated by Fern. DO NOT EDIT.

package brandvettingappeals

import (
	context "context"
	http "net/http"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	option "github.com/wavix/wavix-go-sdk/option"
	tendlc "github.com/wavix/wavix-go-sdk/tendlc"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *tendlc.ListBrandVettingAppealsRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*wavixgosdk.TenDlcBrandVettingAppeal], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.wavix.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v3/10dlc/brands/%v/vettings/appeals",
		request.BrandID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*wavixgosdk.TenDlcBrandVettingAppeal
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(tendlc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*wavixgosdk.TenDlcBrandVettingAppeal]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *tendlc.TenDlcBrandVettingAppealCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*tendlc.CreateBrandVettingAppealsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.wavix.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v3/10dlc/brands/%v/vettings/appeals",
		request.BrandID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *tendlc.CreateBrandVettingAppealsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(tendlc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*tendlc.CreateBrandVettingAppealsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
