// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	brandappeals "github.com/wavix/wavix-go-sdk/tendlc/brandappeals"
	brandevidence "github.com/wavix/wavix-go-sdk/tendlc/brandevidence"
	brands "github.com/wavix/wavix-go-sdk/tendlc/brands"
	brandvettingappeals "github.com/wavix/wavix-go-sdk/tendlc/brandvettingappeals"
	brandvettings "github.com/wavix/wavix-go-sdk/tendlc/brandvettings"
	campaignnumbers "github.com/wavix/wavix-go-sdk/tendlc/campaignnumbers"
	campaigns "github.com/wavix/wavix-go-sdk/tendlc/campaigns"
	subscriptions "github.com/wavix/wavix-go-sdk/tendlc/subscriptions"
)

type Client struct {
	Brands              *brands.Client
	BrandAppeals        *brandappeals.Client
	BrandEvidence       *brandevidence.Client
	BrandVettings       *brandvettings.Client
	BrandVettingAppeals *brandvettingappeals.Client
	Campaigns           *campaigns.Client
	Subscriptions       *subscriptions.Client
	CampaignNumbers     *campaignnumbers.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Brands:              brands.NewClient(options),
		BrandAppeals:        brandappeals.NewClient(options),
		BrandEvidence:       brandevidence.NewClient(options),
		BrandVettings:       brandvettings.NewClient(options),
		BrandVettingAppeals: brandvettingappeals.NewClient(options),
		Campaigns:           campaigns.NewClient(options),
		Subscriptions:       subscriptions.NewClient(options),
		CampaignNumbers:     campaignnumbers.NewClient(options),
		options:             options,
		baseURL:             options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
