// Code generated by Fern. DO NOT EDIT.

package papers

import (
	context "context"
	fmt "fmt"
	http "net/http"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	numbers "github.com/wavix/wavix-go-sdk/numbers"
	option "github.com/wavix/wavix-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Upload(
	ctx context.Context,
	request *numbers.UploadPapersRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*wavixgosdk.NumberDocument], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.wavix.com",
	)
	endpointURL := baseURL + "/v1/numbers/papers"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	writer := internal.NewMultipartWriter()
	if err := writer.WriteField("did_ids", request.DidIDs); err != nil {
		return nil, err
	}
	if err := writer.WriteFile("doc_attachment", request.DocAttachment); err != nil {
		return nil, err
	}
	if err := writer.WriteField("doc_id", fmt.Sprintf("%v", request.DocID)); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.ContentType())

	var response []*wavixgosdk.NumberDocument
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         writer.Buffer(),
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(numbers.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*wavixgosdk.NumberDocument]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
