// Code generated by Fern. DO NOT EDIT.

package callcontrol

import (
	json "encoding/json"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	callAudioPlayRequestFieldID        = big.NewInt(1 << 0)
	callAudioPlayRequestFieldAudioFile = big.NewInt(1 << 1)
)

type CallAudioPlayRequest struct {
	// The `uuid` of the call.
	ID string `json:"-" url:"-"`
	// URL of the audio file to play to the call.
	AudioFile string `json:"audio_file" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CallAudioPlayRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallAudioPlayRequest) SetID(id string) {
	c.ID = id
	c.require(callAudioPlayRequestFieldID)
}

// SetAudioFile sets the AudioFile field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallAudioPlayRequest) SetAudioFile(audioFile string) {
	c.AudioFile = audioFile
	c.require(callAudioPlayRequestFieldAudioFile)
}

func (c *CallAudioPlayRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CallAudioPlayRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CallAudioPlayRequest(body)
	return nil
}

func (c *CallAudioPlayRequest) MarshalJSON() ([]byte, error) {
	type embed CallAudioPlayRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	stopAudioRequestFieldID = big.NewInt(1 << 0)
)

type StopAudioRequest struct {
	// The `uuid` of the call.
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopAudioRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAudioRequest) SetID(id string) {
	s.ID = id
	s.require(stopAudioRequestFieldID)
}
