// Code generated by Fern. DO NOT EDIT.

package ten_dlc_campaigns_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	client "github.com/wavix/wavix-go-sdk/client"
	option "github.com/wavix/wavix-go-sdk/option"
	tendlc "github.com/wavix/wavix-go-sdk/tendlc"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTenDlcCampaignsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.ListCampaignsRequest{
		Name: wavixgosdk.String(
			"Name",
		),
		Usecase: wavixgosdk.String(
			"2FA",
		),
		Status: wavixgosdk.String(
			"APPROVED",
		),
		Mock: wavixgosdk.Bool(
			true,
		),
		CreatedBefore: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2024-08-22",
			),
		),
		CreatedAfter: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2024-08-22",
			),
		),
		Page: wavixgosdk.Int(
			1,
		),
		PerPage: wavixgosdk.Int(
			25,
		),
	}
	_, invocationErr := client.TenDlc.Campaigns.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsListWithWireMock", "GET", "/v3/10dlc/brands/campaigns", map[string]interface{}{"name": "Name", "usecase": "2FA", "status": "APPROVED", "mock": "true", "created_before": "2024-08-22", "created_after": "2024-08-22", "page": "1", "per_page": "25"}, 1)
}

func TestTenDlcCampaignsListByBrandWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.ListByBrandCampaignsRequest{
		BrandID: "BM20QP9",
		Name: wavixgosdk.String(
			"Name",
		),
		Usecase: wavixgosdk.String(
			"2FA",
		),
		Status: wavixgosdk.String(
			"APPROVED",
		),
		Mock: wavixgosdk.Bool(
			true,
		),
		CreatedBefore: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2024-08-22",
			),
		),
		CreatedAfter: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2024-08-22",
			),
		),
		Page: wavixgosdk.Int(
			1,
		),
		PerPage: wavixgosdk.Int(
			25,
		),
	}
	_, invocationErr := client.TenDlc.Campaigns.ListByBrand(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsListByBrandWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsListByBrandWithWireMock", "GET", "/v3/10dlc/brands/BM20QP9/campaigns", map[string]interface{}{"name": "Name", "usecase": "2FA", "status": "APPROVED", "mock": "true", "created_before": "2024-08-22", "created_after": "2024-08-22", "page": "1", "per_page": "25"}, 1)
}

func TestTenDlcCampaignsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.TenDlcCampaignCreateRequest{
		BrandID:            "BM20QP9",
		AffiliateMarketing: false,
		AgeGated:           false,
		AutoRenewal:        false,
		DirectLending:      false,
		EmbeddedLinks:      false,
		EmbeddedPhones: wavixgosdk.Bool(
			false,
		),
		EmbeddedLinkSample: wavixgosdk.String(
			"https://site.com/verify",
		),
		Description:    "Our campaign aims to …",
		OptinWorkflow:  "Our SMS ...",
		Help:           true,
		HelpKeywords:   "help",
		HelpMessage:    "For help, please visit www.site.com. To opt-out, reply STOP.",
		Optin:          true,
		OptinKeywords:  "begin,start",
		OptinMessage:   "You are now opted-in for help please reply HELP, to stop please reply STOP",
		Optout:         true,
		OptoutKeywords: "stop,quit,unsubscribe",
		OptoutMessage:  "You are now opted out and will receive no further messages",
		Name:           "My first campaign",
		Sample1:        "Your verification code is XXXXXX",
		Sample2: wavixgosdk.String(
			"XXXX is your verification code",
		),
		Sample3: wavixgosdk.String(
			"Your code is XXXXXX, valid for 10 minutes",
		),
		Sample4: wavixgosdk.String(
			"Use code XXXXXX to confirm your login",
		),
		Sample5: wavixgosdk.String(
			"XXXXXX is your one-time passcode",
		),
		Mock:    false,
		Usecase: "2FA",
		PrivacyPolicy: wavixgosdk.String(
			"https://site.com/privacy-policy",
		),
		TermsConditions: "https://site.com/terms-and-conditions",
	}
	_, invocationErr := client.TenDlc.Campaigns.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsCreateWithWireMock", "POST", "/v3/10dlc/brands/BM20QP9/campaigns", nil, 1)
}

func TestTenDlcCampaignsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.GetCampaignsRequest{
		BrandID:    "BM20QP9",
		CampaignID: "CKLCK95",
	}
	_, invocationErr := client.TenDlc.Campaigns.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsGetWithWireMock", "GET", "/v3/10dlc/brands/BM20QP9/campaigns/CKLCK95", nil, 1)
}

func TestTenDlcCampaignsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.TenDlcCampaignUpdateRequest{
		BrandID:    "BM20QP9",
		CampaignID: "CKLCK95",
	}
	_, invocationErr := client.TenDlc.Campaigns.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsUpdateWithWireMock", "PUT", "/v3/10dlc/brands/BM20QP9/campaigns/CKLCK95", nil, 1)
}

func TestTenDlcCampaignsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.DeleteCampaignsRequest{
		BrandID:    "BM20QP9",
		CampaignID: "CKLCK95",
	}
	_, invocationErr := client.TenDlc.Campaigns.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsDeleteWithWireMock", "DELETE", "/v3/10dlc/brands/BM20QP9/campaigns/CKLCK95", nil, 1)
}

func TestTenDlcCampaignsNudgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &tendlc.NudgeCampaignsRequest{
		BrandID:     "B9FXYNH",
		CampaignID:  "CSJ4TV0",
		NudgeIntent: "REVIEW",
		Description: "Please review the campaign.",
	}
	_, invocationErr := client.TenDlc.Campaigns.Nudge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTenDlcCampaignsNudgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTenDlcCampaignsNudgeWithWireMock", "POST", "/v3/10dlc/brands/B9FXYNH/campaigns/CSJ4TV0/nudge", nil, 1)
}
