// Code generated by Fern. DO NOT EDIT.

package brandvettings

import (
	context "context"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	option "github.com/wavix/wavix-go-sdk/option"
	tendlc "github.com/wavix/wavix-go-sdk/tendlc"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the external vettings for the 10DLC Brand identified by `brand_id`.
func (c *Client) List(
	ctx context.Context,
	request *tendlc.ListBrandVettingsRequest,
	opts ...option.RequestOption,
) ([]*wavixgosdk.TenDlcBrandVetting, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requests external vetting for a 10DLC Brand. Supported providers: `AEGIS`, `CV`, `WMC`. Supported classes: `STANDARD`, `ENHANCED`.
func (c *Client) Create(
	ctx context.Context,
	request *tendlc.TenDlcBrandVettingCreateRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.TenDlcBrandVetting, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Imports an existing external vetting record into the 10DLC Brand identified by `brand_id`.
func (c *Client) Import(
	ctx context.Context,
	request *tendlc.TenDlcBrandVettingImportRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.TenDlcBrandVetting, error) {
	response, err := c.WithRawResponse.Import(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
