// Code generated by Fern. DO NOT EDIT.

package buy

import (
	json "encoding/json"
	fmt "fmt"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	internal "github.com/wavix/wavix-go-sdk/internal"
	big "math/big"
)

var (
	listCitiesRequestFieldCountryID       = big.NewInt(1 << 0)
	listCitiesRequestFieldTextEnabledOnly = big.NewInt(1 << 1)
)

type ListCitiesRequest struct {
	// The unique ID of the country.
	CountryID int `json:"-" url:"-"`
	// When `true`, returns only cities that offer text-enabled numbers.
	TextEnabledOnly *bool `json:"-" url:"text_enabled_only,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCitiesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCountryID sets the CountryID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCitiesRequest) SetCountryID(countryID int) {
	l.CountryID = countryID
	l.require(listCitiesRequestFieldCountryID)
}

// SetTextEnabledOnly sets the TextEnabledOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCitiesRequest) SetTextEnabledOnly(textEnabledOnly *bool) {
	l.TextEnabledOnly = textEnabledOnly
	l.require(listCitiesRequestFieldTextEnabledOnly)
}

var (
	listCitiesResponseFieldCities = big.NewInt(1 << 0)
)

type ListCitiesResponse struct {
	// Cities available for the requested country or region.
	Cities []*wavixgosdk.City `json:"cities" url:"cities"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListCitiesResponse) GetCities() []*wavixgosdk.City {
	if l == nil {
		return nil
	}
	return l.Cities
}

func (l *ListCitiesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListCitiesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCities sets the Cities field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCitiesResponse) SetCities(cities []*wavixgosdk.City) {
	l.Cities = cities
	l.require(listCitiesResponseFieldCities)
}

func (l *ListCitiesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListCitiesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListCitiesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListCitiesResponse) MarshalJSON() ([]byte, error) {
	type embed ListCitiesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListCitiesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
