// Code generated by Fern. DO NOT EDIT.

package call_recording_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	client "github.com/wavix/wavix-go-sdk/client"
	option "github.com/wavix/wavix-go-sdk/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCallRecordingListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &wavixgosdk.ListCallRecordingRequest{
		FromDate: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2023-01-01",
			),
		),
		ToDate: wavixgosdk.Time(
			wavixgosdk.MustParseDate(
				"2023-12-31",
			),
		),
		From: wavixgosdk.String(
			"123456",
		),
		To: wavixgosdk.String(
			"1987654321",
		),
		CallUUID: wavixgosdk.String(
			"aa566501-c591-4a8b-b3b9-cc1295398b72",
		),
		Page: wavixgosdk.Int(
			1,
		),
		PerPage: wavixgosdk.Int(
			25,
		),
	}
	_, invocationErr := client.CallRecording.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCallRecordingListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCallRecordingListWithWireMock", "GET", "/v1/recordings", map[string]interface{}{"from_date": "2023-01-01", "to_date": "2023-12-31", "from": "123456", "to": "1987654321", "call_uuid": "aa566501-c591-4a8b-b3b9-cc1295398b72", "page": "1", "per_page": "25"}, 1)
}

func TestCallRecordingGetByCallWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &wavixgosdk.GetByCallCallRecordingRequest{
		CallID: "aa566501-c591-4a8b-b3b9-cc1295398b72",
	}
	invocationErr := client.CallRecording.GetByCall(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCallRecordingGetByCallWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCallRecordingGetByCallWithWireMock", "GET", "/v1/recordings/aa566501-c591-4a8b-b3b9-cc1295398b72", nil, 1)
}

func TestCallRecordingGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &wavixgosdk.GetCallRecordingRequest{
		ID: 123,
	}
	_, invocationErr := client.CallRecording.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCallRecordingGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCallRecordingGetWithWireMock", "GET", "/v1/recordings/123", nil, 1)
}

func TestCallRecordingDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &wavixgosdk.DeleteCallRecordingRequest{
		ID: 123,
	}
	_, invocationErr := client.CallRecording.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCallRecordingDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCallRecordingDeleteWithWireMock", "DELETE", "/v1/recordings/123", nil, 1)
}
