// Code generated by Fern. DO NOT EDIT.

package twofa

import (
	big "math/big"
)

var (
	listEventsRequestFieldSessionID = big.NewInt(1 << 0)
)

type ListEventsRequest struct {
	// The unique ID of the 2FA verification session.
	SessionID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListEventsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetSessionID(sessionID string) {
	l.SessionID = sessionID
	l.require(listEventsRequestFieldSessionID)
}
