// Code generated by Fern. DO NOT EDIT.

package twofa

import (
	big "math/big"
	time "time"
)

var (
	listSessionsRequestFieldServiceID = big.NewInt(1 << 0)
	listSessionsRequestFieldFrom      = big.NewInt(1 << 1)
	listSessionsRequestFieldTo        = big.NewInt(1 << 2)
)

type ListSessionsRequest struct {
	// The unique ID of the 2FA service.
	ServiceID string `json:"-" url:"-"`
	// Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	From time.Time `json:"-" url:"from" format:"date"`
	// End of the date range to query, in `YYYY-MM-DD` format. Inclusive.
	To time.Time `json:"-" url:"to" format:"date"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSessionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetServiceID sets the ServiceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetServiceID(serviceID string) {
	l.ServiceID = serviceID
	l.require(listSessionsRequestFieldServiceID)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetFrom(from time.Time) {
	l.From = from
	l.require(listSessionsRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetTo(to time.Time) {
	l.To = to
	l.require(listSessionsRequestFieldTo)
}
