// Code generated by Fern. DO NOT EDIT.

package twofa

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	testing "testing"
	time "time"
)

func TestSettersCancelVerificationRequest(t *testing.T) {
	t.Run("SetSessionID", func(t *testing.T) {
		obj := &CancelVerificationRequest{}
		var fernTestValueSessionID string
		obj.SetSessionID(fernTestValueSessionID)
		assert.Equal(t, fernTestValueSessionID, obj.SessionID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCancelVerificationRequest(t *testing.T) {
	t.Run("SetSessionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CancelVerificationRequest{}
		var fernTestValueSessionID string

		// Act
		obj.SetSessionID(fernTestValueSessionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTwoFactorVerificationCheckRequest(t *testing.T) {
	t.Run("SetSessionID", func(t *testing.T) {
		obj := &TwoFactorVerificationCheckRequest{}
		var fernTestValueSessionID string
		obj.SetSessionID(fernTestValueSessionID)
		assert.Equal(t, fernTestValueSessionID, obj.SessionID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCode", func(t *testing.T) {
		obj := &TwoFactorVerificationCheckRequest{}
		var fernTestValueCode string
		obj.SetCode(fernTestValueCode)
		assert.Equal(t, fernTestValueCode, obj.Code)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTwoFactorVerificationCheckRequest(t *testing.T) {
	t.Run("SetSessionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationCheckRequest{}
		var fernTestValueSessionID string

		// Act
		obj.SetSessionID(fernTestValueSessionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationCheckRequest{}
		var fernTestValueCode string

		// Act
		obj.SetCode(fernTestValueCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTwoFactorVerificationCreateRequest(t *testing.T) {
	t.Run("SetServiceID", func(t *testing.T) {
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueServiceID string
		obj.SetServiceID(fernTestValueServiceID)
		assert.Equal(t, fernTestValueServiceID, obj.ServiceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueTo string
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChannel", func(t *testing.T) {
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueChannel string
		obj.SetChannel(fernTestValueChannel)
		assert.Equal(t, fernTestValueChannel, obj.Channel)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTwoFactorVerificationCreateRequest(t *testing.T) {
	t.Run("SetServiceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueServiceID string

		// Act
		obj.SetServiceID(fernTestValueServiceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueTo string

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChannel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationCreateRequest{}
		var fernTestValueChannel string

		// Act
		obj.SetChannel(fernTestValueChannel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTwoFactorVerificationResendRequest(t *testing.T) {
	t.Run("SetSessionID", func(t *testing.T) {
		obj := &TwoFactorVerificationResendRequest{}
		var fernTestValueSessionID string
		obj.SetSessionID(fernTestValueSessionID)
		assert.Equal(t, fernTestValueSessionID, obj.SessionID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChannel", func(t *testing.T) {
		obj := &TwoFactorVerificationResendRequest{}
		var fernTestValueChannel TwoFactorVerificationResendRequestChannel
		obj.SetChannel(fernTestValueChannel)
		assert.Equal(t, fernTestValueChannel, obj.Channel)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTwoFactorVerificationResendRequest(t *testing.T) {
	t.Run("SetSessionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationResendRequest{}
		var fernTestValueSessionID string

		// Act
		obj.SetSessionID(fernTestValueSessionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChannel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwoFactorVerificationResendRequest{}
		var fernTestValueChannel TwoFactorVerificationResendRequestChannel

		// Act
		obj.SetChannel(fernTestValueChannel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCheckVerificationResponse(t *testing.T) {
	t.Run("SetIsValid", func(t *testing.T) {
		obj := &CheckVerificationResponse{}
		var fernTestValueIsValid bool
		obj.SetIsValid(fernTestValueIsValid)
		assert.Equal(t, fernTestValueIsValid, obj.IsValid)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckVerificationResponse(t *testing.T) {
	t.Run("GetIsValid", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckVerificationResponse{}
		var expected bool
		obj.IsValid = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsValid(), "getter should return the property value")
	})

	t.Run("GetIsValid_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsValid() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckVerificationResponse(t *testing.T) {
	t.Run("SetIsValid_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckVerificationResponse{}
		var fernTestValueIsValid bool

		// Act
		obj.SetIsValid(fernTestValueIsValid)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateVerificationResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetServiceID", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueServiceID string
		obj.SetServiceID(fernTestValueServiceID)
		assert.Equal(t, fernTestValueServiceID, obj.ServiceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionURL", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueSessionURL string
		obj.SetSessionURL(fernTestValueSessionURL)
		assert.Equal(t, fernTestValueSessionURL, obj.SessionURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionID", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueSessionID string
		obj.SetSessionID(fernTestValueSessionID)
		assert.Equal(t, fernTestValueSessionID, obj.SessionID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDestination", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueDestination string
		obj.SetDestination(fernTestValueDestination)
		assert.Equal(t, fernTestValueDestination, obj.Destination)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNumberLookup", func(t *testing.T) {
		obj := &CreateVerificationResponse{}
		var fernTestValueNumberLookup *wavixgosdk.PhoneLookupDetails
		obj.SetNumberLookup(fernTestValueNumberLookup)
		assert.Equal(t, fernTestValueNumberLookup, obj.NumberLookup)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateVerificationResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetServiceID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected string
		obj.ServiceID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetServiceID(), "getter should return the property value")
	})

	t.Run("GetServiceID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetServiceID() // Should return zero value
	})

	t.Run("GetSessionURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected string
		obj.SessionURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionURL(), "getter should return the property value")
	})

	t.Run("GetSessionURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionURL() // Should return zero value
	})

	t.Run("GetSessionID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected string
		obj.SessionID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionID(), "getter should return the property value")
	})

	t.Run("GetSessionID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionID() // Should return zero value
	})

	t.Run("GetDestination", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected string
		obj.Destination = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDestination(), "getter should return the property value")
	})

	t.Run("GetDestination_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDestination() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetNumberLookup", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var expected *wavixgosdk.PhoneLookupDetails
		obj.NumberLookup = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNumberLookup(), "getter should return the property value")
	})

	t.Run("GetNumberLookup_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		obj.NumberLookup = nil

		// Act & Assert
		assert.Nil(t, obj.GetNumberLookup(), "getter should return nil when property is nil")
	})

	t.Run("GetNumberLookup_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNumberLookup() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateVerificationResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetServiceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueServiceID string

		// Act
		obj.SetServiceID(fernTestValueServiceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueSessionURL string

		// Act
		obj.SetSessionURL(fernTestValueSessionURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueSessionID string

		// Act
		obj.SetSessionID(fernTestValueSessionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDestination_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueDestination string

		// Act
		obj.SetDestination(fernTestValueDestination)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNumberLookup_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}
		var fernTestValueNumberLookup *wavixgosdk.PhoneLookupDetails

		// Act
		obj.SetNumberLookup(fernTestValueNumberLookup)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersResendVerificationResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &ResendVerificationResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChannel", func(t *testing.T) {
		obj := &ResendVerificationResponse{}
		var fernTestValueChannel string
		obj.SetChannel(fernTestValueChannel)
		assert.Equal(t, fernTestValueChannel, obj.Channel)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDestination", func(t *testing.T) {
		obj := &ResendVerificationResponse{}
		var fernTestValueDestination string
		obj.SetDestination(fernTestValueDestination)
		assert.Equal(t, fernTestValueDestination, obj.Destination)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ResendVerificationResponse{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersResendVerificationResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetChannel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var expected string
		obj.Channel = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetChannel(), "getter should return the property value")
	})

	t.Run("GetChannel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetChannel() // Should return zero value
	})

	t.Run("GetDestination", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var expected string
		obj.Destination = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDestination(), "getter should return the property value")
	})

	t.Run("GetDestination_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDestination() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitResendVerificationResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChannel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var fernTestValueChannel string

		// Act
		obj.SetChannel(fernTestValueChannel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDestination_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var fernTestValueDestination string

		// Act
		obj.SetDestination(fernTestValueDestination)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCheckVerificationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckVerificationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckVerificationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckVerificationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CheckVerificationResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCreateVerificationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVerificationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateVerificationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateVerificationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateVerificationResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingResendVerificationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendVerificationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ResendVerificationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ResendVerificationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ResendVerificationResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCheckVerificationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckVerificationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckVerificationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCreateVerificationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateVerificationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringResendVerificationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ResendVerificationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumTwoFactorVerificationResendRequestChannel(t *testing.T) {
	t.Run("NewFromString_sms", func(t *testing.T) {
		t.Parallel()
		val, err := NewTwoFactorVerificationResendRequestChannelFromString("sms")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TwoFactorVerificationResendRequestChannel("sms"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_voice", func(t *testing.T) {
		t.Parallel()
		val, err := NewTwoFactorVerificationResendRequestChannelFromString("voice")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TwoFactorVerificationResendRequestChannel("voice"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTwoFactorVerificationResendRequestChannelFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTwoFactorVerificationResendRequestChannelFromString("sms")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCheckVerificationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckVerificationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckVerificationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCreateVerificationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateVerificationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateVerificationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesResendVerificationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ResendVerificationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ResendVerificationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
