// Code generated by Fern. DO NOT EDIT.

package numbers

import (
	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	400: func(apiError *core.APIError) error {
		return &wavixgosdk.BadRequestError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &wavixgosdk.ForbiddenError{
			APIError: apiError,
		}
	},
}
