// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	wavixgosdk "github.com/wavix/wavix-go-sdk"
	core "github.com/wavix/wavix-go-sdk/core"
	internal "github.com/wavix/wavix-go-sdk/internal"
	metrics "github.com/wavix/wavix-go-sdk/linkshortener/metrics"
	option "github.com/wavix/wavix-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient
	Metrics         *metrics.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Metrics:         metrics.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates a short link that redirects to the target URL and tracks click metrics.
func (c *Client) Create(
	ctx context.Context,
	request *wavixgosdk.ShortLinkCreateRequest,
	opts ...option.RequestOption,
) (*wavixgosdk.ShortLinkResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
